# 또래지명 파트

In [152]:
# 학생 명단 불러오기
import pandas as pd
students = pd.read_excel('학생_명단_역할부여.xlsx')
# 컬럼 변경
students.rename(columns={'부여_역할': '역할'}, inplace=True)
students

       반   이름       역할
0     1반  조하준      사교형
1     1반  장시우      경청형
2     1반  서소율  관계갈등핵심형
3     1반  이연우    주의산만형
4     1반  배유준    고립위험형
..   ...  ...      ...
195  10반  정채은  관계갈등핵심형
196  10반  한준서      집중형
197  10반  한유준   균형조정키형
198  10반  김우진    기초보완형
199  10반  홍지안      관망형

[200 rows x 3 columns]

In [153]:
# 역할별 가중치 불러오기
role_weights = pd.read_excel('역할_척도_가중치_매트릭스_v2.xlsx')
# 컬럼 변경
role_weights.rename(columns={'role_name': '역할'}, inplace=True)
role_weights

,역할,지각된 인기,사회적 선호,외현적 공격성,관계적 공격성,친사회성,또래 괴롭힘 가해,또래 괴롭힘 피해,친한친구,학습친구,...,정서적 공감,인지적 공감,내재화(우울),또래공동체 의식 (학급),행동적 수업참여,정서적 수업참여,협동적 태도,경쟁적 태도,애정,거부
0,학습리더형,0.629666,0.350517,0.100000,0.100000,1.000000,0.100000,0.370144,0.564614,1.000000,...,0.800000,0.800000,0.597281,0.412492,0.900000,0.900000,1.000000,0.519230,1.000000,0.100000
1,성실과제형,0.523842,0.459291,0.613186,0.593080,0.648052,0.446633,0.375694,0.497493,0.592793,...,0.358640,0.605908,0.432174,0.577542,0.607542,0.354194,0.484445,0.628502,0.492076,0.478331
2,질문형,0.484660,0.473200,0.362590,0.559484,0.475738,0.393422,0.553183,0.626170,0.412355,...,0.451405,0.479343,0.478881,0.542011,0.506624,0.432606,0.364964,0.380376,0.545494,0.552506
3,집중형,0.367416,0.548041,0.617714,0.645979,0.443788,0.427854,0.548847,0.596732,0.382268,...,0.415659,0.424876,0.420038,0.374443,0.516689,0.513214,0.401721,0.377986,0.483729,0.589496
4,기초보완형,0.360677,0.589082,0.509508,0.474634,0.515946,0.599404,0.534133,0.458979,0.583331,...,0.369326,0.388228,0.557807,0.374734,0.603301,0.497763,0.634592,0.540214,0.417602,0.528008
5,시험강점형,0.548032,0.456409,0.364163,0.436320,0.461963,0.530427,0.378787,0.626543,0.444350,...,0.504941,0.429749,0.481060,0.559580,0.542935,0.478418,0.561216,0.636765,0.506246,0.530740
6,사교형,1.000000,1.000000,0.300000,0.300000,0.800000,0.300000,0.485682,1.000000,0.800000,...,0.504216,0.559227,0.645220,0.491734,0.579001,0.410922,0.800000,0.527222,0.800000,0.300000
7,중재자형,0.428441,0.395375,0.100000,0.100000,0.900000,0.100000,0.436349,0.515220,0.900000,...,1.000000,1.000000,0.559603,0.496836,0.427028,0.406603,0.900000,0.429963,0.900000,0.100000
8,리더형,0.900000,0.900000,0.604462,0.573328,0.800000,0.503587,0.451450,0.900000,0.800000,...,0.581294,0.513534,0.438378,0.525230,0.700000,0.700000,0.800000,0.530272,0.800000,0.551126
9,소극형,0.641080,0.499885,0.478759,0.451685,0.590063,0.627920,0.450242,0.399694,0.636821,...,0.596033,0.592367,0.640711,0.640174,0.599700,0.445493,0.370023,0.485181,0.483690,0.387989
10,고립위험형,0.200000,0.200000,0.465711,0.537452,0.383649,0.535511,0.900000,0.200000,0.581984,...,0.443379,0.405193,0.900000,0.300000,0.385076,0.406666,0.422453,0.631385,0.584012,0.572412
11,친구의존형,0.642724,0.633826,0.389378,0.538757,0.371809,0.623106,0.572450,0.489319,0.378249,...,0.451527,0.417012,0.484217,0.582870,0.584563,0.410772,0.391330,0.578217,0.579076,0.610386
12,규칙준수형,0.384663,0.566291,0.375721,0.587315,0.360659,0.417421,0.362481,0.520639,0.456105,...,0.549158,0.512199,0.534335,0.462875,0.613608,0.627945,0.506420,0.366889,0.637178,0.518906
13,자율형,0.521766,0.561510,0.440143,0.377406,0.507778,0.474804,0.547842,0.496137,0.517443,...,0.597230,0.371626,0.472576,0.504866,0.476839,0.620892,0.427654,0.567232,0.519804,0.503923
14,주의산만형,0.389762,0.589047,0.501376,0.353380,0.554981,0.432289,0.466086,0.580834,0.454344,...,0.468031,0.353414,0.443615,0.477719,0.577884,0.358885,0.417663,0.611901,0.541593,0.532862
15,충동형,0.583158,0.384843,1.000000,1.000000,0.352826,1.000000,0.639752,0.635757,0.540432,...,0.200000,0.200000,0.361143,0.547448,0.200000,0.200000,0.479449,0.544771,0.548698,1.000000
16,지각결석관리형,0.429876,0.409730,0.394169,0.598842,0.515187,0.561272,0.431586,0.586659,0.606889,...,0.392231,0.628546,0.530433,0.409573,0.356907,0.455518,0.421505,0.614646,0.527326,0.647882
17,생활모범형,0.576539,0.434786,0.569827,0.567817,0.595368,0.379151,0.520779,0.359193,0.494972,...,0.366879,0.448159,0.644085,0.508614,0.468863,0.605658,0.411328,0.570844,0.405328,0.421481
18,발표형,0.556327,0.456315,0.583278,0.524281,0.385667,0.387995,0.432095,0.611830,0.359204,...,0.405209,0.393606,0.608347,0.381349,0.622882,0.445622,0.491376,0.640528,0.579786,0.617694
19,경청형,0.441098,0.409059,0.644737,0.639658,0.620776,0.396436,0.584249,0.414080,0.602063,...,0.517271,0.389369,0.537200,0.448170,0.351421,0.352346,0.422015,0.411379,0.571266,0.636182
20,창의형,0.558604,0.629869,0.630505,0.424087,0.606775,0.550934,0.550039,0.490530,0.373642,...,0.496873,0.616226,0.356632,0.474380,0.509050,0.522105,0.402175,0.377312,0.494177,0.456414
21,실행형,0.461589,0.572335,0.423676,0.633694,0.363245,0.612857,0.566673,0.518775,0.415049,...,0.641217,0.465876,0.440284,0.473270,0.543180,0.448404,0.496588,0.627666,0.430046,0.376504
22,관망형,0.426027,0.398471,0.581738,0.539826,0.574709,0.444375,0.537308,0.408518,0.365053,...,0.640460,0.441904,0.422819,0.402678,0.552716,0.495799,0.524371,0.600471,0.486626,0.408748
23,정서민감형,0.622948,0.576532,0.635785,0.482983,0.357007,0.623980,0.452042,0.634242,0.603305,...,0.609677,0.647458,0.512809,0.437509,0.615896,0.358938,0.577817,0.494355,0.511475,0.490708
24,스트레스고위험형,0.610427,0.477281,0.459208,0.511703,0.448843,0.437988,0.375269,0.350626,0.472045,...,0.394864,0.542041,0.428852,0.640894,0.619504,0.610202,0.420259,0.390082,0.572257,0.389529
25,회복탄력형,0.490582,0.390340,0.394050,0.444403,0.398253,0.525075,0.428659,0.638807,0.370373,...,0.423332,0.409351,0.611162,0.623789,0.452855,0.422529,0.478120,0.595102,0.509442,0.497254
26,자존감저하형,0.372853,0.468274,0.473423,0.390604,0.628725,0.546525,0.453957,0.590869,0.463250,...,0.613675,0.626982,0.371224,0.582826,0.398690,0.448906,0.475692,0.520117,0.584131,0.452359
27,특수지원대상형,0.427844,0.437204,0.630157,0.634259,0.480452,0.529985,0.365468,0.561351,0.459978,...,0.491520,0.521524,0.446259,0.492567,0.391357,0.641104,0.587487,0.516959,0.511447,0.568471
28,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,0.551964,0.592027,0.634361,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
29,균형조정키형,0.376542,0.566731,0.435219,0.533959,0.444352,0.594683,0.638035,0.509550,0.549323,...,0.484602,0.592273,0.643531,0.567827,0.619324,0.466060,0.475341,0.457974,0.448934,0.519112

In [154]:
# 학생 명단과 역할별 가중치 병합
students_role_weight = pd.merge(students, role_weights, on='역할', how='left')
students_role_weight

,반,이름,역할,지각된 인기,사회적 선호,외현적 공격성,관계적 공격성,친사회성,또래 괴롭힘 가해,또래 괴롭힘 피해,...,정서적 공감,인지적 공감,내재화(우울),또래공동체 의식 (학급),행동적 수업참여,정서적 수업참여,협동적 태도,경쟁적 태도,애정,거부
0,1반,조하준,사교형,1.000000,1.000000,0.300000,0.300000,0.800000,0.300000,0.485682,...,0.504216,0.559227,0.645220,0.491734,0.579001,0.410922,0.800000,0.527222,0.800000,0.300000
1,1반,장시우,경청형,0.441098,0.409059,0.644737,0.639658,0.620776,0.396436,0.584249,...,0.517271,0.389369,0.537200,0.448170,0.351421,0.352346,0.422015,0.411379,0.571266,0.636182
2,1반,서소율,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,0.551964,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
3,1반,이연우,주의산만형,0.389762,0.589047,0.501376,0.353380,0.554981,0.432289,0.466086,...,0.468031,0.353414,0.443615,0.477719,0.577884,0.358885,0.417663,0.611901,0.541593,0.532862
4,1반,배유준,고립위험형,0.200000,0.200000,0.465711,0.537452,0.383649,0.535511,0.900000,...,0.443379,0.405193,0.900000,0.300000,0.385076,0.406666,0.422453,0.631385,0.584012,0.572412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,10반,정채은,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,0.551964,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
196,10반,한준서,집중형,0.367416,0.548041,0.617714,0.645979,0.443788,0.427854,0.548847,...,0.415659,0.424876,0.420038,0.374443,0.516689,0.513214,0.401721,0.377986,0.483729,0.589496
197,10반,한유준,균형조정키형,0.376542,0.566731,0.435219,0.533959,0.444352,0.594683,0.638035,...,0.484602,0.592273,0.643531,0.567827,0.619324,0.466060,0.475341,0.457974,0.448934,0.519112
198,10반,김우진,기초보완형,0.360677,0.589082,0.509508,0.474634,0.515946,0.599404,0.534133,...,0.369326,0.388228,0.557807,0.374734,0.603301,0.497763,0.634592,0.540214,0.417602,0.528008
199,10반,홍지안,관망형,0.426027,0.398471,0.581738,0.539826,0.574709,0.444375,0.537308,...,0.640460,0.441904,0.422819,0.402678,0.552716,0.495799,0.524371,0.600471,0.486626,0.408748

In [155]:
# 반별로 학생 번호 재부여
students_role_weight['번호'] = students_role_weight.groupby('반')['이름'].cumcount() + 1
# 번호 컬럼 앞으로 이동
cols = students_role_weight.columns.tolist()
cols.insert(1, cols.pop(cols.index('번호')))
students_role_weight = students_role_weight[cols]
students_role_weight

,반,번호,이름,역할,지각된 인기,사회적 선호,외현적 공격성,관계적 공격성,친사회성,또래 괴롭힘 가해,...,정서적 공감,인지적 공감,내재화(우울),또래공동체 의식 (학급),행동적 수업참여,정서적 수업참여,협동적 태도,경쟁적 태도,애정,거부
0,1반,1,조하준,사교형,1.000000,1.000000,0.300000,0.300000,0.800000,0.300000,...,0.504216,0.559227,0.645220,0.491734,0.579001,0.410922,0.800000,0.527222,0.800000,0.300000
1,1반,2,장시우,경청형,0.441098,0.409059,0.644737,0.639658,0.620776,0.396436,...,0.517271,0.389369,0.537200,0.448170,0.351421,0.352346,0.422015,0.411379,0.571266,0.636182
2,1반,3,서소율,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
3,1반,4,이연우,주의산만형,0.389762,0.589047,0.501376,0.353380,0.554981,0.432289,...,0.468031,0.353414,0.443615,0.477719,0.577884,0.358885,0.417663,0.611901,0.541593,0.532862
4,1반,5,배유준,고립위험형,0.200000,0.200000,0.465711,0.537452,0.383649,0.535511,...,0.443379,0.405193,0.900000,0.300000,0.385076,0.406666,0.422453,0.631385,0.584012,0.572412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,10반,16,정채은,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
196,10반,17,한준서,집중형,0.367416,0.548041,0.617714,0.645979,0.443788,0.427854,...,0.415659,0.424876,0.420038,0.374443,0.516689,0.513214,0.401721,0.377986,0.483729,0.589496
197,10반,18,한유준,균형조정키형,0.376542,0.566731,0.435219,0.533959,0.444352,0.594683,...,0.484602,0.592273,0.643531,0.567827,0.619324,0.466060,0.475341,0.457974,0.448934,0.519112
198,10반,19,김우진,기초보완형,0.360677,0.589082,0.509508,0.474634,0.515946,0.599404,...,0.369326,0.388228,0.557807,0.374734,0.603301,0.497763,0.634592,0.540214,0.417602,0.528008
199,10반,20,홍지안,관망형,0.426027,0.398471,0.581738,0.539826,0.574709,0.444375,...,0.640460,0.441904,0.422819,0.402678,0.552716,0.495799,0.524371,0.600471,0.486626,0.408748

In [156]:
# 또래지명 문항 데이터 불러오기
point_nominations = pd.read_excel('C:/Users/qndba/peer/문항 및 로직/250825_스쿨프렌즈 검사 최종 문항_저자수정요청.xlsx', sheet_name='학생문항_또래지명')
point_nominations

      구분  번호 reporting      scale reverse                                문항 내용
0    PN1   1      또래지명     지각된 인기       N                          인기가 있는 친구는?
1    PN2   2      또래지명     사회적 선호       N                        같이 놀고 싶은 친구는?
2    PN3   3      또래지명     사회적 선호       N                        같이 놀기 싫은 친구는?
3    PN4   4      또래지명    외현적 공격성       N         문제를 일으키는/학교의 규칙을 지키지 않는 친구는?
4    PN5   5      또래지명    외현적 공격성       N                          싸움을 하는 친구는?
5    PN6   6      또래지명    관계적 공격성       N          다른 친구를 나쁘게 이야기하거나 따돌리는 친구는?
6    PN7   7      또래지명    관계적 공격성       N                     나쁜 소문을 퍼뜨리는 친구는?
7    PN8   8      또래지명       친사회성       N                         평소에 친절한 친구는?
8    PN9   9      또래지명       친사회성       N              다른 친구를 잘 도와주고 어울리는 친구는?
9   PN10  10      또래지명  또래 괴롭힘 가해       N               친구를 괴롭히는 행동을 시작하는 친구는?
10  PN11  11      또래지명  또래 괴롭힘 가해       N  친구를 괴롭힐 때 다른 친구한테도 같이 괴롭히자고 하는 친구는?
11  PN12  12      또래지명  또래 괴롭힘 피해       N              다른 아이들에게 자주 놀림을 받는 친구는?
12  PN13  13      또래지명  또래 괴롭힘 피해       N             다른 아이들에게 맞거나 욕설을 듣는 친구는?
13  PN14  14      또래지명       친한친구       N                           나랑 친한 친구는?
14  PN15  15      또래지명       학습친구       N                  평소에 나랑 같이 공부하는 친구는?
15  PN16  16      또래지명    협동학습 친구       N           수업 시간에 함께 잘 도와주고 어울리는 친구는?
16  PN17  17      또래지명    선망하는 친구       N             함께 어울리거나, 친구가 되고 싶은 사람은?
17  PN18  18      또래지명       교사선호       N                      선생님과 잘 지내는 친구는?
18  PN19  19      또래지명      교사비선호       N                  선생님과 잘 지내지 못하는 친구는?

In [157]:
# point_nominations의 scale에 해당하는 시리즈를 컬럼으로 전환
# 학생 이름과 롤을 행인덱싱으로 활용
# 틀만 우선 만들고

point_question_simulation_t = students_role_weight[['반','번호','이름','역할']].copy()
for i, new_col in enumerate(point_nominations['scale']):
    point_question_simulation_t.loc[:, f'{i}_{new_col}'] = pd.NA
point_question_simulation_t.head()

,반,번호,이름,역할,0_지각된 인기,1_사회적 선호,2_사회적 선호,3_외현적 공격성,4_외현적 공격성,5_관계적 공격성,...,9_또래 괴롭힘 가해,10_또래 괴롭힘 가해,11_또래 괴롭힘 피해,12_또래 괴롭힘 피해,13_친한친구,14_학습친구,15_협동학습 친구,16_선망하는 친구,17_교사선호,18_교사비선호
0,1반,1,조하준,사교형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,1반,2,장시우,경청형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,1반,3,서소율,관계갈등핵심형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,1반,4,이연우,주의산만형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,1반,5,배유준,고립위험형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [158]:
point_question_simulation_groupby = point_question_simulation_t.groupby('반')
point_question_student_role_weight_groupby = students_role_weight.groupby('반')

In [159]:
for ban, sim_df in point_question_simulation_groupby:
    # 같은 반의 role weight dataframe 가져오기
    role_weight_df = point_question_student_role_weight_groupby.get_group(ban)

    # 여기서 sim_df, role_weight_df를 함께 사용
    print(f"=== {ban}반 ===")
    print(sim_df.shape, role_weight_df.shape)

    # 예시 처리
    # result = simulate(sim_df, role_weight_df)

=== 10반반 ===
(20, 23) (20, 29)
=== 1반반 ===
(20, 23) (20, 29)
=== 2반반 ===
(20, 23) (20, 29)
=== 3반반 ===
(20, 23) (20, 29)
=== 4반반 ===
(20, 23) (20, 29)
=== 5반반 ===
(20, 23) (20, 29)
=== 6반반 ===
(20, 23) (20, 29)
=== 7반반 ===
(20, 23) (20, 29)
=== 8반반 ===
(20, 23) (20, 29)
=== 9반반 ===
(20, 23) (20, 29)

In [160]:
import numpy as np
final_df_list = []
for class_num, sub_simulation_df in point_question_simulation_groupby:
    print(f"Processing class: {class_num}")
    students_role_weight = point_question_student_role_weight_groupby.get_group(class_num)
    
    # 지명 이름 데이터 생성
    students_name_list = list(sub_simulation_df['이름'])

    # weights_col 정재
    weights_col = point_question_simulation_t.columns[4:]
    print(weights_col)
    
    for name in students_name_list:
        students_name_list_copy = students_name_list.copy()
        print(name)
        students_name_list_copy.remove(name)  # 본인 제거
        for col in weights_col:
            # col의 숫자와 _ 제거
            col_refined = col.split('_', 1)[1]
            print(col_refined)
            weights = list(students_role_weight.loc[students_role_weight['이름'] != name, col_refined])
            n = np.random.choice([1,2,3,4,5], p=[0.3, 0.4, 0.2, 0.05, 0.05])  # 1~5명을 확률적으로 지명
            print(len(students_name_list_copy))
            print(len(np.array(weights)/sum(weights)))
            point = np.random.choice(students_name_list_copy, p=np.array(weights)/sum(weights), replace=False, size=n)
            point = ", ".join(point.tolist())
            sub_simulation_df.loc[sub_simulation_df['이름'] == name, col] = point
    final_df_list.append(sub_simulation_df)

Processing class: 10반
Index(['0_지각된 인기', '1_사회적 선호', '2_사회적 선호', '3_외현적 공격성', '4_외현적 공격성',
       '5_관계적 공격성', '6_관계적 공격성', '7_친사회성', '8_친사회성', '9_또래 괴롭힘 가해',
       '10_또래 괴롭힘 가해', '11_또래 괴롭힘 피해', '12_또래 괴롭힘 피해', '13_친한친구', '14_학습친구',
       '15_협동학습 친구', '16_선망하는 친구', '17_교사선호', '18_교사비선호'],
      dtype='object')
이소율
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
배서연
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
서이준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
김시윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강시윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
최은우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
장이준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
조은우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
이도윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
한승우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
서승우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강채은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
최현우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강가은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
장준서
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
정채은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
한준서
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
한유준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
김우진
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
홍지안
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
Processing class: 1반
Index(['0_지각된 인기', '1_사회적 선호', '2_사회적 선호', '3_외현적 공격성', '4_외현적 공격성',
       '5_관계적 공격성', '6_관계적 공격성', '7_친사회성', '8_친사회성', '9_또래 괴롭힘 가해',
       '10_또래 괴롭힘 가해', '11_또래 괴롭힘 피해', '12_또래 괴롭힘 피해', '13_친한친구', '14_학습친구',
       '15_협동학습 친구', '16_선망하는 친구', '17_교사선호', '18_교사비선호'],
      dtype='object')
조하준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
장시우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
서소율
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
이연우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
배유준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
한선우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
정소율
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
윤서윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강예린
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
박하윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
정이준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강시우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
장민서
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
임하윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강채원
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
최유나
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
오선우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
오서준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강유준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
배채은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
Processing class: 2반
Index(['0_지각된 인기', '1_사회적 선호', '2_사회적 선호', '3_외현적 공격성', '4_외현적 공격성',
       '5_관계적 공격성', '6_관계적 공격성', '7_친사회성', '8_친사회성', '9_또래 괴롭힘 가해',
       '10_또래 괴롭힘 가해', '11_또래 괴롭힘 피해', '12_또래 괴롭힘 피해', '13_친한친구', '14_학습친구',
       '15_협동학습 친구', '16_선망하는 친구', '17_교사선호', '18_교사비선호'],
      dtype='object')
박지안
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
정소율
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
장지유
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
한민서
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
최하준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
서건우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
이소율
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
배하은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
장채은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
조지호
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
장은채
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
김지안
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
정서윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
이유나
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강건우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
최다인
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
서우진
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
김다인
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
한정우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
김이준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
Processing class: 3반
Index(['0_지각된 인기', '1_사회적 선호', '2_사회적 선호', '3_외현적 공격성', '4_외현적 공격성',
       '5_관계적 공격성', '6_관계적 공격성', '7_친사회성', '8_친사회성', '9_또래 괴롭힘 가해',
       '10_또래 괴롭힘 가해', '11_또래 괴롭힘 피해', '12_또래 괴롭힘 피해', '13_친한친구', '14_학습친구',
       '15_협동학습 친구', '16_선망하는 친구', '17_교사선호', '18_교사비선호'],
      dtype='object')
서은우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
김지호
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
홍도윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
정윤서
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
강서준
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
서채은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
박하은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
김준우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
정시우
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
배준서
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
최하은
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
한다인
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 피해
19
19
또래 괴롭힘 피해
19
19
친한친구
19
19
학습친구
19
19
협동학습 친구
19
19
선망하는 친구
19
19
교사선호
19
19
교사비선호
19
19
홍서윤
지각된 인기
19
19
사회적 선호
19
19
사회적 선호
19
19
외현적 공격성
19
19
외현적 공격성
19
19
관계적 공격성
19
19
관계적 공격성
19
19
친사회성
19
19
친사회성
19
19
또래 괴롭힘 가해
19
19
또래 괴롭힘 가해
19
19

In [161]:
final_df = pd.concat(final_df_list, ignore_index=True)

In [162]:
# 시뮬레이션 결과 저장
final_df.to_excel('지명 시뮬레이션 데이터.xlsx', index=False)

# 자기보고 데이터 생성

In [244]:
# 학생 명단 불러오기
import pandas as pd
students = pd.read_excel('학생_명단_역할부여.xlsx')
# 컬럼 변경
students.rename(columns={'부여_역할': '역할'}, inplace=True)
students

       반   이름       역할
0     1반  조하준      사교형
1     1반  장시우      경청형
2     1반  서소율  관계갈등핵심형
3     1반  이연우    주의산만형
4     1반  배유준    고립위험형
..   ...  ...      ...
195  10반  정채은  관계갈등핵심형
196  10반  한준서      집중형
197  10반  한유준   균형조정키형
198  10반  김우진    기초보완형
199  10반  홍지안      관망형

[200 rows x 3 columns]

In [245]:
# 역할별 가중치 불러오기
role_weights = pd.read_excel('역할_척도_가중치_매트릭스_v2.xlsx')
# 컬럼 변경
role_weights.rename(columns={'role_name': '역할'}, inplace=True)
role_weights

,역할,지각된 인기,사회적 선호,외현적 공격성,관계적 공격성,친사회성,또래 괴롭힘 가해,또래 괴롭힘 피해,친한친구,학습친구,...,정서적 공감,인지적 공감,내재화(우울),또래공동체 의식 (학급),행동적 수업참여,정서적 수업참여,협동적 태도,경쟁적 태도,애정,거부
0,학습리더형,0.629666,0.350517,0.100000,0.100000,1.000000,0.100000,0.370144,0.564614,1.000000,...,0.800000,0.800000,0.597281,0.412492,0.900000,0.900000,1.000000,0.519230,1.000000,0.100000
1,성실과제형,0.523842,0.459291,0.613186,0.593080,0.648052,0.446633,0.375694,0.497493,0.592793,...,0.358640,0.605908,0.432174,0.577542,0.607542,0.354194,0.484445,0.628502,0.492076,0.478331
2,질문형,0.484660,0.473200,0.362590,0.559484,0.475738,0.393422,0.553183,0.626170,0.412355,...,0.451405,0.479343,0.478881,0.542011,0.506624,0.432606,0.364964,0.380376,0.545494,0.552506
3,집중형,0.367416,0.548041,0.617714,0.645979,0.443788,0.427854,0.548847,0.596732,0.382268,...,0.415659,0.424876,0.420038,0.374443,0.516689,0.513214,0.401721,0.377986,0.483729,0.589496
4,기초보완형,0.360677,0.589082,0.509508,0.474634,0.515946,0.599404,0.534133,0.458979,0.583331,...,0.369326,0.388228,0.557807,0.374734,0.603301,0.497763,0.634592,0.540214,0.417602,0.528008
5,시험강점형,0.548032,0.456409,0.364163,0.436320,0.461963,0.530427,0.378787,0.626543,0.444350,...,0.504941,0.429749,0.481060,0.559580,0.542935,0.478418,0.561216,0.636765,0.506246,0.530740
6,사교형,1.000000,1.000000,0.300000,0.300000,0.800000,0.300000,0.485682,1.000000,0.800000,...,0.504216,0.559227,0.645220,0.491734,0.579001,0.410922,0.800000,0.527222,0.800000,0.300000
7,중재자형,0.428441,0.395375,0.100000,0.100000,0.900000,0.100000,0.436349,0.515220,0.900000,...,1.000000,1.000000,0.559603,0.496836,0.427028,0.406603,0.900000,0.429963,0.900000,0.100000
8,리더형,0.900000,0.900000,0.604462,0.573328,0.800000,0.503587,0.451450,0.900000,0.800000,...,0.581294,0.513534,0.438378,0.525230,0.700000,0.700000,0.800000,0.530272,0.800000,0.551126
9,소극형,0.641080,0.499885,0.478759,0.451685,0.590063,0.627920,0.450242,0.399694,0.636821,...,0.596033,0.592367,0.640711,0.640174,0.599700,0.445493,0.370023,0.485181,0.483690,0.387989
10,고립위험형,0.200000,0.200000,0.465711,0.537452,0.383649,0.535511,0.900000,0.200000,0.581984,...,0.443379,0.405193,0.900000,0.300000,0.385076,0.406666,0.422453,0.631385,0.584012,0.572412
11,친구의존형,0.642724,0.633826,0.389378,0.538757,0.371809,0.623106,0.572450,0.489319,0.378249,...,0.451527,0.417012,0.484217,0.582870,0.584563,0.410772,0.391330,0.578217,0.579076,0.610386
12,규칙준수형,0.384663,0.566291,0.375721,0.587315,0.360659,0.417421,0.362481,0.520639,0.456105,...,0.549158,0.512199,0.534335,0.462875,0.613608,0.627945,0.506420,0.366889,0.637178,0.518906
13,자율형,0.521766,0.561510,0.440143,0.377406,0.507778,0.474804,0.547842,0.496137,0.517443,...,0.597230,0.371626,0.472576,0.504866,0.476839,0.620892,0.427654,0.567232,0.519804,0.503923
14,주의산만형,0.389762,0.589047,0.501376,0.353380,0.554981,0.432289,0.466086,0.580834,0.454344,...,0.468031,0.353414,0.443615,0.477719,0.577884,0.358885,0.417663,0.611901,0.541593,0.532862
15,충동형,0.583158,0.384843,1.000000,1.000000,0.352826,1.000000,0.639752,0.635757,0.540432,...,0.200000,0.200000,0.361143,0.547448,0.200000,0.200000,0.479449,0.544771,0.548698,1.000000
16,지각결석관리형,0.429876,0.409730,0.394169,0.598842,0.515187,0.561272,0.431586,0.586659,0.606889,...,0.392231,0.628546,0.530433,0.409573,0.356907,0.455518,0.421505,0.614646,0.527326,0.647882
17,생활모범형,0.576539,0.434786,0.569827,0.567817,0.595368,0.379151,0.520779,0.359193,0.494972,...,0.366879,0.448159,0.644085,0.508614,0.468863,0.605658,0.411328,0.570844,0.405328,0.421481
18,발표형,0.556327,0.456315,0.583278,0.524281,0.385667,0.387995,0.432095,0.611830,0.359204,...,0.405209,0.393606,0.608347,0.381349,0.622882,0.445622,0.491376,0.640528,0.579786,0.617694
19,경청형,0.441098,0.409059,0.644737,0.639658,0.620776,0.396436,0.584249,0.414080,0.602063,...,0.517271,0.389369,0.537200,0.448170,0.351421,0.352346,0.422015,0.411379,0.571266,0.636182
20,창의형,0.558604,0.629869,0.630505,0.424087,0.606775,0.550934,0.550039,0.490530,0.373642,...,0.496873,0.616226,0.356632,0.474380,0.509050,0.522105,0.402175,0.377312,0.494177,0.456414
21,실행형,0.461589,0.572335,0.423676,0.633694,0.363245,0.612857,0.566673,0.518775,0.415049,...,0.641217,0.465876,0.440284,0.473270,0.543180,0.448404,0.496588,0.627666,0.430046,0.376504
22,관망형,0.426027,0.398471,0.581738,0.539826,0.574709,0.444375,0.537308,0.408518,0.365053,...,0.640460,0.441904,0.422819,0.402678,0.552716,0.495799,0.524371,0.600471,0.486626,0.408748
23,정서민감형,0.622948,0.576532,0.635785,0.482983,0.357007,0.623980,0.452042,0.634242,0.603305,...,0.609677,0.647458,0.512809,0.437509,0.615896,0.358938,0.577817,0.494355,0.511475,0.490708
24,스트레스고위험형,0.610427,0.477281,0.459208,0.511703,0.448843,0.437988,0.375269,0.350626,0.472045,...,0.394864,0.542041,0.428852,0.640894,0.619504,0.610202,0.420259,0.390082,0.572257,0.389529
25,회복탄력형,0.490582,0.390340,0.394050,0.444403,0.398253,0.525075,0.428659,0.638807,0.370373,...,0.423332,0.409351,0.611162,0.623789,0.452855,0.422529,0.478120,0.595102,0.509442,0.497254
26,자존감저하형,0.372853,0.468274,0.473423,0.390604,0.628725,0.546525,0.453957,0.590869,0.463250,...,0.613675,0.626982,0.371224,0.582826,0.398690,0.448906,0.475692,0.520117,0.584131,0.452359
27,특수지원대상형,0.427844,0.437204,0.630157,0.634259,0.480452,0.529985,0.365468,0.561351,0.459978,...,0.491520,0.521524,0.446259,0.492567,0.391357,0.641104,0.587487,0.516959,0.511447,0.568471
28,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,0.551964,0.592027,0.634361,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
29,균형조정키형,0.376542,0.566731,0.435219,0.533959,0.444352,0.594683,0.638035,0.509550,0.549323,...,0.484602,0.592273,0.643531,0.567827,0.619324,0.466060,0.475341,0.457974,0.448934,0.519112

In [246]:
# 학생 명단과 역할별 가중치 병합
students_role_weight = pd.merge(students, role_weights, on='역할', how='left')
students_role_weight

,반,이름,역할,지각된 인기,사회적 선호,외현적 공격성,관계적 공격성,친사회성,또래 괴롭힘 가해,또래 괴롭힘 피해,...,정서적 공감,인지적 공감,내재화(우울),또래공동체 의식 (학급),행동적 수업참여,정서적 수업참여,협동적 태도,경쟁적 태도,애정,거부
0,1반,조하준,사교형,1.000000,1.000000,0.300000,0.300000,0.800000,0.300000,0.485682,...,0.504216,0.559227,0.645220,0.491734,0.579001,0.410922,0.800000,0.527222,0.800000,0.300000
1,1반,장시우,경청형,0.441098,0.409059,0.644737,0.639658,0.620776,0.396436,0.584249,...,0.517271,0.389369,0.537200,0.448170,0.351421,0.352346,0.422015,0.411379,0.571266,0.636182
2,1반,서소율,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,0.551964,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
3,1반,이연우,주의산만형,0.389762,0.589047,0.501376,0.353380,0.554981,0.432289,0.466086,...,0.468031,0.353414,0.443615,0.477719,0.577884,0.358885,0.417663,0.611901,0.541593,0.532862
4,1반,배유준,고립위험형,0.200000,0.200000,0.465711,0.537452,0.383649,0.535511,0.900000,...,0.443379,0.405193,0.900000,0.300000,0.385076,0.406666,0.422453,0.631385,0.584012,0.572412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,10반,정채은,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,0.551964,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
196,10반,한준서,집중형,0.367416,0.548041,0.617714,0.645979,0.443788,0.427854,0.548847,...,0.415659,0.424876,0.420038,0.374443,0.516689,0.513214,0.401721,0.377986,0.483729,0.589496
197,10반,한유준,균형조정키형,0.376542,0.566731,0.435219,0.533959,0.444352,0.594683,0.638035,...,0.484602,0.592273,0.643531,0.567827,0.619324,0.466060,0.475341,0.457974,0.448934,0.519112
198,10반,김우진,기초보완형,0.360677,0.589082,0.509508,0.474634,0.515946,0.599404,0.534133,...,0.369326,0.388228,0.557807,0.374734,0.603301,0.497763,0.634592,0.540214,0.417602,0.528008
199,10반,홍지안,관망형,0.426027,0.398471,0.581738,0.539826,0.574709,0.444375,0.537308,...,0.640460,0.441904,0.422819,0.402678,0.552716,0.495799,0.524371,0.600471,0.486626,0.408748

In [247]:
# 반별로 학생 번호 재부여
students_role_weight['번호'] = students_role_weight.groupby('반')['이름'].cumcount() + 1
# 번호 컬럼 앞으로 이동
cols = students_role_weight.columns.tolist()
cols.insert(1, cols.pop(cols.index('번호')))
students_role_weight = students_role_weight[cols]
students_role_weight

,반,번호,이름,역할,지각된 인기,사회적 선호,외현적 공격성,관계적 공격성,친사회성,또래 괴롭힘 가해,...,정서적 공감,인지적 공감,내재화(우울),또래공동체 의식 (학급),행동적 수업참여,정서적 수업참여,협동적 태도,경쟁적 태도,애정,거부
0,1반,1,조하준,사교형,1.000000,1.000000,0.300000,0.300000,0.800000,0.300000,...,0.504216,0.559227,0.645220,0.491734,0.579001,0.410922,0.800000,0.527222,0.800000,0.300000
1,1반,2,장시우,경청형,0.441098,0.409059,0.644737,0.639658,0.620776,0.396436,...,0.517271,0.389369,0.537200,0.448170,0.351421,0.352346,0.422015,0.411379,0.571266,0.636182
2,1반,3,서소율,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
3,1반,4,이연우,주의산만형,0.389762,0.589047,0.501376,0.353380,0.554981,0.432289,...,0.468031,0.353414,0.443615,0.477719,0.577884,0.358885,0.417663,0.611901,0.541593,0.532862
4,1반,5,배유준,고립위험형,0.200000,0.200000,0.465711,0.537452,0.383649,0.535511,...,0.443379,0.405193,0.900000,0.300000,0.385076,0.406666,0.422453,0.631385,0.584012,0.572412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,10반,16,정채은,관계갈등핵심형,0.512129,0.361017,0.534207,0.386429,0.528242,0.602851,...,0.422072,0.450157,0.569695,0.377966,0.429352,0.610135,0.445684,0.516832,0.380580,0.424960
196,10반,17,한준서,집중형,0.367416,0.548041,0.617714,0.645979,0.443788,0.427854,...,0.415659,0.424876,0.420038,0.374443,0.516689,0.513214,0.401721,0.377986,0.483729,0.589496
197,10반,18,한유준,균형조정키형,0.376542,0.566731,0.435219,0.533959,0.444352,0.594683,...,0.484602,0.592273,0.643531,0.567827,0.619324,0.466060,0.475341,0.457974,0.448934,0.519112
198,10반,19,김우진,기초보완형,0.360677,0.589082,0.509508,0.474634,0.515946,0.599404,...,0.369326,0.388228,0.557807,0.374734,0.603301,0.497763,0.634592,0.540214,0.417602,0.528008
199,10반,20,홍지안,관망형,0.426027,0.398471,0.581738,0.539826,0.574709,0.444375,...,0.640460,0.441904,0.422819,0.402678,0.552716,0.495799,0.524371,0.600471,0.486626,0.408748

In [248]:
# 자기보고 문항 데이터 불러오기
self_report_question_info = pd.read_excel('C:/Users/qndba/peer/문항 및 로직/250825_스쿨프렌즈 검사 최종 문항_저자수정요청.xlsx', sheet_name='학생문항_자기보고')
self_report_question_info

,구분,번호,reporting,scale,reverse,문항 내용
0,SR1,1,학생보고(5점 리커트),사회적 발달 목표,N,나는 친구들과 더 잘 지내는 방법을 알게 될 때 기쁘다.
1,SR2,2,학생보고(5점 리커트),사회적 발달 목표,N,나는 친구들을 더 잘 이해하게 되는 것이 좋다.
2,SR3,3,학생보고(5점 리커트),사회적 발달 목표,N,나는 다른 친구에 대해 더 잘 알아 가는 것이 좋다.
3,SR4,4,학생보고(5점 리커트),사회적 과시목표,N,나는 인기 있는 아이들과 친구가 되고 싶다.
4,SR5,5,학생보고(5점 리커트),사회적 과시목표,N,‘잘 나가는’ 아이들과 친구가 되는 것은 중요하다.
...,...,...,...,...,...,...
70,SR72,71,학생보고(5점 리커트),거부,N,부모님은 내가 잘못하면 바로 혼내신다.
71,SR72,72,학생보고(5점 리커트),거부,N,부모님은 내가 신경 쓰이게 만든다고 말씀하실 때가 있다.
72,SR73,73,학생보고(5점 리커트),거부,N,부모님은 내 기분을 상하게 하실 때가 있다.
73,SR74,74,학생보고(5점 리커트),거부,N,"내가 잘못했을 때, 부모님이 소리를 지르거나 무섭게 대하실 때가 있다."
74,SR75,75,학생보고(5점 리커트),거부,N,부모님은 화가 나시면 나를 크게 혼내실 때가 있다.

In [249]:
# self_report_question_info의 scale에 해당하는 시리즈를 컬럼으로 전환
# 학생 이름과 롤을 행인덱싱으로 활용
# 틀만 우선 만들고
self_report_question_simulation_t = students_role_weight[['반', '번호','이름','역할']].copy()
for index, new_col in enumerate(self_report_question_info['scale']):
    self_report_question_simulation_t.loc[:, f'{index}_{new_col}'] = pd.NA
self_report_question_simulation_t

,반,번호,이름,역할,0_사회적 발달 목표,1_사회적 발달 목표,2_사회적 발달 목표,3_사회적 과시목표,4_사회적 과시목표,5_사회적 과시목표,...,65_애정,66_애정,67_애정,68_거부,69_거부,70_거부,71_거부,72_거부,73_거부,74_거부
0,1반,1,조하준,사교형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,1반,2,장시우,경청형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,1반,3,서소율,관계갈등핵심형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,1반,4,이연우,주의산만형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,1반,5,배유준,고립위험형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,10반,16,정채은,관계갈등핵심형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
196,10반,17,한준서,집중형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
197,10반,18,한유준,균형조정키형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
198,10반,19,김우진,기초보완형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
199,10반,20,홍지안,관망형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [250]:
self_report_question_simulation_t_groupby = self_report_question_simulation_t.groupby('반')
self_report_question_student_role_weight_groupby = students_role_weight.groupby('반')

In [251]:
weights_col = self_report_question_simulation_t.columns[4:]
print(weights_col)

Index(['0_사회적 발달 목표', '1_사회적 발달 목표', '2_사회적 발달 목표', '3_사회적 과시목표', '4_사회적 과시목표',
       '5_사회적 과시목표', '6_정서적 공감', '7_정서적 공감', '8_정서적 공감', '9_정서적 공감',
       '10_정서적 공감', '11_정서적 공감', '12_정서적 공감', '13_인지적 공감', '14_인지적 공감',
       '15_인지적 공감', '16_인지적 공감', '17_인지적 공감', '18_인지적 공감', '19_인지적 공감',
       '20_내재화(우울)', '21_내재화(우울)', '22_내재화(우울)', '23_내재화(우울)', '24_내재화(우울)',
       '25_내재화(우울)', '26_내재화(우울)', '27_내재화(우울)', '28_내재화(우울)', '29_내재화(우울)',
       '30_또래공동체 의식 (학급)', '31_또래공동체 의식 (학급)', '32_또래공동체 의식 (학급)',
       '33_또래공동체 의식 (학급)', '34_행동적 수업참여', '35_행동적 수업참여', '36_행동적 수업참여',
       '37_행동적 수업참여', '38_행동적 수업참여', '39_정서적 수업참여', '40_정서적 수업참여',
       '41_정서적 수업참여', '42_정서적 수업참여', '43_정서적 수업참여', '44_협동적 태도', '45_협동적 태도',
       '46_협동적 태도', '47_협동적 태도', '48_협동적 태도', '49_협동적 태도', '50_협동적 태도',
       '51_경쟁적 태도', '52_경쟁적 태도', '53_경쟁적 태도', '54_경쟁적 태도', '55_경쟁적 태도',
       '56_경쟁적 태도', '57_경쟁적 태도', '58_경쟁적 태도', '59_애정', '60_애정', '61_애정',
       '62_애정', '63_애정', '64_애정', '65_애정', '66_애정', '67_애정', '68_거부', '69_거부',
       '70_거부', '71_거부', '72_거부', '73_거부', '74_거부'],
      dtype='object')

In [252]:
students_role_weight.columns

Index(['반', '번호', '이름', '역할', '지각된 인기', '사회적 선호', '외현적 공격성', '관계적 공격성', '친사회성',
       '또래 괴롭힘 가해', '또래 괴롭힘 피해', '친한친구', '학습친구', '협동학습 친구', '선망하는 친구', '교사선호',
       '교사비선호', '사회적 발달 목표', '사회적 과시목표', '정서적 공감', '인지적 공감', '내재화(우울)',
       '또래공동체 의식 (학급)', '행동적 수업참여', '정서적 수업참여', '협동적 태도', '경쟁적 태도', '애정',
       '거부'],
      dtype='object')

In [253]:
weight_low_self_prob = [0.4, 0.3, 0.2, 0.05, 0.05]
weight_mid_self_prob = [0.1, 0.2, 0.4, 0.2, 0.1]
weight_high_self_prob = [0.05, 0.05, 0.2, 0.3, 0.4]

In [254]:
final_df_list = []
for class_num, sub_simulation_df in point_question_simulation_groupby:
    print(f"Processing class: {class_num}")
    students_role_weight = point_question_student_role_weight_groupby.get_group(class_num)
    # 지명 이름 데이터 생성
    students_name_list = list(sub_simulation_df['이름'])

    for name in students_name_list:
        print(name)
        for col in weights_col:
            # col의 숫자와 _ 제거
            col_refined = col.split('_', 1)[1]
            weight = students_role_weight.loc[students_role_weight['이름'] == name, col_refined].values[0]
            print(col_refined, weight)
            if weight == 5.0:
                score_prob = weight_high_self_prob
            elif weight == 0.6:
                score_prob = weight_mid_self_prob
            else:
                score_prob = weight_low_self_prob
            base_scores = np.array([1, 2, 3, 4, 5])
            score = np.random.choice(base_scores, p=score_prob)
            sub_simulation_df.loc[sub_simulation_df['이름'] == name, col] = score
    final_df_list.append(sub_simulation_df)

Processing class: 10반
이소율
사회적 발달 목표 0.6260279757772655
사회적 발달 목표 0.6260279757772655
사회적 발달 목표 0.6260279757772655
사회적 과시목표 0.488596793503975
사회적 과시목표 0.488596793503975
사회적 과시목표 0.488596793503975
정서적 공감 0.6404602588744386
정서적 공감 0.6404602588744386
정서적 공감 0.6404602588744386
정서적 공감 0.6404602588744386
정서적 공감 0.6404602588744386
정서적 공감 0.6404602588744386
정서적 공감 0.6404602588744386
인지적 공감 0.4419041385241494
인지적 공감 0.4419041385241494
인지적 공감 0.4419041385241494
인지적 공감 0.4419041385241494
인지적 공감 0.4419041385241494
인지적 공감 0.4419041385241494
인지적 공감 0.4419041385241494
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
내재화(우울) 0.4228185530542429
또래공동체 의식 (학급) 0.4026778628385563
또래공동체 의식 (학급) 0.4026778628385563
또래공동체 의식 (학급) 0.4026778628385563
또래공동체 의식 (학급) 0.4026778628385563
행동적 수업참여 0.5527163124505743
행동적 수업참여 0.5527163124505743
행동적 수업참여 0.5527163124505743
행동적 수업참여 0.5527163124505743
행동적 수업참여 0.5527163124505743
정서적 수업참여 0.4957991757280621
정서적 수업참여 0.4957991757280621
정서적 수업참여 0.4957991757280621
정서적 수업참여 0.4957991757280621
정서적 수업참여 0.4957991757280621
협동적 태도 0.5243711029636497
협동적 태도 0.5243711029636497
협동적 태도 0.5243711029636497
협동적 태도 0.5243711029636497
협동적 태도 0.5243711029636497
협동적 태도 0.5243711029636497
협동적 태도 0.5243711029636497
경쟁적 태도 0.6004712161363505
경쟁적 태도 0.6004712161363505
경쟁적 태도 0.6004712161363505
경쟁적 태도 0.6004712161363505
경쟁적 태도 0.6004712161363505
경쟁적 태도 0.6004712161363505
경쟁적 태도 0.6004712161363505
경쟁적 태도 0.6004712161363505
애정 0.4866258421383955
애정 0.4866258421383955
애정 0.4866258421383955
애정 0.4866258421383955
애정 0.4866258421383955
애정 0.4866258421383955
애정 0.4866258421383955
애정 0.4866258421383955
애정 0.4866258421383955
거부 0.4087482732031569
거부 0.4087482732031569
거부 0.4087482732031569
거부 0.4087482732031569
거부 0.4087482732031569
거부 0.4087482732031569
거부 0.4087482732031569
배서연
사회적 발달 목표 0.4672119959923254
사회적 발달 목표 0.4672119959923254
사회적 발달 목표 0.4672119959923254
사회적 과시목표 0.5262799982116456
사회적 과시목표 0.5262799982116456
사회적 과시목표 0.5262799982116456
정서적 공감 0.5972304591476675
정서적 공감 0.5972304591476675
정서적 공감 0.5972304591476675
정서적 공감 0.5972304591476675
정서적 공감 0.5972304591476675
정서적 공감 0.5972304591476675
정서적 공감 0.5972304591476675
인지적 공감 0.3716260605778623
인지적 공감 0.3716260605778623
인지적 공감 0.3716260605778623
인지적 공감 0.3716260605778623
인지적 공감 0.3716260605778623
인지적 공감 0.3716260605778623
인지적 공감 0.3716260605778623
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
내재화(우울) 0.4725763333743815
또래공동체 의식 (학급) 0.5048661800116858
또래공동체 의식 (학급) 0.5048661800116858
또래공동체 의식 (학급) 0.5048661800116858
또래공동체 의식 (학급) 0.5048661800116858
행동적 수업참여 0.4768389205374431
행동적 수업참여 0.4768389205374431
행동적 수업참여 0.4768389205374431
행동적 수업참여 0.4768389205374431
행동적 수업참여 0.4768389205374431
정서적 수업참여 0.6208919552114411
정서적 수업참여 0.6208919552114411
정서적 수업참여 0.6208919552114411
정서적 수업참여 0.6208919552114411
정서적 수업참여 0.6208919552114411
협동적 태도 0.4276543392729025
협동적 태도 0.4276543392729025
협동적 태도 0.4276543392729025
협동적 태도 0.4276543392729025
협동적 태도 0.4276543392729025
협동적 태도 0.4276543392729025
협동적 태도 0.4276543392729025
경쟁적 태도 0.56723235184909
경쟁적 태도 0.56723235184909
경쟁적 태도 0.56723235184909
경쟁적 태도 0.56723235184909
경쟁적 태도 0.56723235184909
경쟁적 태도 0.56723235184909
경쟁적 태도 0.56723235184909
경쟁적 태도 0.56723235184909
애정 0.5198041648707145
애정 0.5198041648707145
애정 0.5198041648707145
애정 0.5198041648707145
애정 0.5198041648707145
애정 0.5198041648707145
애정 0.5198041648707145
애정 0.5198041648707145
애정 0.5198041648707145
거부 0.5039225426343175
거부 0.5039225426343175
거부 0.5039225426343175
거부 0.5039225426343175
거부 0.5039225426343175
거부 0.5039225426343175
거부 0.5039225426343175
서이준
사회적 발달 목표 0.5026028093598158
사회적 발달 목표 0.5026028093598158
사회적 발달 목표 0.5026028093598158
사회적 과시목표 0.5441360218346438
사회적 과시목표 0.5441360218346438
사회적 과시목표 0.5441360218346438
정서적 공감 0.5042156597044465
정서적 공감 0.5042156597044465
정서적 공감 0.5042156597044465
정서적 공감 0.5042156597044465
정서적 공감 0.5042156597044465
정서적 공감 0.5042156597044465
정서적 공감 0.5042156597044465
인지적 공감 0.5592271204688773
인지적 공감 0.5592271204688773
인지적 공감 0.5592271204688773
인지적 공감 0.5592271204688773
인지적 공감 0.5592271204688773
인지적 공감 0.5592271204688773
인지적 공감 0.5592271204688773
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
내재화(우울) 0.6452202546853272
또래공동체 의식 (학급) 0.4917341636002177
또래공동체 의식 (학급) 0.4917341636002177
또래공동체 의식 (학급) 0.4917341636002177
또래공동체 의식 (학급) 0.4917341636002177
행동적 수업참여 0.5790010459977728
행동적 수업참여 0.5790010459977728
행동적 수업참여 0.5790010459977728
행동적 수업참여 0.5790010459977728
행동적 수업참여 0.5790010459977728
정서적 수업참여 0.410922453538289
정서적 수업참여 0.410922453538289
정서적 수업참여 0.410922453538289
정서적 수업참여 0.410922453538289
정서적 수업참여 0.410922453538289
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
경쟁적 태도 0.5272219151795788
경쟁적 태도 0.5272219151795788
경쟁적 태도 0.5272219151795788
경쟁적 태도 0.5272219151795788
경쟁적 태도 0.5272219151795788
경쟁적 태도 0.5272219151795788
경쟁적 태도 0.5272219151795788
경쟁적 태도 0.5272219151795788
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
거부 0.3
거부 0.3
거부 0.3
거부 0.3
거부 0.3
거부 0.3
거부 0.3
김시윤
사회적 발달 목표 0.6279272657171671
사회적 발달 목표 0.6279272657171671
사회적 발달 목표 0.6279272657171671
사회적 과시목표 0.6113268866470334
사회적 과시목표 0.6113268866470334
사회적 과시목표 0.6113268866470334
정서적 공감 0.6136748691467506
정서적 공감 0.6136748691467506
정서적 공감 0.6136748691467506
정서적 공감 0.6136748691467506
정서적 공감 0.6136748691467506
정서적 공감 0.6136748691467506
정서적 공감 0.6136748691467506
인지적 공감 0.6269823004296153
인지적 공감 0.6269823004296153
인지적 공감 0.6269823004296153
인지적 공감 0.6269823004296153
인지적 공감 0.6269823004296153
인지적 공감 0.6269823004296153
인지적 공감 0.6269823004296153
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
내재화(우울) 0.3712242770360746
또래공동체 의식 (학급) 0.5828263765015311
또래공동체 의식 (학급) 0.5828263765015311
또래공동체 의식 (학급) 0.5828263765015311
또래공동체 의식 (학급) 0.5828263765015311
행동적 수업참여 0.3986898803647156
행동적 수업참여 0.3986898803647156
행동적 수업참여 0.3986898803647156
행동적 수업참여 0.3986898803647156
행동적 수업참여 0.3986898803647156
정서적 수업참여 0.4489057073811947
정서적 수업참여 0.4489057073811947
정서적 수업참여 0.4489057073811947
정서적 수업참여 0.4489057073811947
정서적 수업참여 0.4489057073811947
협동적 태도 0.4756920397090798
협동적 태도 0.4756920397090798
협동적 태도 0.4756920397090798
협동적 태도 0.4756920397090798
협동적 태도 0.4756920397090798
협동적 태도 0.4756920397090798
협동적 태도 0.4756920397090798
경쟁적 태도 0.5201174299580602
경쟁적 태도 0.5201174299580602
경쟁적 태도 0.5201174299580602
경쟁적 태도 0.5201174299580602
경쟁적 태도 0.5201174299580602
경쟁적 태도 0.5201174299580602
경쟁적 태도 0.5201174299580602
경쟁적 태도 0.5201174299580602
애정 0.5841306849694324
애정 0.5841306849694324
애정 0.5841306849694324
애정 0.5841306849694324
애정 0.5841306849694324
애정 0.5841306849694324
애정 0.5841306849694324
애정 0.5841306849694324
애정 0.5841306849694324
거부 0.4523594590099234
거부 0.4523594590099234
거부 0.4523594590099234
거부 0.4523594590099234
거부 0.4523594590099234
거부 0.4523594590099234
거부 0.4523594590099234
강시윤
사회적 발달 목표 0.5669274938137234
사회적 발달 목표 0.5669274938137234
사회적 발달 목표 0.5669274938137234
사회적 과시목표 0.546771101870437
사회적 과시목표 0.546771101870437
사회적 과시목표 0.546771101870437
정서적 공감 0.5812939471933776
정서적 공감 0.5812939471933776
정서적 공감 0.5812939471933776
정서적 공감 0.5812939471933776
정서적 공감 0.5812939471933776
정서적 공감 0.5812939471933776
정서적 공감 0.5812939471933776
인지적 공감 0.5135342682983047
인지적 공감 0.5135342682983047
인지적 공감 0.5135342682983047
인지적 공감 0.5135342682983047
인지적 공감 0.5135342682983047
인지적 공감 0.5135342682983047
인지적 공감 0.5135342682983047
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
내재화(우울) 0.4383784226585377
또래공동체 의식 (학급) 0.5252298281592812
또래공동체 의식 (학급) 0.5252298281592812
또래공동체 의식 (학급) 0.5252298281592812
또래공동체 의식 (학급) 0.5252298281592812
행동적 수업참여 0.7
행동적 수업참여 0.7
행동적 수업참여 0.7
행동적 수업참여 0.7
행동적 수업참여 0.7
정서적 수업참여 0.7
정서적 수업참여 0.7
정서적 수업참여 0.7
정서적 수업참여 0.7
정서적 수업참여 0.7
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
협동적 태도 0.8
경쟁적 태도 0.5302718218710742
경쟁적 태도 0.5302718218710742
경쟁적 태도 0.5302718218710742
경쟁적 태도 0.5302718218710742
경쟁적 태도 0.5302718218710742
경쟁적 태도 0.5302718218710742
경쟁적 태도 0.5302718218710742
경쟁적 태도 0.5302718218710742
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
애정 0.8
거부 0.5511258974375688
거부 0.5511258974375688
거부 0.5511258974375688
거부 0.5511258974375688
거부 0.5511258974375688
거부 0.5511258974375688
거부 0.5511258974375688
최은우
사회적 발달 목표 0.5086668373429682
사회적 발달 목표 0.5086668373429682
사회적 발달 목표 0.5086668373429682
사회적 과시목표 0.3645311104858437
사회적 과시목표 0.3645311104858437
사회적 과시목표 0.3645311104858437
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
또래공동체 의식 (학급) 0.4777193656628248
또래공동체 의식 (학급) 0.4777193656628248
또래공동체 의식 (학급) 0.4777193656628248
또래공동체 의식 (학급) 0.4777193656628248
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
장이준
사회적 발달 목표 0.5086668373429682
사회적 발달 목표 0.5086668373429682
사회적 발달 목표 0.5086668373429682
사회적 과시목표 0.3645311104858437
사회적 과시목표 0.3645311104858437
사회적 과시목표 0.3645311104858437
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
정서적 공감 0.4680306018577103
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
인지적 공감 0.3534142103092134
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
내재화(우울) 0.4436154055091738
또래공동체 의식 (학급) 0.4777193656628248
또래공동체 의식 (학급) 0.4777193656628248
또래공동체 의식 (학급) 0.4777193656628248
또래공동체 의식 (학급) 0.4777193656628248
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
행동적 수업참여 0.5778844778735742
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
정서적 수업참여 0.3588848657408024
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
협동적 태도 0.4176626078361738
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
경쟁적 태도 0.6119008085666527
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
애정 0.5415934222802916
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
거부 0.5328622146117086
조은우
사회적 발달 목표 0.4904624813110864
사회적 발달 목표 0.4904624813110864
사회적 발달 목표 0.4904624813110864
사회적 과시목표 0.5090876195731949
사회적 과시목표 0.5090876195731949
사회적 과시목표 0.5090876195731949
정서적 공감 0.4233319900484065
정서적 공감 0.4233319900484065
정서적 공감 0.4233319900484065
정서적 공감 0.4233319900484065
정서적 공감 0.4233319900484065
정서적 공감 0.4233319900484065
정서적 공감 0.4233319900484065
인지적 공감 0.4093512103465646
인지적 공감 0.4093512103465646
인지적 공감 0.4093512103465646
인지적 공감 0.4093512103465646
인지적 공감 0.4093512103465646
인지적 공감 0.4093512103465646
인지적 공감 0.4093512103465646
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
내재화(우울) 0.6111621017824864
또래공동체 의식 (학급) 0.6237886631435078
또래공동체 의식 (학급) 0.6237886631435078
또래공동체 의식 (학급) 0.6237886631435078
또래공동체 의식 (학급) 0.6237886631435078
행동적 수업참여 0.4528549680797928
행동적 수업참여 0.4528549680797928
행동적 수업참여 0.4528549680797928
행동적 수업참여 0.4528549680797928
행동적 수업참여 0.4528549680797928
정서적 수업참여 0.4225292562195923
정서적 수업참여 0.4225292562195923
정서적 수업참여 0.4225292562195923
정서적 수업참여 0.4225292562195923
정서적 수업참여 0.4225292562195923
협동적 태도 0.4781200678984211
협동적 태도 0.4781200678984211
협동적 태도 0.4781200678984211
협동적 태도 0.4781200678984211
협동적 태도 0.4781200678984211
협동적 태도 0.4781200678984211
협동적 태도 0.4781200678984211
경쟁적 태도 0.5951019731506563
경쟁적 태도 0.5951019731506563
경쟁적 태도 0.5951019731506563
경쟁적 태도 0.5951019731506563
경쟁적 태도 0.5951019731506563
경쟁적 태도 0.5951019731506563
경쟁적 태도 0.5951019731506563
경쟁적 태도 0.5951019731506563
애정 0.5094418745284118
애정 0.5094418745284118
애정 0.5094418745284118
애정 0.5094418745284118
애정 0.5094418745284118
애정 0.5094418745284118
애정 0.5094418745284118
애정 0.5094418745284118
애정 0.5094418745284118
거부 0.4972540773717362
거부 0.4972540773717362
거부 0.4972540773717362
거부 0.4972540773717362
거부 0.4972540773717362
거부 0.4972540773717362
거부 0.4972540773717362
이도윤
사회적 발달 목표 0.6445603377703695
사회적 발달 목표 0.6445603377703695
사회적 발달 목표 0.6445603377703695
사회적 과시목표 0.3716570248969963
사회적 과시목표 0.3716570248969963
사회적 과시목표 0.3716570248969963
정서적 공감 0.5960333728261169
정서적 공감 0.5960333728261169
정서적 공감 0.5960333728261169
정서적 공감 0.5960333728261169
정서적 공감 0.5960333728261169
정서적 공감 0.5960333728261169
정서적 공감 0.5960333728261169
인지적 공감 0.5923671514532247
인지적 공감 0.5923671514532247
인지적 공감 0.5923671514532247
인지적 공감 0.5923671514532247
인지적 공감 0.5923671514532247
인지적 공감 0.5923671514532247
인지적 공감 0.5923671514532247
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
내재화(우울) 0.6407112099560713
또래공동체 의식 (학급) 0.6401738922472339
또래공동체 의식 (학급) 0.6401738922472339
또래공동체 의식 (학급) 0.6401738922472339
또래공동체 의식 (학급) 0.6401738922472339
행동적 수업참여 0.5996998406272102
행동적 수업참여 0.5996998406272102
행동적 수업참여 0.5996998406272102
행동적 수업참여 0.5996998406272102
행동적 수업참여 0.5996998406272102
정서적 수업참여 0.445492918333187
정서적 수업참여 0.445492918333187
정서적 수업참여 0.445492918333187
정서적 수업참여 0.445492918333187
정서적 수업참여 0.445492918333187
협동적 태도 0.370023073863891
협동적 태도 0.370023073863891
협동적 태도 0.370023073863891
협동적 태도 0.370023073863891
협동적 태도 0.370023073863891
협동적 태도 0.370023073863891
협동적 태도 0.370023073863891
경쟁적 태도 0.4851811722796068
경쟁적 태도 0.4851811722796068
경쟁적 태도 0.4851811722796068
경쟁적 태도 0.4851811722796068
경쟁적 태도 0.4851811722796068
경쟁적 태도 0.4851811722796068
경쟁적 태도 0.4851811722796068
경쟁적 태도 0.4851811722796068
애정 0.4836898026476616
애정 0.4836898026476616
애정 0.4836898026476616
애정 0.4836898026476616
애정 0.4836898026476616
애정 0.4836898026476616
애정 0.4836898026476616
애정 0.4836898026476616
애정 0.4836898026476616
거부 0.3879893025352484
거부 0.3879893025352484
거부 0.3879893025352484
거부 0.3879893025352484
거부 0.3879893025352484
거부 0.3879893025352484
거부 0.3879893025352484
한승우
사회적 발달 목표 0.6029642256902774
사회적 발달 목표 0.6029642256902774
사회적 발달 목표 0.6029642256902774
사회적 과시목표 0.4711247971690922
사회적 과시목표 0.4711247971690922
사회적 과시목표 0.4711247971690922
정서적 공감 0.4915201371237278
정서적 공감 0.4915201371237278
정서적 공감 0.4915201371237278
정서적 공감 0.4915201371237278
정서적 공감 0.4915201371237278
정서적 공감 0.4915201371237278
정서적 공감 0.4915201371237278
인지적 공감 0.5215244076224225
인지적 공감 0.5215244076224225
인지적 공감 0.5215244076224225
인지적 공감 0.5215244076224225
인지적 공감 0.5215244076224225
인지적 공감 0.5215244076224225
인지적 공감 0.5215244076224225
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
내재화(우울) 0.4462585721891499
또래공동체 의식 (학급) 0.4925669032355077
또래공동체 의식 (학급) 0.4925669032355077
또래공동체 의식 (학급) 0.4925669032355077
또래공동체 의식 (학급) 0.4925669032355077
행동적 수업참여 0.3913568021251821
행동적 수업참여 0.3913568021251821
행동적 수업참여 0.3913568021251821
행동적 수업참여 0.3913568021251821
행동적 수업참여 0.3913568021251821
정서적 수업참여 0.6411038254515448
정서적 수업참여 0.6411038254515448
정서적 수업참여 0.6411038254515448
정서적 수업참여 0.6411038254515448
정서적 수업참여 0.6411038254515448
협동적 태도 0.5874868780598901
협동적 태도 0.5874868780598901
협동적 태도 0.5874868780598901
협동적 태도 0.5874868780598901
협동적 태도 0.5874868780598901
협동적 태도 0.5874868780598901
협동적 태도 0.5874868780598901
경쟁적 태도 0.5169588188405658
경쟁적 태도 0.5169588188405658
경쟁적 태도 0.5169588188405658
경쟁적 태도 0.5169588188405658
경쟁적 태도 0.5169588188405658
경쟁적 태도 0.5169588188405658
경쟁적 태도 0.5169588188405658
경쟁적 태도 0.5169588188405658
애정 0.5114466421900005
애정 0.5114466421900005
애정 0.5114466421900005
애정 0.5114466421900005
애정 0.5114466421900005
애정 0.5114466421900005
애정 0.5114466421900005
애정 0.5114466421900005
애정 0.5114466421900005
거부 0.5684710709785857
거부 0.5684710709785857
거부 0.5684710709785857
거부 0.5684710709785857
거부 0.5684710709785857
거부 0.5684710709785857
거부 0.5684710709785857
서승우
사회적 발달 목표 0.5857895352148276
사회적 발달 목표 0.5857895352148276
사회적 발달 목표 0.5857895352148276
사회적 과시목표 0.4515974384159817
사회적 과시목표 0.4515974384159817
사회적 과시목표 0.4515974384159817
정서적 공감 0.5491579670748945
정서적 공감 0.5491579670748945
정서적 공감 0.5491579670748945
정서적 공감 0.5491579670748945
정서적 공감 0.5491579670748945
정서적 공감 0.5491579670748945
정서적 공감 0.5491579670748945
인지적 공감 0.512198739460259
인지적 공감 0.512198739460259
인지적 공감 0.512198739460259
인지적 공감 0.512198739460259
인지적 공감 0.512198739460259
인지적 공감 0.512198739460259
인지적 공감 0.512198739460259
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
내재화(우울) 0.5343350122909102
또래공동체 의식 (학급) 0.4628747940171972
또래공동체 의식 (학급) 0.4628747940171972
또래공동체 의식 (학급) 0.4628747940171972
또래공동체 의식 (학급) 0.4628747940171972
행동적 수업참여 0.6136083387448743
행동적 수업참여 0.6136083387448743
행동적 수업참여 0.6136083387448743
행동적 수업참여 0.6136083387448743
행동적 수업참여 0.6136083387448743
정서적 수업참여 0.6279446431513855

In [255]:
sub_simulation_df

,반,번호,이름,역할,0_지각된 인기,1_사회적 선호,2_사회적 선호,3_외현적 공격성,4_외현적 공격성,5_관계적 공격성,...,65_애정,66_애정,67_애정,68_거부,69_거부,70_거부,71_거부,72_거부,73_거부,74_거부
160,9반,1,오민서,관망형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,1.0,5.0,1.0,5.0,2.0,5.0,3.0,2.0,2.0
161,9반,2,한은우,관망형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,4.0,5.0,2.0,1.0,2.0,2.0,3.0,3.0,4.0,1.0
162,9반,3,서예은,균형조정키형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,1.0,1.0,3.0,2.0,1.0,3.0,2.0,2.0,1.0
163,9반,4,임채원,정서민감형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,3.0,5.0,2.0,5.0,1.0,2.0,1.0,1.0,2.0
164,9반,5,장준우,기초보완형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,1.0,3.0
165,9반,6,임예은,질문형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,4.0,1.0
166,9반,7,이이준,친구의존형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,1.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,1.0
167,9반,8,정다인,중재자형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,3.0,2.0,3.0,3.0,1.0,2.0,4.0,1.0,3.0
168,9반,9,김연우,실행형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,3.0,1.0,2.0,3.0,2.0,1.0,3.0,1.0,2.0
169,9반,10,장수빈,자존감저하형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,5.0,1.0,2.0,3.0,1.0,1.0,2.0,2.0,1.0
170,9반,11,서하윤,질문형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,3.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0
171,9반,12,이지유,학습리더형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,2.0,1.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0
172,9반,13,김선우,질문형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,1.0,3.0,1.0,1.0,4.0,1.0,1.0,1.0,2.0
173,9반,14,강소율,기초보완형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,4.0,4.0,2.0,1.0,5.0,2.0,1.0,1.0,3.0
174,9반,15,김도현,주의산만형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,5.0,1.0,5.0,1.0,3.0,2.0,3.0,3.0,1.0
175,9반,16,이하은,자율형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,3.0,1.0,5.0,3.0,1.0,3.0,3.0,1.0,1.0,1.0
176,9반,17,배이준,질문형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,2.0,2.0,1.0,1.0,2.0,1.0,3.0,2.0,2.0,3.0
177,9반,18,조윤서,학습리더형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,1.0,5.0,1.0,1.0,2.0,3.0,1.0,1.0,3.0,1.0
178,9반,19,임은우,기초보완형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,3.0,1.0,3.0,3.0,2.0,1.0,1.0,3.0,2.0,1.0
179,9반,20,박정우,회복탄력형,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,3.0,3.0,1.0,3.0,3.0,1.0,4.0,1.0,2.0,3.0

In [256]:
final_df = pd.concat(final_df_list, ignore_index=True)
print(len(final_df))

200

In [257]:
final_df.to_excel('자기보고 시뮬레이션 데이터.xlsx', index=False)

# 반별로 엑섹 쪼개기

In [258]:
# 지명 + 자기보고 통합 데이터를 반별로 쪼개서 엑셀로 저장
final_df = pd.read_excel('학생_종합_시뮬레이션_데이터.xlsx')
final_df

,반,번호,이름,인기가 있는 친구는?,같이 놀고 싶은 친구는?,같이 놀기 싫은 친구는?,문제를 일으키는/학교의 규칙을 지키지 않는 친구는?,싸움을 하는 친구는?,다른 친구를 나쁘게 이야기하거나 따돌리는 친구는?,나쁜 소문을 퍼뜨리는 친구는?,...,문항73 (거부),문항74 (거부),문항75 (거부),문항1 (친구가 속상해 보일 때 나는 보통 ________),문항2 (수업 중 질문이 나오면 나는 ________),문항3 (수업 시간은 보통 ________ 느낌이다.),문항4 (친구랑 함께 공부하면 나는 ________),문항5 (친구보다 점수가 낮으면 나는 ________),문항6 (실수했을 때 나는 보통 ________),문항7 (내가 힘들다고 말하면 부모님은 ________)
0,10반,1,이소율,"서이준, 최현우","강가은, 배서연, 강시윤",최은우,"서이준, 김시윤",강가은,"강시윤, 서승우","장준서, 정채은",...,1,2,2,걱정해주고 같이 놀자고 한다,열심히 발표한다,신난다,서로 알려주며 같이 한다,하기 싫어진다,웃어넘긴다,대충 들어준다
1,10반,2,배서연,"장이준, 최현우",김우진,"서이준, 조은우, 김우진","장준서, 이소율, 서이준","김우진, 한승우","한승우, 서이준",김시윤,...,3,5,1,먼저 다가가서 위로한다,적극적으로 참여한다,신난다,함께 해서 잘 된다,짜증 난다,별로 신경 안 쓴다,대충 들어준다
2,10반,3,서이준,"한승우, 서승우","이도윤, 홍지안","김시윤, 한유준","장이준, 강채은, 한준서","김시윤, 최현우",장준서,"이도윤, 최은우, 한준서, 정채은, 장이준",...,1,1,1,신경 안 쓴다,손을 들고 대답한다,그냥 그렇다,혼자 한다,더 열심히 하려고 한다,조금 창피하다,조언은 해준다
3,10반,4,김시윤,강가은,"김우진, 한준서","김우진, 최현우",이도윤,"이도윤, 김우진","홍지안, 강채은","장이준, 배서연",...,3,4,1,신경 안 쓴다,가끔 대답한다,그냥 그렇다,혼자 한다,짜증 난다,속상해한다,안 들어준다
4,10반,5,강시윤,"장준서, 최은우, 이도윤","서승우, 서이준",한유준,"이소율, 장준서","장이준, 배서연","조은우, 최현우","서승우, 최은우, 강가은",...,3,1,2,신경 안 쓴다,손을 들고 대답한다,그냥 그렇다,혼자 한다,더 열심히 하려고 한다,괜찮다고 넘긴다,대충 들어준다
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,9반,16,이하은,이지유,오민서,"김연우, 임채원, 박정우","배이준, 임예은",김연우,"서예은, 김선우",박정우,...,1,1,1,무슨 일인지 물어본다,손을 들고 대답한다,신난다,내가 아는 걸 알려준다,짜증 난다,별로 신경 안 쓴다,조언은 해준다
196,9반,17,배이준,"이하은, 한은우, 강소율","정다인, 한은우","이이준, 김연우","김연우, 임채원, 임예은, 오민서","조윤서, 강소율, 오민서","강소율, 장수빈",김도현,...,2,2,3,잠깐 쳐다보고 말할까 말까 한다,열심히 발표한다,재밌고 즐겁다,내가 아는 걸 알려준다,짜증 난다,웃어넘긴다,조언은 해준다
197,9반,18,조윤서,김선우,김도현,"김선우, 이하은","이하은, 김선우, 서하윤","장준우, 김도현","오민서, 김연우","이이준, 강소율",...,1,3,1,그냥 지나간다,조용히 듣고만 있다,조금 지루하다,혼자 한다,다음엔 꼭 이기려고 한다,조금 창피하다,조언은 해준다
198,9반,19,임은우,"이하은, 강소율, 조윤서","서예은, 박정우, 이지유, 김도현, 이이준","한은우, 서예은","임채원, 장수빈",서하윤,강소율,"이지유, 이이준, 이하은",...,3,2,1,잠깐 쳐다보고 말할까 말까 한다,딴 짓을 한다,하기 싫다,같이 하기 싫다,하기 싫어진다,우울해한다,화를 낸다
199,9반,20,박정우,서하윤,"이하은, 서예은, 장준우, 배이준","이이준, 한은우","김선우, 김연우","배이준, 김선우","임채원, 김도현","강소율, 배이준",...,1,2,3,신경 안 쓴다,대답하지 않는다,재미없다,같이 하기 싫다,더 열심히 하려고 한다,조금 창피하다,화를 낸다

In [260]:
final_df_groupby = final_df.groupby('반')
for class_num, sub_final_df in final_df_groupby:
    print(f"Processing class: {class_num}")
    sub_final_df.to_excel(f'학생_종합_시뮬레이션_데이터_{class_num}.xlsx', index=False)

Processing class: 10반
Processing class: 1반
Processing class: 2반
Processing class: 3반
Processing class: 4반
Processing class: 5반
Processing class: 6반
Processing class: 7반
Processing class: 8반
Processing class: 9반