# 학급 분위기

## 응답 데이터 추출

### 지명 데이터 추출

In [50]:
import sys
print(sys.executable)   # 예: C:\ProgramData\anaconda3\python.exe
print(sys.path)         # 패키지 탐색 경로(여기에 site-packages가 있어야 import 가능)

import awswrangler as wr
query_df = wr.athena.read_sql_query(
    """
    select a.school_code, a.school_name, b.school_grade, b.school_num, b.class_name, c.psy_name, c.psy_code, c.close_yn, f.student_num, d.target_code, e.user_testing_no, e.question_no, e.student_code 
    from school_info a
    inner join school_class b on a.school_code = b.school_code
    inner join psy_class c on b.class_code = c.class_code
    inner join psy_target_detail d on c.class_code = d.class_code and c.psy_code = d.psy_code
    inner join at_user_testing_paper_pn e on d.user_testing_no = e.user_testing_no
    inner join school_student f on d.target_code = f.student_code and d.class_code = f.class_code
    where c.close_yn = 'Y' and e.question_no in (1, 4, 5, 6, 7, 12)
    and d.psy_code = 'P202511122059'
    """
    , database="schoolfriends-kmj"
)

c:\ProgramData\anaconda3\python.exe
['c:\\ProgramData\\anaconda3\\python313.zip', 'c:\\ProgramData\\anaconda3\\DLLs', 'c:\\ProgramData\\anaconda3\\Lib', 'c:\\ProgramData\\anaconda3', '', 'C:\\Users\\USER\\AppData\\Roaming\\Python\\Python313\\site-packages', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\win32', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\win32\\lib', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\Pythonwin']

In [51]:
query_df

,school_code,school_name,school_grade,school_num,class_name,psy_name,psy_code,close_yn,student_num,target_code,user_testing_no,question_no,student_code
0,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,"""8916207158814a67abc2""",1,AD00012025115D1E4010
1,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,"""8916207158814a67abc2""",1,AD00012025115D1E4016
2,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,"""8916207158814a67abc2""",4,AD00012025115D1E4003
3,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,"""8916207158814a67abc2""",4,AD00012025115D1E4008
4,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,"""8916207158814a67abc2""",4,AD00012025115D1E4010
...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,"""5021a196f7c74c81a151""",12,AD00012025115D1E4007
244,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,"""5021a196f7c74c81a151""",12,AD00012025115D1E4009
245,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,"""5021a196f7c74c81a151""",12,AD00012025115D1E4010
246,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,"""5021a196f7c74c81a151""",12,AD00012025115D1E4012
247,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,"""5021a196f7c74c81a151""",12,AD00012025115D1E4013

In [74]:
query_df['user_testing_no'] = query_df['user_testing_no'].str.replace('"', '')
query_df

,school_code,school_name,school_grade,school_num,class_name,psy_name,psy_code,close_yn,student_num,target_code,user_testing_no,question_no,student_code
0,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,8916207158814a67abc2,1,AD00012025115D1E4010
1,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,8916207158814a67abc2,1,AD00012025115D1E4016
2,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,8916207158814a67abc2,4,AD00012025115D1E4003
3,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,8916207158814a67abc2,4,AD00012025115D1E4008
4,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4020,8916207158814a67abc2,4,AD00012025115D1E4010
...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,5021a196f7c74c81a151,12,AD00012025115D1E4007
244,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,5021a196f7c74c81a151,12,AD00012025115D1E4009
245,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,5021a196f7c74c81a151,12,AD00012025115D1E4010
246,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,5021a196f7c74c81a151,12,AD00012025115D1E4012
247,AD0001,학지중학교,<NA>,<NA>,"""""","""25년 11월_1차""",P202511122059,Y,<NA>,AD00012025115D1E4001,5021a196f7c74c81a151,12,AD00012025115D1E4013

In [75]:
query_df.columns

Index(['school_code', 'school_name', 'school_grade', 'school_num',
       'class_name', 'psy_name', 'psy_code', 'close_yn', 'student_num',
       'target_code', 'user_testing_no', 'question_no', 'student_code'],
      dtype='object')

In [76]:
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]

In [77]:
# 검수하고자 하는 평가명 필터링
df = query_df[query_df['psy_name'].str.contains('25년 11월_1차')]
print(df)

    school_code school_name  school_grade  school_num class_name  \
0        AD0001       학지중학교          <NA>        <NA>         ""
1        AD0001       학지중학교          <NA>        <NA>         ""
2        AD0001       학지중학교          <NA>        <NA>         ""
3        AD0001       학지중학교          <NA>        <NA>         ""
4        AD0001       학지중학교          <NA>        <NA>         ""
..          ...         ...           ...         ...        ...
243      AD0001       학지중학교          <NA>        <NA>         ""
244      AD0001       학지중학교          <NA>        <NA>         ""
245      AD0001       학지중학교          <NA>        <NA>         ""
246      AD0001       학지중학교          <NA>        <NA>         ""
247      AD0001       학지중학교          <NA>        <NA>         ""

         psy_name       psy_code close_yn  student_num           target_code  \
0    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
1    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
2    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
3    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
4    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
..            ...            ...      ...          ...                   ...
243  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
244  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
245  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
246  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
247  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001

          user_testing_no  question_no          student_code
0    8916207158814a67abc2            1  AD00012025115D1E4010
1    8916207158814a67abc2            1  AD00012025115D1E4016
2    8916207158814a67abc2            4  AD00012025115D1E4003
3    8916207158814a67abc2            4  AD00012025115D1E4008
4    8916207158814a67abc2            4  AD00012025115D1E4010
..                    ...          ...                   ...
243  5021a196f7c74c81a151           12  AD00012025115D1E4007
244  5021a196f7c74c81a151           12  AD00012025115D1E4009
245  5021a196f7c74c81a151           12  AD00012025115D1E4010
246  5021a196f7c74c81a151           12  AD00012025115D1E4012
247  5021a196f7c74c81a151           12  AD00012025115D1E4013

[248 rows x 13 columns]

### 자기보고 데이터 추출

In [ ]:
# s3까지는 정상적으로 올라갔지만
# aws 크롤러가 json 데이터를 읽으면서 ,을 구분자로 인식해 스키마가 깨짐
# 해결 방법 중 base64로 인코딩하고 크롤링 후 아테나에서 디코딩하는 방법을 적용해봄
# import base64
# import pandas as pd

# df = pd.read_csv("AT_USER_TESTING_PAPER_202511140921.csv")

# def json_to_b64(x):
#     if pd.isna(x):
#         return x
#     return base64.b64encode(x.encode("utf-8")).decode("utf-8")

# df["PAPER_JSON"] = df["PAPER_JSON"].apply(json_to_b64)

# df.to_csv("AT_USER_TESTING_PAPER_202511140921_encoded.csv", index=False)

In [35]:
# # 아테네로 쿼링
# import awswrangler as wr
# query_df = wr.athena.read_sql_query(
#     """
#     select col0, CAST(from_base64(col1) AS VARCHAR) AS decoded_text
#     from at_user_testing_paper
#     where col0 = '000f74aeb10d4041a999'
#     """
#     , database="schoolfriends-kmj"
# )

QueryFailed: TYPE_MISMATCH: line 7:3: Cannot cast varbinary to varchar. You may need to manually clean the data at location 's3://aws-athena-query-results-932744610695-ap-northeast-2/tables/a650aea4-1abf-4533-a0ac-b3dfcd3a2c96' before retrying. Athena will not delete data in your account.

In [78]:
student_testing_list = df['user_testing_no'].unique().tolist()
print(student_testing_list)

['8916207158814a67abc2', 'a28c9553672c4f54ad7d', '157327d769394633811f', 'd163f8c83ef64c50aa87', 'ac181f9b8eaa426cb4c8', '72559204bbdf448b912f', '30aa23408f104d1293a4', '4f3f46fc2d2244758a78', 'dc9998566c234f0599c3', '1eb4ec746358472a9a97', 'a511507acce04b908351', '14c8df44e4004885a5e0', '1d49e9937ff141f98e40', '083269d802e940ce95be', 'e0cebb8191764f41a106', 'bd5e577fd48840d6bd34', '521595a387b449f8b55d', '59237a4bfe5b46189c25', '62dfbfb230e1497c963a', '5021a196f7c74c81a151']

In [80]:
# 타입오류가 계속 발생하여
# 급하기 때문에 raw csv에서 학생명단으로 병합하여 검수 진행
import pandas as pd
testing_paper_df = pd.read_csv("AT_USER_TESTING_PAPER_202511140921.csv")
# 학생 리스트 구하기
student_testing_list = df['user_testing_no'].unique().tolist()
print(student_testing_list)
print(len(student_testing_list))
# 병합하여 자기보고 json 추출
testing_paper_df_filtered = pd.merge(testing_paper_df, pd.DataFrame({'USER_TESTING_NO': student_testing_list}), on='USER_TESTING_NO', how='inner')
print(testing_paper_df_filtered)

['8916207158814a67abc2', 'a28c9553672c4f54ad7d', '157327d769394633811f', 'd163f8c83ef64c50aa87', 'ac181f9b8eaa426cb4c8', '72559204bbdf448b912f', '30aa23408f104d1293a4', '4f3f46fc2d2244758a78', 'dc9998566c234f0599c3', '1eb4ec746358472a9a97', 'a511507acce04b908351', '14c8df44e4004885a5e0', '1d49e9937ff141f98e40', '083269d802e940ce95be', 'e0cebb8191764f41a106', 'bd5e577fd48840d6bd34', '521595a387b449f8b55d', '59237a4bfe5b46189c25', '62dfbfb230e1497c963a', '5021a196f7c74c81a151']
20
         USER_TESTING_NO                                         PAPER_JSON  \
0   083269d802e940ce95be  {"questionChoiceList":[{"questionNo":1,"choice...
1   14c8df44e4004885a5e0  {"questionChoiceList":[{"questionNo":1,"choice...
2   157327d769394633811f  {"questionChoiceList":[{"questionNo":1,"choice...
3   1d49e9937ff141f98e40  {"questionChoiceList":[{"questionNo":1,"choice...
4   1eb4ec746358472a9a97  {"questionChoiceList":[{"questionNo":1,"choice...
5   30aa23408f104d1293a4  {"questionChoiceList":[{"questionNo":1,"choice...
6   4f3f46fc2d2244758a78  {"questionChoiceList":[{"questionNo":1,"choice...
7   5021a196f7c74c81a151  {"questionChoiceList":[{"questionNo":1,"choice...
8   521595a387b449f8b55d  {"questionChoiceList":[{"questionNo":1,"choice...
9   59237a4bfe5b46189c25  {"questionChoiceList":[{"questionNo":1,"choice...
10  62dfbfb230e1497c963a  {"questionChoiceList":[{"questionNo":1,"choice...
11  72559204bbdf448b912f  {"questionChoiceList":[{"questionNo":1,"choice...
12  8916207158814a67abc2  {"questionChoiceList":[{"questionNo":1,"choice...
13  a28c9553672c4f54ad7d  {"questionChoiceList":[{"questionNo":1,"choice...
14  a511507acce04b908351  {"questionChoiceList":[{"questionNo":1,"choice...
15  ac181f9b8eaa426cb4c8  {"questionChoiceList":[{"questionNo":1,"choice...
16  bd5e577fd48840d6bd34  {"questionChoiceList":[{"questionNo":1,"choice...
17  d163f8c83ef64c50aa87  {"questionChoiceList":[{"questionNo":1,"choice...
18  dc9998566c234f0599c3  {"questionChoiceList":[{"questionNo":1,"choice...
19  e0cebb8191764f41a106  {"questionChoiceList":[{"questionNo":1,"choice...

               REG_DATE
0   2025-11-13 11:17:36
1   2025-11-13 11:31:45
2   2025-11-13 12:40:22
3   2025-11-13 11:24:31
4   2025-11-13 11:46:34
5   2025-11-13 12:11:09
6   2025-11-13 12:03:14
7   2025-11-13 10:27:12
8   2025-11-13 10:54:38
9   2025-11-13 10:41:26
10  2025-11-13 10:34:01
11  2025-11-13 12:18:15
12  2025-11-13 12:54:45
13  2025-11-13 12:47:15
14  2025-11-13 11:39:22
15  2025-11-13 12:25:40
16  2025-11-13 11:01:39
17  2025-11-13 12:32:58
18  2025-11-13 13:17:53
19  2025-11-13 11:09:46

In [ ]:
# 디버깅용 엑셀 저장
test_df = testing_paper_df_filtered.to_excel("testing_paper_filtered.xlsx", index=False)

In [110]:
# json 데이터 파싱 후 프레임 형태로 변환 필요
import json
# str -> json 변환
json_test = json.loads(testing_paper_df_filtered['PAPER_JSON'][0])
print(json_test['questionChoiceList'])
print(pd.DataFrame(json_test['questionChoiceList']))
print(pd.DataFrame(json_test['questionChoiceList'])['choiceScore'])
test_1 = pd.DataFrame(json_test['questionChoiceList'])['choiceScore']
print(pd.DataFrame(json_test['questionChoiceList'])['choiceScore'].transpose())
test_2 = pd.DataFrame(json_test['questionChoiceList'])['choiceScore'].transpose()
# 위와 같은 방식으로 행별로 뜯어서 순환 전처리

[{'questionNo': 1, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 2, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 3, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 4, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 5, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 6, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 7, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 8, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 9, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 10, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 11, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 12, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 13, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 14, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 15, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 16, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 17, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 18, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 19, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 20, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 21, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 22, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 23, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 24, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 25, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 26, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 27, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 28, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 29, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 30, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 31, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 32, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 33, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 34, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 35, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 36, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 37, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 38, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 39, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 40, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 41, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 42, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 43, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 44, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 45, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 46, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 47, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 48, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 49, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 50, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 51, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 52, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 53, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 54, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 55, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 56, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 57, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 58, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 59, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 60, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 61, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 62, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 63, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 64, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 65, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 66, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 67, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 68, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 69, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 70, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 71, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 72, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 73, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 74, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 75, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 76, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 77, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 78, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 79, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 80, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 81, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 82, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 83, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 84, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 85, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 86, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 87, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 88, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 89, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 90, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 91, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 92, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 93, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 94, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 95, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 96, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 97, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 98, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 99, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 100, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 101, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 102, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 103, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 104, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 105, 'choiceNo': '2', 'choiceScore': '2'}, {'questionNo': 106, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 107, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 108, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 109, 'choiceNo': '5', 'choiceScore': '5'}, {'questionNo': 110, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 111, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 112, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 113, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 114, 'choiceNo': '1', 'choiceScore': '1'}, {'questionNo': 115, 'choiceNo': '4', 'choiceScore': '4'}, {'questionNo': 116, 'choiceNo': '3', 'choiceScore': '3'}, {'questionNo': 117, 'choiceNo': '3', 'choiceScore': '3'}]
     questionNo choiceNo choiceScore
0             1        1           1
1             2        4           4
2             3        3           3
3             4        3           3
4             5        3           3
..          ...      ...         ...
112         113        3           3
113         114        1           1
114         115        4           4
115         116        3           3
116         117        3           3

[117 rows x 3 columns]
0      1
1      4
2      3
3      3
4      3
      ..
112    3
113    1
114    4
115    3
116    3
Name: choiceScore, Length: 117, dtype: object
0      1
1      4
2      3
3      3
4      3
      ..
112    3
113    1
114    4
115    3
116    3
Name: choiceScore, Length: 117, dtype: object

In [119]:
self_report_df = pd.DataFrame()
for idx, row in testing_paper_df_filtered.iterrows():
    user_testing_no = row['USER_TESTING_NO']
    json_data = json.loads(row['PAPER_JSON'])
    question_choices_df = pd.DataFrame(json_data['questionChoiceList'])
    question_choices_df = question_choices_df['choiceScore']
    temp_df = pd.DataFrame(question_choices_df).transpose()
    temp_df['USER_TESTING_NO'] = user_testing_no
    self_report_df = pd.concat([self_report_df, temp_df], ignore_index=True)
print(self_report_df)

    0  1  2  3  4  5  6  7  8  9  ... 108 109 110 111 112 113 114 115 116  \
0   1  4  3  3  3  3  3  3  1  1  ...   5   4   4   4   3   1   4   3   3
1   4  2  3  3  1  3  3  5  4  3  ...   5   4   3   4   3   5   5   4   5
2   3  3  3  3  1  3  3  3  2  4  ...   3   1   5   5   4   4   3   5   5
3   4  5  5  2  1  1  1  3  4  3  ...   5   5   2   2   1   1   2   3   1
4   4  5  3  4  3  3  1  2  1  1  ...   1   5   1   3   2   1   1   2   1
5   4  5  5  5  2  5  2  4  5  3  ...   1   1   3   1   3   1   2   2   1
6   3  4  4  2  3  3  4  4  5  5  ...   3   5   5   5   3   2   5   3   4
7   5  5  2  5  3  4  4  4  4  3  ...   2   4   1   3   3   3   3   2   1
8   1  5  5  4  4  2  2  1  3  3  ...   3   5   5   5   5   2   5   3   4
9   2  1  1  2  1  1  2  3  3  2  ...   2   1   1   3   5   1   1   2   3
10  3  3  5  5  5  3  4  3  1  5  ...   5   2   5   2   1   5   1   3   1
11  3  3  3  1  2  3  2  2  1  4  ...   4   5   4   3   3   2   3   5   4
12  5  3  3  4  4  5  5  4  3  4  ...   3   2   3   3   5   3   3   3   4
13  3  1  1  1  1  2  1  3  2  4  ...   2   1   2   2   3   4   2   3   1
14  1  1  1  1  1  1  4  3  4  1  ...   2   1   2   3   1   1   1   3   1
15  3  4  5  5  4  3  5  4  5  5  ...   3   3   2   2   1   3   3   3   3
16  1  3  2  2  1  1  1  3  1  2  ...   2   1   2   3   1   2   3   3   3
17  3  1  4  3  4  3  2  3  2  2  ...   3   5   4   4   4   4   4   3   5
18  3  5  5  3  5  2  3  3  2  3  ...   4   4   5   5   4   5   5   4   2
19  2  4  2  1  1  1  5  5  5  4  ...   3   5   4   4   2   3   1   2   2

         USER_TESTING_NO
0   083269d802e940ce95be
1   14c8df44e4004885a5e0
2   157327d769394633811f
3   1d49e9937ff141f98e40
4   1eb4ec746358472a9a97
5   30aa23408f104d1293a4
6   4f3f46fc2d2244758a78
7   5021a196f7c74c81a151
8   521595a387b449f8b55d
9   59237a4bfe5b46189c25
10  62dfbfb230e1497c963a
11  72559204bbdf448b912f
12  8916207158814a67abc2
13  a28c9553672c4f54ad7d
14  a511507acce04b908351
15  ac181f9b8eaa426cb4c8
16  bd5e577fd48840d6bd34
17  d163f8c83ef64c50aa87
18  dc9998566c234f0599c3
19  e0cebb8191764f41a106

[20 rows x 118 columns]

In [120]:
# 컬럼명 변경
self_report_df.columns = [f'q{col+1}' if isinstance(col, int) else col for col in self_report_df.columns]
# 컬럼명 순서 변경
self_report_df = self_report_df[['USER_TESTING_NO'] + [col for col in self_report_df.columns if col != 'USER_TESTING_NO']]
print(self_report_df)

         USER_TESTING_NO q1 q2 q3 q4 q5 q6 q7 q8 q9  ... q108 q109 q110 q111  \
0   083269d802e940ce95be  1  4  3  3  3  3  3  3  1  ...    5    5    4    4
1   14c8df44e4004885a5e0  4  2  3  3  1  3  3  5  4  ...    5    5    4    3
2   157327d769394633811f  3  3  3  3  1  3  3  3  2  ...    3    3    1    5
3   1d49e9937ff141f98e40  4  5  5  2  1  1  1  3  4  ...    3    5    5    2
4   1eb4ec746358472a9a97  4  5  3  4  3  3  1  2  1  ...    1    1    5    1
5   30aa23408f104d1293a4  4  5  5  5  2  5  2  4  5  ...    1    1    1    3
6   4f3f46fc2d2244758a78  3  4  4  2  3  3  4  4  5  ...    4    3    5    5
7   5021a196f7c74c81a151  5  5  2  5  3  4  4  4  4  ...    5    2    4    1
8   521595a387b449f8b55d  1  5  5  4  4  2  2  1  3  ...    3    3    5    5
9   59237a4bfe5b46189c25  2  1  1  2  1  1  2  3  3  ...    1    2    1    1
10  62dfbfb230e1497c963a  3  3  5  5  5  3  4  3  1  ...    1    5    2    5
11  72559204bbdf448b912f  3  3  3  1  2  3  2  2  1  ...    4    4    5    4
12  8916207158814a67abc2  5  3  3  4  4  5  5  4  3  ...    2    3    2    3
13  a28c9553672c4f54ad7d  3  1  1  1  1  2  1  3  2  ...    3    2    1    2
14  a511507acce04b908351  1  1  1  1  1  1  4  3  4  ...    3    2    1    2
15  ac181f9b8eaa426cb4c8  3  4  5  5  4  3  5  4  5  ...    5    3    3    2
16  bd5e577fd48840d6bd34  1  3  2  2  1  1  1  3  1  ...    3    2    1    2
17  d163f8c83ef64c50aa87  3  1  4  3  4  3  2  3  2  ...    5    3    5    4
18  dc9998566c234f0599c3  3  5  5  3  5  2  3  3  2  ...    4    4    4    5
19  e0cebb8191764f41a106  2  4  2  1  1  1  5  5  5  ...    1    3    5    4

   q112 q113 q114 q115 q116 q117
0     4    3    1    4    3    3
1     4    3    5    5    4    5
2     5    4    4    3    5    5
3     2    1    1    2    3    1
4     3    2    1    1    2    1
5     1    3    1    2    2    1
6     5    3    2    5    3    4
7     3    3    3    3    2    1
8     5    5    2    5    3    4
9     3    5    1    1    2    3
10    2    1    5    1    3    1
11    3    3    2    3    5    4
12    3    5    3    3    3    4
13    2    3    4    2    3    1
14    3    1    1    1    3    1
15    2    1    3    3    3    3
16    3    1    2    3    3    3
17    4    4    4    4    3    5
18    5    4    5    5    4    2
19    4    2    3    1    2    2

[20 rows x 118 columns]

## 친구 또래공동체

In [132]:
peer_community_df = self_report_df[['USER_TESTING_NO', 'q41', 'q42', 'q43', 'q44']].copy()
# 타입변환
peer_community_df[['q41', 'q42', 'q43', 'q44']] = peer_community_df[['q41', 'q42', 'q43', 'q44']].apply(pd.to_numeric, errors='coerce')
# 행별 평균 구하기
peer_community_df['peer_community_point'] = peer_community_df[['q41', 'q42', 'q43', 'q44']].mean(axis=1)
print(peer_community_df)
# 전체 평균 구하기
overall_peer_community_point = peer_community_df['peer_community_point'].mean(axis=0)
print(f"Overall Peer Community Point: {overall_peer_community_point}")

         USER_TESTING_NO  q41  q42  q43  q44  peer_community_point
0   083269d802e940ce95be    2    2    1    4                  2.25
1   14c8df44e4004885a5e0    3    4    4    3                  3.50
2   157327d769394633811f    4    5    5    5                  4.75
3   1d49e9937ff141f98e40    1    1    2    3                  1.75
4   1eb4ec746358472a9a97    1    1    4    3                  2.25
5   30aa23408f104d1293a4    5    1    2    1                  2.25
6   4f3f46fc2d2244758a78    5    5    3    4                  4.25
7   5021a196f7c74c81a151    1    1    4    3                  2.25
8   521595a387b449f8b55d    3    2    5    5                  3.75
9   59237a4bfe5b46189c25    4    2    3    1                  2.50
10  62dfbfb230e1497c963a    1    4    3    3                  2.75
11  72559204bbdf448b912f    2    2    1    2                  1.75
12  8916207158814a67abc2    5    5    5    5                  5.00
13  a28c9553672c4f54ad7d    2    2    1    5                  2.50
14  a511507acce04b908351    2    2    2    1                  1.75
15  ac181f9b8eaa426cb4c8    3    4    5    5                  4.25
16  bd5e577fd48840d6bd34    4    3    5    1                  3.25
17  d163f8c83ef64c50aa87    2    3    2    2                  2.25
18  dc9998566c234f0599c3    3    2    5    3                  3.25
19  e0cebb8191764f41a106    1    1    1    2                  1.25
Overall Peer Community Point: 2.875

## 학습 또래공동체

In [133]:
peer_learning_community_df = self_report_df[['USER_TESTING_NO', 'q37', 'q38', 'q39', 'q40']].copy()
# 타입변환
peer_learning_community_df[['q37', 'q38', 'q39', 'q40']] = peer_learning_community_df[['q37', 'q38', 'q39', 'q40']].apply(pd.to_numeric, errors='coerce')
# 행별 평균 구하기
peer_learning_community_df['peer_learning_community_point'] = peer_learning_community_df[['q37', 'q38', 'q39', 'q40']].mean(axis=1)
print(peer_learning_community_df)
# 전체 평균 구하기
overall_peer_learning_community_point = peer_learning_community_df['peer_learning_community_point'].mean(axis=0)
print(f"Overall Peer Learning Community Point: {overall_peer_learning_community_point}")

         USER_TESTING_NO  q37  q38  q39  q40  peer_learning_community_point
0   083269d802e940ce95be    4    5    4    5                           4.50
1   14c8df44e4004885a5e0    4    5    5    4                           4.50
2   157327d769394633811f    4    3    5    4                           4.00
3   1d49e9937ff141f98e40    4    2    1    2                           2.25
4   1eb4ec746358472a9a97    3    3    2    1                           2.25
5   30aa23408f104d1293a4    5    1    2    5                           3.25
6   4f3f46fc2d2244758a78    5    2    4    3                           3.50
7   5021a196f7c74c81a151    3    4    3    2                           3.00
8   521595a387b449f8b55d    5    2    2    3                           3.00
9   59237a4bfe5b46189c25    2    5    3    5                           3.75
10  62dfbfb230e1497c963a    1    4    3    2                           2.50
11  72559204bbdf448b912f    2    4    4    4                           3.50
12  8916207158814a67abc2    4    3    5    4                           4.00
13  a28c9553672c4f54ad7d    3    1    2    3                           2.25
14  a511507acce04b908351    1    3    1    2                           1.75
15  ac181f9b8eaa426cb4c8    5    4    5    4                           4.50
16  bd5e577fd48840d6bd34    1    3    1    1                           1.50
17  d163f8c83ef64c50aa87    1    2    5    2                           2.50
18  dc9998566c234f0599c3    4    5    5    5                           4.75
19  e0cebb8191764f41a106    1    4    2    3                           2.50
Overall Peer Learning Community Point: 3.1875

## 공격성 규범 검수

In [16]:
# 학생 리스트 구하기
student_list_obj, psy_code = student_list(df)
print(student_list_obj, psy_code)
print(len(student_list_obj))

['AD00012025115D1E4020', 'AD00012025115D1E4019', 'AD00012025115D1E4018', 'AD00012025115D1E4017', 'AD00012025115D1E4016', 'AD00012025115D1E4015', 'AD00012025115D1E4014', 'AD00012025115D1E4013', 'AD00012025115D1E4012', 'AD00012025115D1E4011', 'AD00012025115D1E4010', 'AD00012025115D1E4009', 'AD00012025115D1E4008', 'AD00012025115D1E4007', 'AD00012025115D1E4006', 'AD00012025115D1E4005', 'AD00012025115D1E4004', 'AD00012025115D1E4003', 'AD00012025115D1E4002', 'AD00012025115D1E4001'] P202511122059
20

In [18]:
# 지명수 구하기
aggression_point_df, _ = count_point(df, student_list_obj, [4,5])
n12_point_df, _ = count_point(df, student_list_obj, [12])
print(aggression_point_df)
print(n12_point_df)

            student_code  num_point
0   AD00012025115D1E4020          2
1   AD00012025115D1E4019          8
2   AD00012025115D1E4018          0
3   AD00012025115D1E4017         11
4   AD00012025115D1E4016          1
5   AD00012025115D1E4015          1
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          0
8   AD00012025115D1E4012          2
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          9
11  AD00012025115D1E4009          0
12  AD00012025115D1E4008          8
13  AD00012025115D1E4007          0
14  AD00012025115D1E4006         12
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          0
17  AD00012025115D1E4003         16
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          6
            student_code  num_point
0   AD00012025115D1E4020          2
1   AD00012025115D1E4019          0
2   AD00012025115D1E4018          4
3   AD00012025115D1E4017          0
4   AD00012025115D1E4016          8
5   AD00012025115D1E4015          0
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          4
8   AD00012025115D1E4012          7
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          3
11  AD00012025115D1E4009          6
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          2
14  AD00012025115D1E4006          3
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          2
17  AD00012025115D1E4003          0
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          1

In [19]:
# 공격 지명수 * 친구 지명수
aggression_point_df['n12_point'] = n12_point_df['num_point']
aggression_point_df.rename(columns={'num_point':'aggression_point'}, inplace=True)
aggression_point_df['aggression_x_n12'] = aggression_point_df['aggression_point'] * aggression_point_df['n12_point']
print(aggression_point_df)

            student_code  aggression_point  n12_point  aggression_x_n12
0   AD00012025115D1E4020                 2          2                 4
1   AD00012025115D1E4019                 8          0                 0
2   AD00012025115D1E4018                 0          4                 0
3   AD00012025115D1E4017                11          0                 0
4   AD00012025115D1E4016                 1          8                 8
5   AD00012025115D1E4015                 1          0                 0
6   AD00012025115D1E4014                 0          0                 0
7   AD00012025115D1E4013                 0          4                 0
8   AD00012025115D1E4012                 2          7                14
9   AD00012025115D1E4011                 0          0                 0
10  AD00012025115D1E4010                 9          3                27
11  AD00012025115D1E4009                 0          6                 0
12  AD00012025115D1E4008                 8          0                 0
13  AD00012025115D1E4007                 0          2                 0
14  AD00012025115D1E4006                12          3                36
15  AD00012025115D1E4005                 0          0                 0
16  AD00012025115D1E4004                 0          2                 0
17  AD00012025115D1E4003                16          0                 0
18  AD00012025115D1E4002                 0          0                 0
19  AD00012025115D1E4001                 6          1                 6

In [21]:
# 공격성 규범 지수 계산
def aggression_norms(df, celling_parameter=67) :
    import pandas as pd
    student_list_obj, psy_code = student_list(df)
    aggression_point_df, psy_code = count_point(df, student_list_obj, [4,5])
    n12_point_df, psy_code = count_point(df, student_list_obj, [12])

    aggression_norms_df = pd.merge(aggression_point_df, n12_point_df, on='student_code', suffixes=('_agg', '_12no'))
    aggression_norms_df['agg*12no_num_point'] = aggression_norms_df['num_point_agg'] * aggression_norms_df['num_point_12no']
    aggression_norms_df.sort_values(by='agg*12no_num_point', ascending=False, inplace=True)
    
    top5_aggression_norms_df = aggression_norms_df.head(5)
    top5_mean = top5_aggression_norms_df['agg*12no_num_point'].mean()
    total_mean = aggression_norms_df['agg*12no_num_point'].mean()
    weighted_mean = 0.4 * (top5_mean) + 0.6 * (total_mean)
    weighted_mean = 4 * ((min(max(weighted_mean, 0), celling_parameter)-0)/celling_parameter)+1
    result_df = pd.DataFrame({'psy_code': [psy_code], 'top5_mean': [top5_mean], 'total_mean': [total_mean], 'weighted_mean': [weighted_mean]})
    result_df['reg_date'] = pd.Timestamp.now()
    result_df['purpose'] = f'"purpose=calibration;celling_parameter={celling_parameter};author=Yumin"'
    return result_df
result_df = aggression_norms(df)
print(result_df)

        psy_code  top5_mean  total_mean  weighted_mean  \
0  P202511122059       18.2        4.75       1.604776

                    reg_date  \
0 2025-11-17 09:43:24.703850

                                             purpose
0  "purpose=calibration;celling_parameter=67;auth...

## 친사회성 규범 검수

In [22]:
# 학생 리스트 구하기
student_list_obj, psy_code = student_list(df)
print(student_list_obj, psy_code)
print(len(student_list_obj))

['AD00012025115D1E4020', 'AD00012025115D1E4019', 'AD00012025115D1E4018', 'AD00012025115D1E4017', 'AD00012025115D1E4016', 'AD00012025115D1E4015', 'AD00012025115D1E4014', 'AD00012025115D1E4013', 'AD00012025115D1E4012', 'AD00012025115D1E4011', 'AD00012025115D1E4010', 'AD00012025115D1E4009', 'AD00012025115D1E4008', 'AD00012025115D1E4007', 'AD00012025115D1E4006', 'AD00012025115D1E4005', 'AD00012025115D1E4004', 'AD00012025115D1E4003', 'AD00012025115D1E4002', 'AD00012025115D1E4001'] P202511122059
20

In [23]:
# 지명수 구하기
prosociality_point_df, _ = count_point(df, student_list_obj, [6,7])
n12_point_df, _ = count_point(df, student_list_obj, [12])
print(prosociality_point_df)
print(n12_point_df)

            student_code  num_point
0   AD00012025115D1E4020         15
1   AD00012025115D1E4019          1
2   AD00012025115D1E4018         18
3   AD00012025115D1E4017          2
4   AD00012025115D1E4016         13
5   AD00012025115D1E4015          2
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          0
8   AD00012025115D1E4012         13
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          0
11  AD00012025115D1E4009          0
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          3
14  AD00012025115D1E4006          1
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004         13
17  AD00012025115D1E4003          0
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          0
            student_code  num_point
0   AD00012025115D1E4020          2
1   AD00012025115D1E4019          0
2   AD00012025115D1E4018          4
3   AD00012025115D1E4017          0
4   AD00012025115D1E4016          8
5   AD00012025115D1E4015          0
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          4
8   AD00012025115D1E4012          7
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          3
11  AD00012025115D1E4009          6
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          2
14  AD00012025115D1E4006          3
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          2
17  AD00012025115D1E4003          0
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          1

In [24]:
# 친사회성 지명수 * 친구 지명수
prosociality_point_df['n12_point'] = n12_point_df['num_point']
prosociality_point_df.rename(columns={'num_point':'prosociality_point'}, inplace=True)
prosociality_point_df['prosociality_x_n12'] = prosociality_point_df['prosociality_point'] * prosociality_point_df['n12_point']
print(prosociality_point_df)

            student_code  prosociality_point  n12_point  prosociality_x_n12
0   AD00012025115D1E4020                  15          2                  30
1   AD00012025115D1E4019                   1          0                   0
2   AD00012025115D1E4018                  18          4                  72
3   AD00012025115D1E4017                   2          0                   0
4   AD00012025115D1E4016                  13          8                 104
5   AD00012025115D1E4015                   2          0                   0
6   AD00012025115D1E4014                   0          0                   0
7   AD00012025115D1E4013                   0          4                   0
8   AD00012025115D1E4012                  13          7                  91
9   AD00012025115D1E4011                   0          0                   0
10  AD00012025115D1E4010                   0          3                   0
11  AD00012025115D1E4009                   0          6                   0
12  AD00012025115D1E4008                   0          0                   0
13  AD00012025115D1E4007                   3          2                   6
14  AD00012025115D1E4006                   1          3                   3
15  AD00012025115D1E4005                   0          0                   0
16  AD00012025115D1E4004                  13          2                  26
17  AD00012025115D1E4003                   0          0                   0
18  AD00012025115D1E4002                   0          0                   0
19  AD00012025115D1E4001                   0          1                   0

In [25]:
# 친사회성성 규범 지수 계산
def prosociality_norms(df, celling_parameter=67) :
    import pandas as pd
    student_list_obj, psy_code = student_list(df)
    prosociality_point_df, psy_code = count_point(df, student_list_obj, [6,7])
    n12_point_df, psy_code = count_point(df, student_list_obj, [12])

    prosociality_norms_df = pd.merge(prosociality_point_df, n12_point_df, on='student_code', suffixes=('_pro', '_12no'))
    prosociality_norms_df['pro*12no_num_point'] = prosociality_norms_df['num_point_pro'] * prosociality_norms_df['num_point_12no']
    prosociality_norms_df.sort_values(by='pro*12no_num_point', ascending=False, inplace=True)
    
    top5_prosociality_norms_df = prosociality_norms_df.head(5)
    top5_mean = top5_prosociality_norms_df['pro*12no_num_point'].mean()
    total_mean = prosociality_norms_df['pro*12no_num_point'].mean()
    weighted_mean = 0.4 * (top5_mean) + 0.6 * (total_mean)
    weighted_mean = 4 * ((min(max(weighted_mean, 0), celling_parameter)-0)/celling_parameter)+1
    result_df = pd.DataFrame({'psy_code': [psy_code], 'top5_mean': [top5_mean], 'total_mean': [total_mean], 'weighted_mean': [weighted_mean]})
    result_df['reg_date'] = pd.Timestamp.now()
    result_df['purpose'] = f'"purpose=calibration;celling_parameter={celling_parameter};author=Yumin"'
    return result_df
result_df = prosociality_norms(df)
print(result_df)

        psy_code  top5_mean  total_mean  weighted_mean  \
0  P202511122059       64.6        16.6       3.137313

                    reg_date  \
0 2025-11-17 09:47:32.435561

                                             purpose
0  "purpose=calibration;celling_parameter=67;auth...

## 학습참여 규범

In [171]:
participation_learning_df = self_report_df[['USER_TESTING_NO', 'q45', 'q46', 'q47', 'q48', 'q49', 'q50', 'q51', 'q52', 'q53', 'q54']].copy()
# 타입변환
participation_learning_df[['q45', 'q46', 'q47', 'q48', 'q49', 'q50', 'q51', 'q52', 'q53', 'q54']] = participation_learning_df[['q45', 'q46', 'q47', 'q48', 'q49', 'q50', 'q51', 'q52', 'q53', 'q54']].apply(pd.to_numeric, errors='coerce')
# 행별 평균 구하기
participation_learning_df['participation_learning_point'] = participation_learning_df[['q45', 'q46', 'q47', 'q48', 'q49', 'q50', 'q51', 'q52', 'q53', 'q54']].mean(axis=1)
print(participation_learning_df)

         USER_TESTING_NO  q45  q46  q47  q48  q49  q50  q51  q52  q53  q54  \
0   083269d802e940ce95be    5    5    3    3    3    5    5    3    3    5
1   14c8df44e4004885a5e0    5    1    2    3    3    4    3    4    4    5
2   157327d769394633811f    2    1    2    2    3    3    3    3    5    3
3   1d49e9937ff141f98e40    1    1    1    2    4    5    2    3    3    1
4   1eb4ec746358472a9a97    2    5    3    4    5    3    3    1    3    3
5   30aa23408f104d1293a4    5    5    5    5    3    2    3    3    2    2
6   4f3f46fc2d2244758a78    2    1    2    3    2    3    5    5    2    4
7   5021a196f7c74c81a151    5    5    3    3    5    3    3    5    3    1
8   521595a387b449f8b55d    4    5    4    5    5    3    5    4    5    5
9   59237a4bfe5b46189c25    3    3    3    1    1    1    1    1    1    1
10  62dfbfb230e1497c963a    3    3    4    5    5    2    3    4    3    5
11  72559204bbdf448b912f    3    2    4    3    3    2    1    3    2    4
12  8916207158814a67abc2    2    1    3    5    1    4    3    4    3    4
13  a28c9553672c4f54ad7d    1    4    3    3    3    2    1    1    2    4
14  a511507acce04b908351    1    3    5    2    2    3    1    1    1    2
15  ac181f9b8eaa426cb4c8    4    5    4    3    4    3    5    5    5    1
16  bd5e577fd48840d6bd34    1    3    1    3    4    4    3    3    3    3
17  d163f8c83ef64c50aa87    1    3    1    2    1    2    2    3    3    1
18  dc9998566c234f0599c3    1    5    2    3    3    5    2    3    3    2
19  e0cebb8191764f41a106    2    1    3    2    2    3    1    1    2    1

    participation_learning_point
0                            4.0
1                            3.4
2                            2.7
3                            2.3
4                            3.2
5                            3.5
6                            2.9
7                            3.6
8                            4.5
9                            1.6
10                           3.7
11                           2.7
12                           3.0
13                           2.4
14                           2.1
15                           3.9
16                           2.8
17                           1.9
18                           2.9
19                           1.8

In [172]:
# 지명수 구하기
n12_point_df, _ = count_point(df, student_list_obj, [12])
print(n12_point_df)

            student_code  num_point
0   AD00012025115D1E4020          2
1   AD00012025115D1E4019          0
2   AD00012025115D1E4018          4
3   AD00012025115D1E4017          0
4   AD00012025115D1E4016          8
5   AD00012025115D1E4015          0
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          4
8   AD00012025115D1E4012          7
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          3
11  AD00012025115D1E4009          6
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          2
14  AD00012025115D1E4006          3
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          2
17  AD00012025115D1E4003          0
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          1

In [173]:
# 지명수 함수에선 student_code로 반환되므로 USER_TESTING_NO 병합하여 추가해야함
merge_df = df.loc[:, ['target_code', 'user_testing_no']].copy()
merge_df.rename(columns={'target_code':'student_code'}, inplace=True)
# merge_df에서 중복된 데이터 제거
merge_df = merge_df.drop_duplicates(subset=['student_code', 'user_testing_no'])
print(merge_df)

             student_code       user_testing_no
0    AD00012025115D1E4020  8916207158814a67abc2
10   AD00012025115D1E4019  a28c9553672c4f54ad7d
20   AD00012025115D1E4018  157327d769394633811f
35   AD00012025115D1E4017  d163f8c83ef64c50aa87
46   AD00012025115D1E4016  ac181f9b8eaa426cb4c8
57   AD00012025115D1E4015  72559204bbdf448b912f
68   AD00012025115D1E4014  30aa23408f104d1293a4
85   AD00012025115D1E4013  4f3f46fc2d2244758a78
97   AD00012025115D1E4012  dc9998566c234f0599c3
111  AD00012025115D1E4011  1eb4ec746358472a9a97
123  AD00012025115D1E4010  a511507acce04b908351
139  AD00012025115D1E4009  14c8df44e4004885a5e0
150  AD00012025115D1E4008  1d49e9937ff141f98e40
159  AD00012025115D1E4007  083269d802e940ce95be
170  AD00012025115D1E4006  e0cebb8191764f41a106
189  AD00012025115D1E4005  bd5e577fd48840d6bd34
198  AD00012025115D1E4004  521595a387b449f8b55d
211  AD00012025115D1E4003  59237a4bfe5b46189c25
225  AD00012025115D1E4002  62dfbfb230e1497c963a
234  AD00012025115D1E4001  5021a196f7c74c81a151

In [174]:
# 최종 결과 병합
final_df = pd.merge(n12_point_df, merge_df, on='student_code', how='inner')
print(final_df)
# 자기보고 문항 점수 병합
final_df = pd.merge(final_df, participation_learning_df, left_on='user_testing_no', right_on='USER_TESTING_NO', how='inner')
print(final_df)

            student_code  num_point       user_testing_no
0   AD00012025115D1E4020          2  8916207158814a67abc2
1   AD00012025115D1E4019          0  a28c9553672c4f54ad7d
2   AD00012025115D1E4018          4  157327d769394633811f
3   AD00012025115D1E4017          0  d163f8c83ef64c50aa87
4   AD00012025115D1E4016          8  ac181f9b8eaa426cb4c8
5   AD00012025115D1E4015          0  72559204bbdf448b912f
6   AD00012025115D1E4014          0  30aa23408f104d1293a4
7   AD00012025115D1E4013          4  4f3f46fc2d2244758a78
8   AD00012025115D1E4012          7  dc9998566c234f0599c3
9   AD00012025115D1E4011          0  1eb4ec746358472a9a97
10  AD00012025115D1E4010          3  a511507acce04b908351
11  AD00012025115D1E4009          6  14c8df44e4004885a5e0
12  AD00012025115D1E4008          0  1d49e9937ff141f98e40
13  AD00012025115D1E4007          2  083269d802e940ce95be
14  AD00012025115D1E4006          3  e0cebb8191764f41a106
15  AD00012025115D1E4005          0  bd5e577fd48840d6bd34
16  AD00012025115D1E4004          2  521595a387b449f8b55d
17  AD00012025115D1E4003          0  59237a4bfe5b46189c25
18  AD00012025115D1E4002          0  62dfbfb230e1497c963a
19  AD00012025115D1E4001          1  5021a196f7c74c81a151
            student_code  num_point       user_testing_no  \
0   AD00012025115D1E4020          2  8916207158814a67abc2
1   AD00012025115D1E4019          0  a28c9553672c4f54ad7d
2   AD00012025115D1E4018          4  157327d769394633811f
3   AD00012025115D1E4017          0  d163f8c83ef64c50aa87
4   AD00012025115D1E4016          8  ac181f9b8eaa426cb4c8
5   AD00012025115D1E4015          0  72559204bbdf448b912f
6   AD00012025115D1E4014          0  30aa23408f104d1293a4
7   AD00012025115D1E4013          4  4f3f46fc2d2244758a78
8   AD00012025115D1E4012          7  dc9998566c234f0599c3
9   AD00012025115D1E4011          0  1eb4ec746358472a9a97
10  AD00012025115D1E4010          3  a511507acce04b908351
11  AD00012025115D1E4009          6  14c8df44e4004885a5e0
12  AD00012025115D1E4008          0  1d49e9937ff141f98e40
13  AD00012025115D1E4007          2  083269d802e940ce95be
14  AD00012025115D1E4006          3  e0cebb8191764f41a106
15  AD00012025115D1E4005          0  bd5e577fd48840d6bd34
16  AD00012025115D1E4004          2  521595a387b449f8b55d
17  AD00012025115D1E4003          0  59237a4bfe5b46189c25
18  AD00012025115D1E4002          0  62dfbfb230e1497c963a
19  AD00012025115D1E4001          1  5021a196f7c74c81a151

         USER_TESTING_NO  q45  q46  q47  q48  q49  q50  q51  q52  q53  q54  \
0   8916207158814a67abc2    2    1    3    5    1    4    3    4    3    4
1   a28c9553672c4f54ad7d    1    4    3    3    3    2    1    1    2    4
2   157327d769394633811f    2    1    2    2    3    3    3    3    5    3
3   d163f8c83ef64c50aa87    1    3    1    2    1    2    2    3    3    1
4   ac181f9b8eaa426cb4c8    4    5    4    3    4    3    5    5    5    1
5   72559204bbdf448b912f    3    2    4    3    3    2    1    3    2    4
6   30aa23408f104d1293a4    5    5    5    5    3    2    3    3    2    2
7   4f3f46fc2d2244758a78    2    1    2    3    2    3    5    5    2    4
8   dc9998566c234f0599c3    1    5    2    3    3    5    2    3    3    2
9   1eb4ec746358472a9a97    2    5    3    4    5    3    3    1    3    3
10  a511507acce04b908351    1    3    5    2    2    3    1    1    1    2
11  14c8df44e4004885a5e0    5    1    2    3    3    4    3    4    4    5
12  1d49e9937ff141f98e40    1    1    1    2    4    5    2    3    3    1
13  083269d802e940ce95be    5    5    3    3    3    5    5    3    3    5
14  e0cebb8191764f41a106    2    1    3    2    2    3    1    1    2    1
15  bd5e577fd48840d6bd34    1    3    1    3    4    4    3    3    3    3
16  521595a387b449f8b55d    4    5    4    5    5    3    5    4    5    5
17  59237a4bfe5b46189c25    3    3    3    1    1    1    1    1    1    1
18  62dfbfb230e1497c963a    3    3    4    5    5    2    3    4    3    5
19  5021a196f7c74c81a151    5    5    3    3    5    3    3    5    3    1

    participation_learning_point
0                            3.0
1                            2.4
2                            2.7
3                            1.9
4                            3.9
5                            2.7
6                            3.5
7                            2.9
8                            2.9
9                            3.2
10                           2.1
11                           3.4
12                           2.3
13                           4.0
14                           1.8
15                           2.8
16                           4.5
17                           1.6
18                           3.7
19                           3.6

In [175]:
final_df['participation_learning_product'] = final_df['num_point'] * final_df['participation_learning_point']
final_df

,student_code,num_point,user_testing_no,USER_TESTING_NO,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,participation_learning_point,participation_learning_product
0,AD00012025115D1E4020,2,8916207158814a67abc2,8916207158814a67abc2,2,1,3,5,1,4,3,4,3,4,3.0,6.0
1,AD00012025115D1E4019,0,a28c9553672c4f54ad7d,a28c9553672c4f54ad7d,1,4,3,3,3,2,1,1,2,4,2.4,0.0
2,AD00012025115D1E4018,4,157327d769394633811f,157327d769394633811f,2,1,2,2,3,3,3,3,5,3,2.7,10.8
3,AD00012025115D1E4017,0,d163f8c83ef64c50aa87,d163f8c83ef64c50aa87,1,3,1,2,1,2,2,3,3,1,1.9,0.0
4,AD00012025115D1E4016,8,ac181f9b8eaa426cb4c8,ac181f9b8eaa426cb4c8,4,5,4,3,4,3,5,5,5,1,3.9,31.2
5,AD00012025115D1E4015,0,72559204bbdf448b912f,72559204bbdf448b912f,3,2,4,3,3,2,1,3,2,4,2.7,0.0
6,AD00012025115D1E4014,0,30aa23408f104d1293a4,30aa23408f104d1293a4,5,5,5,5,3,2,3,3,2,2,3.5,0.0
7,AD00012025115D1E4013,4,4f3f46fc2d2244758a78,4f3f46fc2d2244758a78,2,1,2,3,2,3,5,5,2,4,2.9,11.6
8,AD00012025115D1E4012,7,dc9998566c234f0599c3,dc9998566c234f0599c3,1,5,2,3,3,5,2,3,3,2,2.9,20.3
9,AD00012025115D1E4011,0,1eb4ec746358472a9a97,1eb4ec746358472a9a97,2,5,3,4,5,3,3,1,3,3,3.2,0.0
10,AD00012025115D1E4010,3,a511507acce04b908351,a511507acce04b908351,1,3,5,2,2,3,1,1,1,2,2.1,6.3
11,AD00012025115D1E4009,6,14c8df44e4004885a5e0,14c8df44e4004885a5e0,5,1,2,3,3,4,3,4,4,5,3.4,20.4
12,AD00012025115D1E4008,0,1d49e9937ff141f98e40,1d49e9937ff141f98e40,1,1,1,2,4,5,2,3,3,1,2.3,0.0
13,AD00012025115D1E4007,2,083269d802e940ce95be,083269d802e940ce95be,5,5,3,3,3,5,5,3,3,5,4.0,8.0
14,AD00012025115D1E4006,3,e0cebb8191764f41a106,e0cebb8191764f41a106,2,1,3,2,2,3,1,1,2,1,1.8,5.4
15,AD00012025115D1E4005,0,bd5e577fd48840d6bd34,bd5e577fd48840d6bd34,1,3,1,3,4,4,3,3,3,3,2.8,0.0
16,AD00012025115D1E4004,2,521595a387b449f8b55d,521595a387b449f8b55d,4,5,4,5,5,3,5,4,5,5,4.5,9.0
17,AD00012025115D1E4003,0,59237a4bfe5b46189c25,59237a4bfe5b46189c25,3,3,3,1,1,1,1,1,1,1,1.6,0.0
18,AD00012025115D1E4002,0,62dfbfb230e1497c963a,62dfbfb230e1497c963a,3,3,4,5,5,2,3,4,3,5,3.7,0.0
19,AD00012025115D1E4001,1,5021a196f7c74c81a151,5021a196f7c74c81a151,5,5,3,3,5,3,3,5,3,1,3.6,3.6

In [177]:
def participation_learning_norm(df, celling_parameter=67) :
    df.sort_values(by='participation_learning_product', ascending=False, inplace=True)
    top5_df = df.head(5)
    top5_mean = top5_df['participation_learning_product'].mean()
    total_mean = df['participation_learning_product'].mean()
    weighted_mean = 0.4 * (top5_mean) + 0.6 * (total_mean)
    weighted_mean = 4 * ((min(max(weighted_mean, 0), celling_parameter)-0)/celling_parameter)+1
    result_df = pd.DataFrame({'psy_code': [psy_code], 'top5_mean': [top5_mean], 'total_mean': [total_mean], 'weighted_mean': [weighted_mean]})
    result_df['reg_date'] = pd.Timestamp.now()
    result_df['purpose'] = f'"purpose=calibration;celling_parameter={celling_parameter};author=Yumin"'
    return result_df
result_df = participation_learning_norm(final_df)
print(result_df)

        psy_code  top5_mean  total_mean  weighted_mean  \
0  P202511122059      18.86        6.63       1.687881

                    reg_date  \
0 2025-11-17 13:36:12.496765

                                             purpose
0  "purpose=calibration;celling_parameter=67;auth...

## 지위위계

In [178]:
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]

In [179]:
count_point_df, psy_code = count_point(query_df, query_df['target_code'].unique().tolist(), [1])
print(count_point_df)

            student_code  num_point
0   AD00012025115D1E4020          5
1   AD00012025115D1E4019          0
2   AD00012025115D1E4018          2
3   AD00012025115D1E4017          0
4   AD00012025115D1E4016          7
5   AD00012025115D1E4015          0
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          7
8   AD00012025115D1E4012          7
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          6
11  AD00012025115D1E4009          7
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          1
14  AD00012025115D1E4006          4
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          0
17  AD00012025115D1E4003          1
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          2

In [180]:
def gini(count_point_df) :
    point_mean = count_point_df['num_point'].mean()
    print(f'지명수 평균 : {point_mean}')
    n = len(count_point_df)
    print(f'학생 수 : {n}')
    abs_diff_list = []
    for point in count_point_df['num_point'] :
        abs_diff = abs(point - point_mean)
        abs_diff_list.append(abs_diff)
    abs_diff_sum = sum(abs_diff_list)
    print(f'절대차 합계 : {abs_diff_sum}')
    gini = abs_diff_sum / (2 * n * point_mean)
    print(f'지위위계 Gini 계수 : {gini}')
    gini_normalization = 4 * ((min(max(gini, 0), 0.6) - 0)/ 0.6) +1
    return gini_normalization

gini_normalization = gini(count_point_df)
print(f'학급 분위기_지위위계 : {gini_normalization}')

지명수 평균 : 2.45
학생 수 : 20
절대차 합계 : 51.70000000000001
지위위계 Gini 계수 : 0.5275510204081634
학급 분위기_지위위계 : 4.51700680272109

In [182]:
def gini(count_point_df) :
    point_mean = count_point_df['num_point'].mean()
    print(f'지명수 평균 : {point_mean}')
    n = len(count_point_df)
    print(f'학생 수 : {n}')
    abs_diff_list = []
    for i in count_point_df['num_point'] :
        for j in count_point_df['num_point'] :
            if i != j:
                abs_diff = abs(i - j)
                abs_diff_list.append(abs_diff)            
            else :
                pass
    abs_diff_sum = sum(abs_diff_list)
    print(f'절대차 합계 : {abs_diff_sum}')
    gini = abs_diff_sum / (2 * n * n * point_mean)
    print(f'지위위계 Gini 계수 : {gini}')
    gini_normalization = 4 * ((min(max(gini, 0), 0.6) - 0)/ 0.6) +1
    return gini_normalization

gini_normalization = gini(count_point_df)
print(f'학급 분위기_지위위계 : {gini_normalization}')

지명수 평균 : 2.45
학생 수 : 20
절대차 합계 : 1206
지위위계 Gini 계수 : 0.6153061224489795
학급 분위기_지위위계 : 5.0