# 보이지 않는 손

## 일치율

### 데이터 추출

In [1]:
import pandas as pd
import numpy as np
import sys
print(sys.executable)   # 예: C:\ProgramData\anaconda3\python.exe
print(sys.path)         # 패키지 탐색 경로(여기에 site-packages가 있어야 import 가능)

import awswrangler as wr
query_df = wr.athena.read_sql_query(
    """
    select a.school_code, a.school_name, b.school_grade, b.school_num, b.class_name, c.psy_name, c.psy_code, c.close_yn, f.student_num, d.target_code, e.user_testing_no, e.question_no, e.student_code 
    from school_info a
    inner join school_class b on a.school_code = b.school_code
    inner join psy_class c on b.class_code = c.class_code
    inner join psy_target_detail d on c.class_code = d.class_code and c.psy_code = d.psy_code
    inner join at_user_testing_paper_pn e on d.user_testing_no = e.user_testing_no
    inner join school_student f on d.target_code = f.student_code and d.class_code = f.class_code
    where c.close_yn = 'Y' and e.question_no in (1,2,4,5,6,7,8,9,10,11)
    and d.psy_code = 'P202511122059'
    """
    , database="schoolfriends-kmj"
)
query_df['user_testing_no'] = query_df['user_testing_no'].str.replace('"', '')
# 검수하고자 하는 평가명 필터링
df = query_df[query_df['psy_name'].str.contains('25년 11월_1차')]
print(df)

c:\ProgramData\anaconda3\python.exe
['c:\\ProgramData\\anaconda3\\python313.zip', 'c:\\ProgramData\\anaconda3\\DLLs', 'c:\\ProgramData\\anaconda3\\Lib', 'c:\\ProgramData\\anaconda3', '', 'C:\\Users\\USER\\AppData\\Roaming\\Python\\Python313\\site-packages', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\win32', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\win32\\lib', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\Pythonwin']
    school_code school_name  school_grade  school_num class_name  \
0        AD0001       학지중학교          <NA>        <NA>         ""
1        AD0001       학지중학교          <NA>        <NA>         ""
2        AD0001       학지중학교          <NA>        <NA>         ""
3        AD0001       학지중학교          <NA>        <NA>         ""
4        AD0001       학지중학교          <NA>        <NA>         ""
..          ...         ...           ...         ...        ...
426      AD0001       학지중학교          <NA>        <NA>         ""
427      AD0001       학지중학교          <NA>        <NA>         ""
428      AD0001       학지중학교          <NA>        <NA>         ""
429      AD0001       학지중학교          <NA>        <NA>         ""
430      AD0001       학지중학교          <NA>        <NA>         ""

         psy_name       psy_code close_yn  student_num           target_code  \
0    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
1    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
2    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
3    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
4    "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4020
..            ...            ...      ...          ...                   ...
426  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
427  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
428  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
429  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001
430  "25년 11월_1차"  P202511122059        Y         <NA>  AD00012025115D1E4001

          user_testing_no  question_no          student_code
0    8916207158814a67abc2            1  AD00012025115D1E4010
1    8916207158814a67abc2            1  AD00012025115D1E4016
2    8916207158814a67abc2            2  AD00012025115D1E4004
3    8916207158814a67abc2            2  AD00012025115D1E4007
4    8916207158814a67abc2            2  AD00012025115D1E4009
..                    ...          ...                   ...
426  5021a196f7c74c81a151            9  AD00012025115D1E4019
427  5021a196f7c74c81a151           10  AD00012025115D1E4012
428  5021a196f7c74c81a151           10  AD00012025115D1E4015
429  5021a196f7c74c81a151           11  AD00012025115D1E4012
430  5021a196f7c74c81a151           11  AD00012025115D1E4017

[431 rows x 13 columns]

In [7]:
import awswrangler as wr
query_df = wr.athena.read_sql_query(
    """
    select * 
    from psy_target_detail
    where psy_code = 'P202511122059'
    """
    , database="schoolfriends-kmj"
)
query_df['user_testing_no'] = query_df['user_testing_no'].str.replace('"', '')
# 검수하고자 하는 평가명 필터링
query_df.loc[query_df['psy_target'] == 'TEACHER', :]

,psy_code,class_code,target_code,psy_target,at_status_cd,pn_check,sr_check,sct_check,tr_check,user_testing_no,reg_member_no,reg_date,mod_member_no,mod_date
20,P202511122059,AD00012025115D1E4,M10000240,TEACHER,<NA>,N,Y,N,Y,e91d62e3680c4cf9bd7a,M10000240,"""2025-11-13 13:24:17""",,

In [11]:
teacher_user_testing_no = query_df[query_df['psy_target'] == 'TEACHER']['user_testing_no'].values.tolist()
teacher_user_testing_no

['e91d62e3680c4cf9bd7a']

In [12]:
import awswrangler as wr
query_df = wr.athena.read_sql_query(
    """
    select * 
    from at_user_testing_paper_tr
    where user_testing_no = 'e91d62e3680c4cf9bd7a'
    """
    , database="schoolfriends-kmj"
)
query_df
#! ....... select_data 누락되어서 들어감....

,user_testing_no,question_no,student_code,select_data,reg_date
0,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4001,<NA>,"""2025-11-13 13:24:57"""
1,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4002,<NA>,"""2025-11-13 13:24:57"""
2,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4003,<NA>,"""2025-11-13 13:24:57"""
3,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4004,<NA>,"""2025-11-13 13:24:57"""
4,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4005,<NA>,"""2025-11-13 13:24:57"""
...,...,...,...,...,...
195,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4016,<NA>,"""2025-11-13 13:24:57"""
196,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4017,<NA>,"""2025-11-13 13:24:57"""
197,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4018,<NA>,"""2025-11-13 13:24:57"""
198,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4019,<NA>,"""2025-11-13 13:24:57"""
199,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4020,<NA>,"""2025-11-13 13:24:57"""

In [13]:
# 디비버에서 직접 쿼리해서 가지고 옴
query_df = pd.read_csv('AT_USER_TESTING_PAPER_TR_202511171701.csv')
query_df

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE
0,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4001,1,2025-11-13 13:24:57
1,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4002,3,2025-11-13 13:24:57
2,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4003,2,2025-11-13 13:24:57
3,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4004,1,2025-11-13 13:24:57
4,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4005,3,2025-11-13 13:24:57
...,...,...,...,...,...
195,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4016,4,2025-11-13 13:24:57
196,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4017,4,2025-11-13 13:24:57
197,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4018,5,2025-11-13 13:24:57
198,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4019,5,2025-11-13 13:24:57
199,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4020,5,2025-11-13 13:24:57

### 인기

In [26]:
# 교사 학생 평가 문항 2번
tr_df = query_df.loc[query_df['QUESTION_NO'] == 1, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std()
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2165074472.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std()
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2165074472.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
0,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4001,1,2025-11-13 13:24:57,-1.101075,1
1,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4002,3,2025-11-13 13:24:57,0.417649,4
2,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4003,2,2025-11-13 13:24:57,-0.341713,2
3,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4004,1,2025-11-13 13:24:57,-1.101075,1
4,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4005,3,2025-11-13 13:24:57,0.417649,4
5,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4006,1,2025-11-13 13:24:57,-1.101075,1
6,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4007,2,2025-11-13 13:24:57,-0.341713,2
7,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4008,4,2025-11-13 13:24:57,1.177012,5
8,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4009,1,2025-11-13 13:24:57,-1.101075,1
9,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4010,2,2025-11-13 13:24:57,-0.341713,2
10,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4011,3,2025-11-13 13:24:57,0.417649,4
11,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4012,3,2025-11-13 13:24:57,0.417649,4
12,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4013,5,2025-11-13 13:24:57,1.936374,5
13,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4014,2,2025-11-13 13:24:57,-0.341713,2
14,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4015,1,2025-11-13 13:24:57,-1.101075,1
15,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4016,5,2025-11-13 13:24:57,1.936374,5
16,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4017,3,2025-11-13 13:24:57,0.417649,4
17,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4018,4,2025-11-13 13:24:57,1.177012,5
18,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4019,2,2025-11-13 13:24:57,-0.341713,2
19,e91d62e3680c4cf9bd7a,1,AD00012025115D1E4020,1,2025-11-13 13:24:57,-1.101075,1

In [27]:
# 인기 지명 문항 1번
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]
student_list = df['target_code'].unique().tolist()
count_point_df, psy_code = count_point(df, student_list, [1])
print(count_point_df)

            student_code  num_point
0   AD00012025115D1E4020          5
1   AD00012025115D1E4019          0
2   AD00012025115D1E4018          2
3   AD00012025115D1E4017          0
4   AD00012025115D1E4016          7
5   AD00012025115D1E4015          0
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          7
8   AD00012025115D1E4012          7
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          6
11  AD00012025115D1E4009          7
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          1
14  AD00012025115D1E4006          4
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          0
17  AD00012025115D1E4003          1
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          2

In [28]:
mean = count_point_df['num_point'].mean()
std = count_point_df['num_point'].std(ddof=0)
count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
print(count_point_df)

            student_code  num_point       z점수  정규화
0   AD00012025115D1E4020          5  0.893363    5
1   AD00012025115D1E4019          0 -0.858329    1
2   AD00012025115D1E4018          2 -0.157652    3
3   AD00012025115D1E4017          0 -0.858329    1
4   AD00012025115D1E4016          7  1.594040    5
5   AD00012025115D1E4015          0 -0.858329    1
6   AD00012025115D1E4014          0 -0.858329    1
7   AD00012025115D1E4013          7  1.594040    5
8   AD00012025115D1E4012          7  1.594040    5
9   AD00012025115D1E4011          0 -0.858329    1
10  AD00012025115D1E4010          6  1.243702    5
11  AD00012025115D1E4009          7  1.594040    5
12  AD00012025115D1E4008          0 -0.858329    1
13  AD00012025115D1E4007          1 -0.507991    2
14  AD00012025115D1E4006          4  0.543025    4
15  AD00012025115D1E4005          0 -0.858329    1
16  AD00012025115D1E4004          0 -0.858329    1
17  AD00012025115D1E4003          1 -0.507991    2
18  AD00012025115D1E4002          0 -0.858329    1
19  AD00012025115D1E4001          2 -0.157652    3

In [ ]:
## 일치율 산출 참고용
# def calculate_euclidean_distance_between_peer_nomination_and_student_evaluation(calculate_scale_scores_by_peer_nomination_df, calculate_scale_scores_by_student_evaluation_df) :
#     """
#     또래지명 척도별 점수와 학생평가 척도별 점수 간의 유클리드 거리를 계산하는 함수
#     """
#     euclidean_list = []
#     for idx in range(1,len(calculate_scale_scores_by_peer_nomination_df.columns)):
#         a_list = calculate_scale_scores_by_peer_nomination_df.iloc[:, idx]
#         b_list = calculate_scale_scores_by_student_evaluation_df.iloc[:, idx]
#         diff_list = []
#         for a, b in zip(a_list, b_list) :
#             diff = a - b
#             diff_list.append(diff)
#         squ_list = [i**2 for i in diff_list]
#         sum_value = sum(squ_list)
#         root_value = sum_value**0.5
#         max_value = (len(calculate_scale_scores_by_peer_nomination_df)*16)**0.5
#         euclidean_value = (1-(root_value/max_value))*100
#         euclidean_value = max(0, euclidean_value)
#         euclidean_list.append(euclidean_value)
#     return pd.DataFrame({
#         '척도' : list(calculate_scale_scores_by_peer_nomination_df.columns[1:]),
#         '일치율' : euclidean_list
#     })

In [30]:
count_point_df.sort_values('student_code', inplace=True)
tr_df.sort_values('STUDENT_CODE', inplace=True)
a_list = count_point_df['정규화'].to_list()
b_list = tr_df['정규화'].to_list()
diff_list = []
for a, b in zip(a_list, b_list) :
    diff = a - b
    diff_list.append(diff)
squ_list = [i**2 for i in diff_list]
sum_value = sum(squ_list)
root_value = sum_value**0.5
max_value = (len(a_list)*16)**0.5
euclidean_value = (1-(root_value/max_value))*100
euclidean_value = max(0, euclidean_value)
print(euclidean_value)

40.57567837997643

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2226412524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 선호

In [35]:
# 교사 학생 평가 문항 2번
tr_df = query_df.loc[query_df['QUESTION_NO'] == 3, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3476889625.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3476889625.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
40,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4001,1,2025-11-13 13:24:57,-1.245682,1
41,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4002,3,2025-11-13 13:24:57,0.415227,4
42,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4003,2,2025-11-13 13:24:57,-0.415227,2
43,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4004,5,2025-11-13 13:24:57,2.076137,5
44,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4005,1,2025-11-13 13:24:57,-1.245682,1
45,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4006,3,2025-11-13 13:24:57,0.415227,4
46,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4007,4,2025-11-13 13:24:57,1.245682,5
47,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4008,3,2025-11-13 13:24:57,0.415227,4
48,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4009,2,2025-11-13 13:24:57,-0.415227,2
49,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4010,1,2025-11-13 13:24:57,-1.245682,1
50,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4011,3,2025-11-13 13:24:57,0.415227,4
51,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4012,1,2025-11-13 13:24:57,-1.245682,1
52,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4013,2,2025-11-13 13:24:57,-0.415227,2
53,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4014,2,2025-11-13 13:24:57,-0.415227,2
54,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4015,3,2025-11-13 13:24:57,0.415227,4
55,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4016,3,2025-11-13 13:24:57,0.415227,4
56,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4017,1,2025-11-13 13:24:57,-1.245682,1
57,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4018,2,2025-11-13 13:24:57,-0.415227,2
58,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4019,5,2025-11-13 13:24:57,2.076137,5
59,e91d62e3680c4cf9bd7a,3,AD00012025115D1E4020,3,2025-11-13 13:24:57,0.415227,4

In [36]:
# 인기 지명 문항 1번
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]
student_list = df['target_code'].unique().tolist()
count_point_df, psy_code = count_point(df, student_list, [2])
print(count_point_df)

            student_code  num_point
0   AD00012025115D1E4020          9
1   AD00012025115D1E4019          0
2   AD00012025115D1E4018          7
3   AD00012025115D1E4017          0
4   AD00012025115D1E4016          3
5   AD00012025115D1E4015          0
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          6
8   AD00012025115D1E4012          4
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          0
11  AD00012025115D1E4009          3
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          3
14  AD00012025115D1E4006          0
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          4
17  AD00012025115D1E4003          0
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          3

In [37]:
mean = count_point_df['num_point'].mean()
std = count_point_df['num_point'].std(ddof=0)
count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
print(count_point_df)

            student_code  num_point       z점수  정규화
0   AD00012025115D1E4020          9  2.555556    5
1   AD00012025115D1E4019          0 -0.777778    2
2   AD00012025115D1E4018          7  1.814815    5
3   AD00012025115D1E4017          0 -0.777778    2
4   AD00012025115D1E4016          3  0.333333    4
5   AD00012025115D1E4015          0 -0.777778    2
6   AD00012025115D1E4014          0 -0.777778    2
7   AD00012025115D1E4013          6  1.444444    5
8   AD00012025115D1E4012          4  0.703704    4
9   AD00012025115D1E4011          0 -0.777778    2
10  AD00012025115D1E4010          0 -0.777778    2
11  AD00012025115D1E4009          3  0.333333    4
12  AD00012025115D1E4008          0 -0.777778    2
13  AD00012025115D1E4007          3  0.333333    4
14  AD00012025115D1E4006          0 -0.777778    2
15  AD00012025115D1E4005          0 -0.777778    2
16  AD00012025115D1E4004          4  0.703704    4
17  AD00012025115D1E4003          0 -0.777778    2
18  AD00012025115D1E4002          0 -0.777778    2
19  AD00012025115D1E4001          3  0.333333    4

In [38]:
count_point_df.sort_values('student_code', inplace=True)
tr_df.sort_values('STUDENT_CODE', inplace=True)
a_list = count_point_df['정규화'].to_list()
b_list = tr_df['정규화'].to_list()
diff_list = []
for a, b in zip(a_list, b_list) :
    diff = a - b
    diff_list.append(diff)
squ_list = [i**2 for i in diff_list]
sum_value = sum(squ_list)
root_value = sum_value**0.5
max_value = (len(a_list)*16)**0.5
euclidean_value = (1-(root_value/max_value))*100
euclidean_value = max(0, euclidean_value)
print(euclidean_value)

51.58770817240729

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2226412524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 선제적 공격성

In [39]:
# 교사 학생 평가 문항 2번
tr_df = query_df.loc[query_df['QUESTION_NO'] == 8, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3779578510.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3779578510.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
140,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4001,2,2025-11-13 13:24:57,-1.008368,1
141,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4002,1,2025-11-13 13:24:57,-1.925067,1
142,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4003,3,2025-11-13 13:24:57,-0.091670,3
143,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4004,4,2025-11-13 13:24:57,0.825029,4
144,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4005,2,2025-11-13 13:24:57,-1.008368,1
145,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4006,5,2025-11-13 13:24:57,1.741727,5
146,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4007,4,2025-11-13 13:24:57,0.825029,4
147,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4008,4,2025-11-13 13:24:57,0.825029,4
148,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4009,3,2025-11-13 13:24:57,-0.091670,3
149,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4010,1,2025-11-13 13:24:57,-1.925067,1
150,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4011,2,2025-11-13 13:24:57,-1.008368,1
151,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4012,4,2025-11-13 13:24:57,0.825029,4
152,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4013,3,2025-11-13 13:24:57,-0.091670,3
153,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4014,4,2025-11-13 13:24:57,0.825029,4
154,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4015,4,2025-11-13 13:24:57,0.825029,4
155,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4016,4,2025-11-13 13:24:57,0.825029,4
156,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4017,4,2025-11-13 13:24:57,0.825029,4
157,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4018,3,2025-11-13 13:24:57,-0.091670,3
158,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4019,2,2025-11-13 13:24:57,-1.008368,1
159,e91d62e3680c4cf9bd7a,8,AD00012025115D1E4020,3,2025-11-13 13:24:57,-0.091670,3

In [40]:
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]
student_list = df['target_code'].unique().tolist()
count_point_df, psy_code = count_point(df, student_list, [4])
print(count_point_df)

            student_code  num_point
0   AD00012025115D1E4020          2
1   AD00012025115D1E4019          5
2   AD00012025115D1E4018          0
3   AD00012025115D1E4017          1
4   AD00012025115D1E4016          0
5   AD00012025115D1E4015          0
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          0
8   AD00012025115D1E4012          2
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          4
11  AD00012025115D1E4009          0
12  AD00012025115D1E4008          4
13  AD00012025115D1E4007          0
14  AD00012025115D1E4006          6
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          0
17  AD00012025115D1E4003          8
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          5

In [41]:
mean = count_point_df['num_point'].mean()
std = count_point_df['num_point'].std(ddof=0)
count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
print(count_point_df)

            student_code  num_point       z점수  정규화
0   AD00012025115D1E4020          2  0.060597    3
1   AD00012025115D1E4019          5  1.272533    5
2   AD00012025115D1E4018          0 -0.747360    2
3   AD00012025115D1E4017          1 -0.343382    2
4   AD00012025115D1E4016          0 -0.747360    2
5   AD00012025115D1E4015          0 -0.747360    2
6   AD00012025115D1E4014          0 -0.747360    2
7   AD00012025115D1E4013          0 -0.747360    2
8   AD00012025115D1E4012          2  0.060597    3
9   AD00012025115D1E4011          0 -0.747360    2
10  AD00012025115D1E4010          4  0.868554    5
11  AD00012025115D1E4009          0 -0.747360    2
12  AD00012025115D1E4008          4  0.868554    5
13  AD00012025115D1E4007          0 -0.747360    2
14  AD00012025115D1E4006          6  1.676511    5
15  AD00012025115D1E4005          0 -0.747360    2
16  AD00012025115D1E4004          0 -0.747360    2
17  AD00012025115D1E4003          8  2.484468    5
18  AD00012025115D1E4002          0 -0.747360    2
19  AD00012025115D1E4001          5  1.272533    5

In [42]:
count_point_df.sort_values('student_code', inplace=True)
tr_df.sort_values('STUDENT_CODE', inplace=True)
a_list = count_point_df['정규화'].to_list()
b_list = tr_df['정규화'].to_list()
diff_list = []
for a, b in zip(a_list, b_list) :
    diff = a - b
    diff_list.append(diff)
squ_list = [i**2 for i in diff_list]
sum_value = sum(squ_list)
root_value = sum_value**0.5
max_value = (len(a_list)*16)**0.5
euclidean_value = (1-(root_value/max_value))*100
euclidean_value = max(0, euclidean_value)
print(euclidean_value)

48.76524617020201

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2226412524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 반응적 공격성

In [43]:
# 교사 학생 평가 문항 2번
tr_df = query_df.loc[query_df['QUESTION_NO'] == 9, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\217395984.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\217395984.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
160,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4001,1,2025-11-13 13:24:57,-1.982937,1
161,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4002,3,2025-11-13 13:24:57,-0.220326,3
162,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4003,5,2025-11-13 13:24:57,1.542284,5
163,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4004,4,2025-11-13 13:24:57,0.660979,4
164,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4005,1,2025-11-13 13:24:57,-1.982937,1
165,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4006,3,2025-11-13 13:24:57,-0.220326,3
166,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4007,4,2025-11-13 13:24:57,0.660979,4
167,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4008,3,2025-11-13 13:24:57,-0.220326,3
168,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4009,3,2025-11-13 13:24:57,-0.220326,3
169,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4010,4,2025-11-13 13:24:57,0.660979,4
170,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4011,3,2025-11-13 13:24:57,-0.220326,3
171,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4012,4,2025-11-13 13:24:57,0.660979,4
172,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4013,5,2025-11-13 13:24:57,1.542284,5
173,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4014,5,2025-11-13 13:24:57,1.542284,5
174,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4015,3,2025-11-13 13:24:57,-0.220326,3
175,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4016,3,2025-11-13 13:24:57,-0.220326,3
176,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4017,2,2025-11-13 13:24:57,-1.101632,1
177,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4018,3,2025-11-13 13:24:57,-0.220326,3
178,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4019,2,2025-11-13 13:24:57,-1.101632,1
179,e91d62e3680c4cf9bd7a,9,AD00012025115D1E4020,4,2025-11-13 13:24:57,0.660979,4

In [44]:
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]
student_list = df['target_code'].unique().tolist()
count_point_df, psy_code = count_point(df, student_list, [5])
print(count_point_df)

            student_code  num_point
0   AD00012025115D1E4020          0
1   AD00012025115D1E4019          3
2   AD00012025115D1E4018          0
3   AD00012025115D1E4017         10
4   AD00012025115D1E4016          1
5   AD00012025115D1E4015          1
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          0
8   AD00012025115D1E4012          0
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          5
11  AD00012025115D1E4009          0
12  AD00012025115D1E4008          4
13  AD00012025115D1E4007          0
14  AD00012025115D1E4006          6
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004          0
17  AD00012025115D1E4003          8
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          1

In [45]:
mean = count_point_df['num_point'].mean()
std = count_point_df['num_point'].std(ddof=0)
count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
print(count_point_df)

            student_code  num_point       z점수  정규화
0   AD00012025115D1E4020          0 -0.655578    2
1   AD00012025115D1E4019          3  0.353004    4
2   AD00012025115D1E4018          0 -0.655578    2
3   AD00012025115D1E4017         10  2.706360    5
4   AD00012025115D1E4016          1 -0.319384    2
5   AD00012025115D1E4015          1 -0.319384    2
6   AD00012025115D1E4014          0 -0.655578    2
7   AD00012025115D1E4013          0 -0.655578    2
8   AD00012025115D1E4012          0 -0.655578    2
9   AD00012025115D1E4011          0 -0.655578    2
10  AD00012025115D1E4010          5  1.025391    5
11  AD00012025115D1E4009          0 -0.655578    2
12  AD00012025115D1E4008          4  0.689197    4
13  AD00012025115D1E4007          0 -0.655578    2
14  AD00012025115D1E4006          6  1.361585    5
15  AD00012025115D1E4005          0 -0.655578    2
16  AD00012025115D1E4004          0 -0.655578    2
17  AD00012025115D1E4003          8  2.033973    5
18  AD00012025115D1E4002          0 -0.655578    2
19  AD00012025115D1E4001          1 -0.319384    2

In [46]:
count_point_df.sort_values('student_code', inplace=True)
tr_df.sort_values('STUDENT_CODE', inplace=True)
a_list = count_point_df['정규화'].to_list()
b_list = tr_df['정규화'].to_list()
diff_list = []
for a, b in zip(a_list, b_list) :
    diff = a - b
    diff_list.append(diff)
squ_list = [i**2 for i in diff_list]
sum_value = sum(squ_list)
root_value = sum_value**0.5
max_value = (len(a_list)*16)**0.5
euclidean_value = (1-(root_value/max_value))*100
euclidean_value = max(0, euclidean_value)
print(euclidean_value)

52.237567063643006

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2226412524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 친사회성

In [47]:
# 교사 학생 평가 문항
tr_df = query_df.loc[query_df['QUESTION_NO'] == 6, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2829714080.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2829714080.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
100,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4001,1,2025-11-13 13:24:57,-1.758854,1
101,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4002,4,2025-11-13 13:24:57,0.535303,4
102,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4003,3,2025-11-13 13:24:57,-0.229416,3
103,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4004,4,2025-11-13 13:24:57,0.535303,4
104,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4005,5,2025-11-13 13:24:57,1.300022,5
105,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4006,4,2025-11-13 13:24:57,0.535303,4
106,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4007,5,2025-11-13 13:24:57,1.300022,5
107,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4008,3,2025-11-13 13:24:57,-0.229416,3
108,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4009,4,2025-11-13 13:24:57,0.535303,4
109,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4010,5,2025-11-13 13:24:57,1.300022,5
110,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4011,5,2025-11-13 13:24:57,1.300022,5
111,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4012,4,2025-11-13 13:24:57,0.535303,4
112,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4013,1,2025-11-13 13:24:57,-1.758854,1
113,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4014,3,2025-11-13 13:24:57,-0.229416,3
114,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4015,2,2025-11-13 13:24:57,-0.994135,1
115,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4016,1,2025-11-13 13:24:57,-1.758854,1
116,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4017,4,2025-11-13 13:24:57,0.535303,4
117,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4018,3,2025-11-13 13:24:57,-0.229416,3
118,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4019,2,2025-11-13 13:24:57,-0.994135,1
119,e91d62e3680c4cf9bd7a,6,AD00012025115D1E4020,3,2025-11-13 13:24:57,-0.229416,3

In [48]:
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]
student_list = df['target_code'].unique().tolist()
count_point_df, psy_code = count_point(df, student_list, [6,7])
print(count_point_df)

            student_code  num_point
0   AD00012025115D1E4020         15
1   AD00012025115D1E4019          1
2   AD00012025115D1E4018         18
3   AD00012025115D1E4017          2
4   AD00012025115D1E4016         13
5   AD00012025115D1E4015          2
6   AD00012025115D1E4014          0
7   AD00012025115D1E4013          0
8   AD00012025115D1E4012         13
9   AD00012025115D1E4011          0
10  AD00012025115D1E4010          0
11  AD00012025115D1E4009          0
12  AD00012025115D1E4008          0
13  AD00012025115D1E4007          3
14  AD00012025115D1E4006          1
15  AD00012025115D1E4005          0
16  AD00012025115D1E4004         13
17  AD00012025115D1E4003          0
18  AD00012025115D1E4002          0
19  AD00012025115D1E4001          0

In [49]:
mean = count_point_df['num_point'].mean()
std = count_point_df['num_point'].std(ddof=0)
count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
print(count_point_df)

            student_code  num_point       z점수  정규화
0   AD00012025115D1E4020         15  1.791774    5
1   AD00012025115D1E4019          1 -0.499079    2
2   AD00012025115D1E4018         18  2.282672    5
3   AD00012025115D1E4017          2 -0.335446    2
4   AD00012025115D1E4016         13  1.464510    5
5   AD00012025115D1E4015          2 -0.335446    2
6   AD00012025115D1E4014          0 -0.662711    2
7   AD00012025115D1E4013          0 -0.662711    2
8   AD00012025115D1E4012         13  1.464510    5
9   AD00012025115D1E4011          0 -0.662711    2
10  AD00012025115D1E4010          0 -0.662711    2
11  AD00012025115D1E4009          0 -0.662711    2
12  AD00012025115D1E4008          0 -0.662711    2
13  AD00012025115D1E4007          3 -0.171814    3
14  AD00012025115D1E4006          1 -0.499079    2
15  AD00012025115D1E4005          0 -0.662711    2
16  AD00012025115D1E4004         13  1.464510    5
17  AD00012025115D1E4003          0 -0.662711    2
18  AD00012025115D1E4002          0 -0.662711    2
19  AD00012025115D1E4001          0 -0.662711    2

In [50]:
count_point_df.sort_values('student_code', inplace=True)
tr_df.sort_values('STUDENT_CODE', inplace=True)
a_list = count_point_df['정규화'].to_list()
b_list = tr_df['정규화'].to_list()
diff_list = []
for a, b in zip(a_list, b_list) :
    diff = a - b
    diff_list.append(diff)
squ_list = [i**2 for i in diff_list]
sum_value = sum(squ_list)
root_value = sum_value**0.5
max_value = (len(a_list)*16)**0.5
euclidean_value = (1-(root_value/max_value))*100
euclidean_value = max(0, euclidean_value)
print(euclidean_value)

50.0

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2226412524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 가해

In [51]:
# 교사 학생 평가 문항 2번
tr_df = query_df.loc[query_df['QUESTION_NO'] == 4, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\1658860631.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\1658860631.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
60,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4001,1,2025-11-13 13:24:57,-1.205199,1
61,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4002,3,2025-11-13 13:24:57,0.457144,4
62,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4003,5,2025-11-13 13:24:57,2.119488,5
63,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4004,4,2025-11-13 13:24:57,1.288316,5
64,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4005,3,2025-11-13 13:24:57,0.457144,4
65,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4006,4,2025-11-13 13:24:57,1.288316,5
66,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4007,1,2025-11-13 13:24:57,-1.205199,1
67,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4008,3,2025-11-13 13:24:57,0.457144,4
68,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4009,4,2025-11-13 13:24:57,1.288316,5
69,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4010,1,2025-11-13 13:24:57,-1.205199,1
70,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4011,2,2025-11-13 13:24:57,-0.374027,2
71,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4012,1,2025-11-13 13:24:57,-1.205199,1
72,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4013,1,2025-11-13 13:24:57,-1.205199,1
73,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4014,2,2025-11-13 13:24:57,-0.374027,2
74,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4015,2,2025-11-13 13:24:57,-0.374027,2
75,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4016,3,2025-11-13 13:24:57,0.457144,4
76,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4017,1,2025-11-13 13:24:57,-1.205199,1
77,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4018,3,2025-11-13 13:24:57,0.457144,4
78,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4019,2,2025-11-13 13:24:57,-0.374027,2
79,e91d62e3680c4cf9bd7a,4,AD00012025115D1E4020,3,2025-11-13 13:24:57,0.457144,4

In [52]:
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]
student_list = df['target_code'].unique().tolist()
count_point_df, psy_code = count_point(df, student_list, [8,9])
mean = count_point_df['num_point'].mean()
std = count_point_df['num_point'].std(ddof=0)
count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
print(count_point_df)

            student_code  num_point       z점수  정규화
0   AD00012025115D1E4020          1 -0.641218    2
1   AD00012025115D1E4019         15  1.631453    5
2   AD00012025115D1E4018          1 -0.641218    2
3   AD00012025115D1E4017          0 -0.803551    2
4   AD00012025115D1E4016          0 -0.803551    2
5   AD00012025115D1E4015          1 -0.641218    2
6   AD00012025115D1E4014          1 -0.641218    2
7   AD00012025115D1E4013         15  1.631453    5
8   AD00012025115D1E4012          1 -0.641218    2
9   AD00012025115D1E4011          0 -0.803551    2
10  AD00012025115D1E4010         15  1.631453    5
11  AD00012025115D1E4009          9  0.657451    4
12  AD00012025115D1E4008          7  0.332784    4
13  AD00012025115D1E4007          1 -0.641218    2
14  AD00012025115D1E4006         12  1.144452    5
15  AD00012025115D1E4005          1 -0.641218    2
16  AD00012025115D1E4004          0 -0.803551    2
17  AD00012025115D1E4003         17  1.956120    5
18  AD00012025115D1E4002          0 -0.803551    2
19  AD00012025115D1E4001          2 -0.478884    2

In [53]:
count_point_df.sort_values('student_code', inplace=True)
tr_df.sort_values('STUDENT_CODE', inplace=True)
a_list = count_point_df['정규화'].to_list()
b_list = tr_df['정규화'].to_list()
diff_list = []
for a, b in zip(a_list, b_list) :
    diff = a - b
    diff_list.append(diff)
squ_list = [i**2 for i in diff_list]
sum_value = sum(squ_list)
root_value = sum_value**0.5
max_value = (len(a_list)*16)**0.5
euclidean_value = (1-(root_value/max_value))*100
euclidean_value = max(0, euclidean_value)
print(euclidean_value)

51.58770817240729

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2226412524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 피해

In [54]:
# 교사 학생 평가 문항
tr_df = query_df.loc[query_df['QUESTION_NO'] == 5, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3394117874.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3394117874.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
80,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4001,3,2025-11-13 13:24:57,0.359211,4
81,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4002,1,2025-11-13 13:24:57,-1.436842,1
82,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4003,4,2025-11-13 13:24:57,1.257237,5
83,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4004,5,2025-11-13 13:24:57,2.155264,5
84,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4005,4,2025-11-13 13:24:57,1.257237,5
85,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4006,1,2025-11-13 13:24:57,-1.436842,1
86,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4007,3,2025-11-13 13:24:57,0.359211,4
87,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4008,1,2025-11-13 13:24:57,-1.436842,1
88,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4009,2,2025-11-13 13:24:57,-0.538816,2
89,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4010,3,2025-11-13 13:24:57,0.359211,4
90,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4011,2,2025-11-13 13:24:57,-0.538816,2
91,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4012,2,2025-11-13 13:24:57,-0.538816,2
92,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4013,3,2025-11-13 13:24:57,0.359211,4
93,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4014,1,2025-11-13 13:24:57,-1.436842,1
94,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4015,3,2025-11-13 13:24:57,0.359211,4
95,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4016,2,2025-11-13 13:24:57,-0.538816,2
96,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4017,2,2025-11-13 13:24:57,-0.538816,2
97,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4018,3,2025-11-13 13:24:57,0.359211,4
98,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4019,3,2025-11-13 13:24:57,0.359211,4
99,e91d62e3680c4cf9bd7a,5,AD00012025115D1E4020,4,2025-11-13 13:24:57,1.257237,5

In [55]:
# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    import pandas as pd
    if df['psy_code'].nunique() > 1 :
        raise ValueError('psy_code 컬럼에 여러 값이 존재합니다.')
    else :
        temp_df = df[df['question_no'].isin(item_no)] # 해당 문항 필터링
        count_list = []
        for student in student_list :
            if len(temp_df[temp_df['student_code']==student]) >= 1 :
                freq = len(temp_df[temp_df['student_code']==student])
            elif len(temp_df[temp_df['student_code']==student]) == 0 :
                freq = 0
            count_list.append(freq)
        count_point_df = pd.DataFrame({'student_code': student_list, 'num_point': count_list})
        return count_point_df, df['psy_code'].iloc[0]

# 학생 리스트 구하는 함수
def student_list(df) :
    student_list = df['target_code'].unique().tolist()
    return student_list, df['psy_code'].iloc[0]
student_list = df['target_code'].unique().tolist()
count_point_df, psy_code = count_point(df, student_list, [10,11])
mean = count_point_df['num_point'].mean()
std = count_point_df['num_point'].std(ddof=0)
count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
print(count_point_df)

            student_code  num_point       z점수  정규화
0   AD00012025115D1E4020          0 -0.669456    2
1   AD00012025115D1E4019          0 -0.669456    2
2   AD00012025115D1E4018         16  1.880851    5
3   AD00012025115D1E4017         12  1.243275    5
4   AD00012025115D1E4016          0 -0.669456    2
5   AD00012025115D1E4015         17  2.040245    5
6   AD00012025115D1E4014          0 -0.669456    2
7   AD00012025115D1E4013          1 -0.510061    2
8   AD00012025115D1E4012         20  2.518428    5
9   AD00012025115D1E4011          2 -0.350667    2
10  AD00012025115D1E4010          0 -0.669456    2
11  AD00012025115D1E4009          2 -0.350667    2
12  AD00012025115D1E4008          1 -0.510061    2
13  AD00012025115D1E4007          4 -0.031879    3
14  AD00012025115D1E4006          1 -0.510061    2
15  AD00012025115D1E4005          4 -0.031879    3
16  AD00012025115D1E4004          0 -0.669456    2
17  AD00012025115D1E4003          2 -0.350667    2
18  AD00012025115D1E4002          2 -0.350667    2
19  AD00012025115D1E4001          0 -0.669456    2

In [56]:
count_point_df.sort_values('student_code', inplace=True)
tr_df.sort_values('STUDENT_CODE', inplace=True)
a_list = count_point_df['정규화'].to_list()
b_list = tr_df['정규화'].to_list()
diff_list = []
for a, b in zip(a_list, b_list) :
    diff = a - b
    diff_list.append(diff)
squ_list = [i**2 for i in diff_list]
sum_value = sum(squ_list)
root_value = sum_value**0.5
max_value = (len(a_list)*16)**0.5
euclidean_value = (1-(root_value/max_value))*100
euclidean_value = max(0, euclidean_value)
print(euclidean_value)

52.56583509747432

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2226412524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 피해

In [58]:
def total_euclidean_value(tr_df, tr_no, point_df, point_no) :
    tr_df = query_df.loc[query_df['QUESTION_NO'] == tr_no, :]
    tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
    def normalize(z):
        if z >= 0.84:
            return 5
        elif z >= 0.25:
            return 4
        elif z >= -0.25:
            return 3
        elif z >= -0.84:
            return 2
        else:
            return 1
    tr_df['정규화'] = tr_df['z점수'].apply(normalize)
    student_list = df['target_code'].unique().tolist()
    count_point_df, psy_code = count_point(df, student_list, point_no)
    mean = count_point_df['num_point'].mean()
    std = count_point_df['num_point'].std(ddof=0)
    count_point_df['z점수'] = (count_point_df['num_point'] - mean) / std
    def normalize(z):
        if z >= 0.84:
            return 5
        elif z >= 0.25:
            return 4
        elif z >= -0.25:
            return 3
        elif z >= -0.84:
            return 2
        else:
            return 1
    count_point_df['정규화'] = count_point_df['z점수'].apply(normalize)
    count_point_df.sort_values('student_code', inplace=True)
    tr_df.sort_values('STUDENT_CODE', inplace=True)
    a_list = count_point_df['정규화'].to_list()
    b_list = tr_df['정규화'].to_list()
    diff_list = []
    for a, b in zip(a_list, b_list) :
        diff = a - b
        diff_list.append(diff)
    squ_list = [i**2 for i in diff_list]
    sum_value = sum(squ_list)
    root_value = sum_value**0.5
    max_value = (len(a_list)*16)**0.5
    euclidean_value = (1-(root_value/max_value))*100
    euclidean_value = max(0, euclidean_value)
    return tr_df['정규화'], count_point_df['정규화'], euclidean_value
df_1, df_2, result_value = total_euclidean_value(tr_df, 5, count_point_df, [10,11])
print(result_value)
print(df_1)
print(df_2)

52.56583509747432
80    4
81    1
82    5
83    5
84    5
85    1
86    4
87    1
88    2
89    4
90    2
91    2
92    4
93    1
94    4
95    2
96    2
97    4
98    4
99    5
Name: 정규화, dtype: int64
19    2
18    2
17    2
16    2
15    3
14    2
13    3
12    2
11    2
10    2
9     2
8     5
7     2
6     2
5     5
4     2
3     5
2     5
1     2
0     2
Name: 정규화, dtype: int64

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2434413560.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2434413560.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\2434413560.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df.sort_values('STUDENT_CODE', inplace=True)

### 행동적 수업참여

In [59]:
# 자기보고 문항
self_scale_dict = {
    '행동적 수업 참여' : ['q45', 'q46', 'q47', 'q48', 'q49'],
    '경쟁적 태도' : [f'q{n}' for n in range(62, 70)]
}
self_scale_dict

{'행동적 수업 참여': ['q45', 'q46', 'q47', 'q48', 'q49'],
 '경쟁적 태도': ['q62', 'q63', 'q64', 'q65', 'q66', 'q67', 'q68', 'q69']}

In [60]:
# 급하기 때문에 raw csv에서 학생명단으로 병합하여 검수 진행
import pandas as pd
testing_paper_df = pd.read_csv("AT_USER_TESTING_PAPER_202511140921.csv")
# 학생 리스트 구하기
student_testing_list = df['user_testing_no'].unique().tolist()
print(student_testing_list)
print(len(student_testing_list))
# 병합하여 자기보고 json 추출
testing_paper_df_filtered = pd.merge(testing_paper_df, pd.DataFrame({'USER_TESTING_NO': student_testing_list}), on='USER_TESTING_NO', how='inner')
print(testing_paper_df_filtered)

['8916207158814a67abc2', 'a28c9553672c4f54ad7d', '157327d769394633811f', 'd163f8c83ef64c50aa87', 'ac181f9b8eaa426cb4c8', '72559204bbdf448b912f', '30aa23408f104d1293a4', '4f3f46fc2d2244758a78', 'dc9998566c234f0599c3', '1eb4ec746358472a9a97', 'a511507acce04b908351', '14c8df44e4004885a5e0', '1d49e9937ff141f98e40', '083269d802e940ce95be', 'e0cebb8191764f41a106', 'bd5e577fd48840d6bd34', '521595a387b449f8b55d', '59237a4bfe5b46189c25', '62dfbfb230e1497c963a', '5021a196f7c74c81a151']
20
         USER_TESTING_NO                                         PAPER_JSON  \
0   083269d802e940ce95be  {"questionChoiceList":[{"questionNo":1,"choice...
1   14c8df44e4004885a5e0  {"questionChoiceList":[{"questionNo":1,"choice...
2   157327d769394633811f  {"questionChoiceList":[{"questionNo":1,"choice...
3   1d49e9937ff141f98e40  {"questionChoiceList":[{"questionNo":1,"choice...
4   1eb4ec746358472a9a97  {"questionChoiceList":[{"questionNo":1,"choice...
5   30aa23408f104d1293a4  {"questionChoiceList":[{"questionNo":1,"choice...
6   4f3f46fc2d2244758a78  {"questionChoiceList":[{"questionNo":1,"choice...
7   5021a196f7c74c81a151  {"questionChoiceList":[{"questionNo":1,"choice...
8   521595a387b449f8b55d  {"questionChoiceList":[{"questionNo":1,"choice...
9   59237a4bfe5b46189c25  {"questionChoiceList":[{"questionNo":1,"choice...
10  62dfbfb230e1497c963a  {"questionChoiceList":[{"questionNo":1,"choice...
11  72559204bbdf448b912f  {"questionChoiceList":[{"questionNo":1,"choice...
12  8916207158814a67abc2  {"questionChoiceList":[{"questionNo":1,"choice...
13  a28c9553672c4f54ad7d  {"questionChoiceList":[{"questionNo":1,"choice...
14  a511507acce04b908351  {"questionChoiceList":[{"questionNo":1,"choice...
15  ac181f9b8eaa426cb4c8  {"questionChoiceList":[{"questionNo":1,"choice...
16  bd5e577fd48840d6bd34  {"questionChoiceList":[{"questionNo":1,"choice...
17  d163f8c83ef64c50aa87  {"questionChoiceList":[{"questionNo":1,"choice...
18  dc9998566c234f0599c3  {"questionChoiceList":[{"questionNo":1,"choice...
19  e0cebb8191764f41a106  {"questionChoiceList":[{"questionNo":1,"choice...

               REG_DATE
0   2025-11-13 11:17:36
1   2025-11-13 11:31:45
2   2025-11-13 12:40:22
3   2025-11-13 11:24:31
4   2025-11-13 11:46:34
5   2025-11-13 12:11:09
6   2025-11-13 12:03:14
7   2025-11-13 10:27:12
8   2025-11-13 10:54:38
9   2025-11-13 10:41:26
10  2025-11-13 10:34:01
11  2025-11-13 12:18:15
12  2025-11-13 12:54:45
13  2025-11-13 12:47:15
14  2025-11-13 11:39:22
15  2025-11-13 12:25:40
16  2025-11-13 11:01:39
17  2025-11-13 12:32:58
18  2025-11-13 13:17:53
19  2025-11-13 11:09:46

In [62]:
import json
self_report_df = pd.DataFrame()
for idx, row in testing_paper_df_filtered.iterrows():
    user_testing_no = row['USER_TESTING_NO']
    json_data = json.loads(row['PAPER_JSON'])
    question_choices_df = pd.DataFrame(json_data['questionChoiceList'])
    question_choices_df = question_choices_df['choiceScore']
    temp_df = pd.DataFrame(question_choices_df).transpose()
    temp_df['USER_TESTING_NO'] = user_testing_no
    self_report_df = pd.concat([self_report_df, temp_df], ignore_index=True)
print(self_report_df)
# 컬럼명 변경
self_report_df.columns = [f'q{col+1}' if isinstance(col, int) else col for col in self_report_df.columns]
# 컬럼명 순서 변경
self_report_df = self_report_df[['USER_TESTING_NO'] + [col for col in self_report_df.columns if col != 'USER_TESTING_NO']]
print(self_report_df)

    0  1  2  3  4  5  6  7  8  9  ... 108 109 110 111 112 113 114 115 116  \
0   1  4  3  3  3  3  3  3  1  1  ...   5   4   4   4   3   1   4   3   3
1   4  2  3  3  1  3  3  5  4  3  ...   5   4   3   4   3   5   5   4   5
2   3  3  3  3  1  3  3  3  2  4  ...   3   1   5   5   4   4   3   5   5
3   4  5  5  2  1  1  1  3  4  3  ...   5   5   2   2   1   1   2   3   1
4   4  5  3  4  3  3  1  2  1  1  ...   1   5   1   3   2   1   1   2   1
5   4  5  5  5  2  5  2  4  5  3  ...   1   1   3   1   3   1   2   2   1
6   3  4  4  2  3  3  4  4  5  5  ...   3   5   5   5   3   2   5   3   4
7   5  5  2  5  3  4  4  4  4  3  ...   2   4   1   3   3   3   3   2   1
8   1  5  5  4  4  2  2  1  3  3  ...   3   5   5   5   5   2   5   3   4
9   2  1  1  2  1  1  2  3  3  2  ...   2   1   1   3   5   1   1   2   3
10  3  3  5  5  5  3  4  3  1  5  ...   5   2   5   2   1   5   1   3   1
11  3  3  3  1  2  3  2  2  1  4  ...   4   5   4   3   3   2   3   5   4
12  5  3  3  4  4  5  5  4  3  4  ...   3   2   3   3   5   3   3   3   4
13  3  1  1  1  1  2  1  3  2  4  ...   2   1   2   2   3   4   2   3   1
14  1  1  1  1  1  1  4  3  4  1  ...   2   1   2   3   1   1   1   3   1
15  3  4  5  5  4  3  5  4  5  5  ...   3   3   2   2   1   3   3   3   3
16  1  3  2  2  1  1  1  3  1  2  ...   2   1   2   3   1   2   3   3   3
17  3  1  4  3  4  3  2  3  2  2  ...   3   5   4   4   4   4   4   3   5
18  3  5  5  3  5  2  3  3  2  3  ...   4   4   5   5   4   5   5   4   2
19  2  4  2  1  1  1  5  5  5  4  ...   3   5   4   4   2   3   1   2   2

         USER_TESTING_NO
0   083269d802e940ce95be
1   14c8df44e4004885a5e0
2   157327d769394633811f
3   1d49e9937ff141f98e40
4   1eb4ec746358472a9a97
5   30aa23408f104d1293a4
6   4f3f46fc2d2244758a78
7   5021a196f7c74c81a151
8   521595a387b449f8b55d
9   59237a4bfe5b46189c25
10  62dfbfb230e1497c963a
11  72559204bbdf448b912f
12  8916207158814a67abc2
13  a28c9553672c4f54ad7d
14  a511507acce04b908351
15  ac181f9b8eaa426cb4c8
16  bd5e577fd48840d6bd34
17  d163f8c83ef64c50aa87
18  dc9998566c234f0599c3
19  e0cebb8191764f41a106

[20 rows x 118 columns]
         USER_TESTING_NO q1 q2 q3 q4 q5 q6 q7 q8 q9  ... q108 q109 q110 q111  \
0   083269d802e940ce95be  1  4  3  3  3  3  3  3  1  ...    5    5    4    4
1   14c8df44e4004885a5e0  4  2  3  3  1  3  3  5  4  ...    5    5    4    3
2   157327d769394633811f  3  3  3  3  1  3  3  3  2  ...    3    3    1    5
3   1d49e9937ff141f98e40  4  5  5  2  1  1  1  3  4  ...    3    5    5    2
4   1eb4ec746358472a9a97  4  5  3  4  3  3  1  2  1  ...    1    1    5    1
5   30aa23408f104d1293a4  4  5  5  5  2  5  2  4  5  ...    1    1    1    3
6   4f3f46fc2d2244758a78  3  4  4  2  3  3  4  4  5  ...    4    3    5    5
7   5021a196f7c74c81a151  5  5  2  5  3  4  4  4  4  ...    5    2    4    1
8   521595a387b449f8b55d  1  5  5  4  4  2  2  1  3  ...    3    3    5    5
9   59237a4bfe5b46189c25  2  1  1  2  1  1  2  3  3  ...    1    2    1    1
10  62dfbfb230e1497c963a  3  3  5  5  5  3  4  3  1  ...    1    5    2    5
11  72559204bbdf448b912f  3  3  3  1  2  3  2  2  1  ...    4    4    5    4
12  8916207158814a67abc2  5  3  3  4  4  5  5  4  3  ...    2    3    2    3
13  a28c9553672c4f54ad7d  3  1  1  1  1  2  1  3  2  ...    3    2    1    2
14  a511507acce04b908351  1  1  1  1  1  1  4  3  4  ...    3    2    1    2
15  ac181f9b8eaa426cb4c8  3  4  5  5  4  3  5  4  5  ...    5    3    3    2
16  bd5e577fd48840d6bd34  1  3  2  2  1  1  1  3  1  ...    3    2    1    2
17  d163f8c83ef64c50aa87  3  1  4  3  4  3  2  3  2  ...    5    3    5    4
18  dc9998566c234f0599c3  3  5  5  3  5  2  3  3  2  ...    4    4    4    5
19  e0cebb8191764f41a106  2  4  2  1  1  1  5  5  5  ...    1    3    5    4

   q112 q113 q114 q115 q116 q117
0     4    3    1    4    3    3
1     4    3    5    5    4    5
2     5    4    4    3    5    5
3     2    1    1    2    3    1
4     3    2    1    1    2    1
5     1    3    1    2    2    1
6     5    3    2    5    3    4
7     3    3    3    3    2    1
8     5    5    2    5    3    4
9     3    5    1    1    2    3
10    2    1    5    1    3    1
11    3    3    2    3    5    4
12    3    5    3    3    3    4
13    2    3    4    2    3    1
14    3    1    1    1    3    1
15    2    1    3    3    3    3
16    3    1    2    3    3    3
17    4    4    4    4    3    5
18    5    4    5    5    4    2
19    4    2    3    1    2    2

[20 rows x 118 columns]

In [63]:
result_self_scale_df = df.loc[:, ['target_code', 'user_testing_no']].copy().drop_duplicates(subset=['target_code', 'user_testing_no'])
for scale, items in self_scale_dict.items() :
    self_report_df[items] = self_report_df[items].apply(pd.to_numeric, errors='coerce')
    self_report_df[f'{scale}_평균점수'] = self_report_df[items].mean(axis=1).round(2)
    temp_df = self_report_df[['USER_TESTING_NO', f'{scale}_평균점수']].copy()
    result_self_scale_df = pd.merge(result_self_scale_df, temp_df, left_on='user_testing_no', right_on='USER_TESTING_NO', how='left')
    result_self_scale_df.drop(columns=['USER_TESTING_NO'], inplace=True)
result_self_scale_df

             target_code       user_testing_no  행동적 수업 참여_평균점수  경쟁적 태도_평균점수
0   AD00012025115D1E4020  8916207158814a67abc2             2.4         4.12
1   AD00012025115D1E4019  a28c9553672c4f54ad7d             2.8         4.38
2   AD00012025115D1E4018  157327d769394633811f             2.0         2.75
3   AD00012025115D1E4017  d163f8c83ef64c50aa87             1.6         1.25
4   AD00012025115D1E4016  ac181f9b8eaa426cb4c8             4.0         3.88
5   AD00012025115D1E4015  72559204bbdf448b912f             3.0         1.50
6   AD00012025115D1E4014  30aa23408f104d1293a4             4.6         4.50
7   AD00012025115D1E4013  4f3f46fc2d2244758a78             2.0         3.88
8   AD00012025115D1E4012  dc9998566c234f0599c3             2.8         3.00
9   AD00012025115D1E4011  1eb4ec746358472a9a97             3.8         2.00
10  AD00012025115D1E4010  a511507acce04b908351             2.6         3.62
11  AD00012025115D1E4009  14c8df44e4004885a5e0             2.8         4.00
12  AD00012025115D1E4008  1d49e9937ff141f98e40             1.8         3.75
13  AD00012025115D1E4007  083269d802e940ce95be             3.8         1.75
14  AD00012025115D1E4006  e0cebb8191764f41a106             2.0         4.50
15  AD00012025115D1E4005  bd5e577fd48840d6bd34             2.4         1.50
16  AD00012025115D1E4004  521595a387b449f8b55d             4.6         1.75
17  AD00012025115D1E4003  59237a4bfe5b46189c25             2.2         3.62
18  AD00012025115D1E4002  62dfbfb230e1497c963a             4.0         4.12
19  AD00012025115D1E4001  5021a196f7c74c81a151             4.2         4.50

In [64]:
# 교사 학생 평가 문항
tr_df = query_df.loc[query_df['QUESTION_NO'] == 7, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\1265923697.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\1265923697.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
120,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4001,2,2025-11-13 13:24:57,-0.940089,1
121,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4002,4,2025-11-13 13:24:57,0.850557,5
122,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4003,3,2025-11-13 13:24:57,-0.044766,3
123,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4004,5,2025-11-13 13:24:57,1.745880,5
124,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4005,5,2025-11-13 13:24:57,1.745880,5
125,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4006,1,2025-11-13 13:24:57,-1.835412,1
126,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4007,2,2025-11-13 13:24:57,-0.940089,1
127,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4008,3,2025-11-13 13:24:57,-0.044766,3
128,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4009,3,2025-11-13 13:24:57,-0.044766,3
129,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4010,3,2025-11-13 13:24:57,-0.044766,3
130,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4011,3,2025-11-13 13:24:57,-0.044766,3
131,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4012,2,2025-11-13 13:24:57,-0.940089,1
132,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4013,1,2025-11-13 13:24:57,-1.835412,1
133,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4014,2,2025-11-13 13:24:57,-0.940089,1
134,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4015,4,2025-11-13 13:24:57,0.850557,5
135,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4016,3,2025-11-13 13:24:57,-0.044766,3
136,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4017,3,2025-11-13 13:24:57,-0.044766,3
137,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4018,4,2025-11-13 13:24:57,0.850557,5
138,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4019,4,2025-11-13 13:24:57,0.850557,5
139,e91d62e3680c4cf9bd7a,7,AD00012025115D1E4020,4,2025-11-13 13:24:57,0.850557,5

### 경쟁적 태도

In [ ]:
# 자기보고 문항
self_scale_dict = {
    '행동적 수업 참여' : ['q45', 'q46', 'q47', 'q48', 'q49'],
    '경쟁적 태도' : [f'q{n}' for n in range(62, 70)]
}
self_scale_dict

{'행동적 수업 참여': ['q45', 'q46', 'q47', 'q48', 'q49'],
 '경쟁적 태도': ['q62', 'q63', 'q64', 'q65', 'q66', 'q67', 'q68', 'q69']}

In [ ]:
# 급하기 때문에 raw csv에서 학생명단으로 병합하여 검수 진행
import pandas as pd
testing_paper_df = pd.read_csv("AT_USER_TESTING_PAPER_202511140921.csv")
# 학생 리스트 구하기
student_testing_list = df['user_testing_no'].unique().tolist()
print(student_testing_list)
print(len(student_testing_list))
# 병합하여 자기보고 json 추출
testing_paper_df_filtered = pd.merge(testing_paper_df, pd.DataFrame({'USER_TESTING_NO': student_testing_list}), on='USER_TESTING_NO', how='inner')
print(testing_paper_df_filtered)

['8916207158814a67abc2', 'a28c9553672c4f54ad7d', '157327d769394633811f', 'd163f8c83ef64c50aa87', 'ac181f9b8eaa426cb4c8', '72559204bbdf448b912f', '30aa23408f104d1293a4', '4f3f46fc2d2244758a78', 'dc9998566c234f0599c3', '1eb4ec746358472a9a97', 'a511507acce04b908351', '14c8df44e4004885a5e0', '1d49e9937ff141f98e40', '083269d802e940ce95be', 'e0cebb8191764f41a106', 'bd5e577fd48840d6bd34', '521595a387b449f8b55d', '59237a4bfe5b46189c25', '62dfbfb230e1497c963a', '5021a196f7c74c81a151']
20
         USER_TESTING_NO                                         PAPER_JSON  \
0   083269d802e940ce95be  {"questionChoiceList":[{"questionNo":1,"choice...
1   14c8df44e4004885a5e0  {"questionChoiceList":[{"questionNo":1,"choice...
2   157327d769394633811f  {"questionChoiceList":[{"questionNo":1,"choice...
3   1d49e9937ff141f98e40  {"questionChoiceList":[{"questionNo":1,"choice...
4   1eb4ec746358472a9a97  {"questionChoiceList":[{"questionNo":1,"choice...
5   30aa23408f104d1293a4  {"questionChoiceList":[{"questionNo":1,"choice...
6   4f3f46fc2d2244758a78  {"questionChoiceList":[{"questionNo":1,"choice...
7   5021a196f7c74c81a151  {"questionChoiceList":[{"questionNo":1,"choice...
8   521595a387b449f8b55d  {"questionChoiceList":[{"questionNo":1,"choice...
9   59237a4bfe5b46189c25  {"questionChoiceList":[{"questionNo":1,"choice...
10  62dfbfb230e1497c963a  {"questionChoiceList":[{"questionNo":1,"choice...
11  72559204bbdf448b912f  {"questionChoiceList":[{"questionNo":1,"choice...
12  8916207158814a67abc2  {"questionChoiceList":[{"questionNo":1,"choice...
13  a28c9553672c4f54ad7d  {"questionChoiceList":[{"questionNo":1,"choice...
14  a511507acce04b908351  {"questionChoiceList":[{"questionNo":1,"choice...
15  ac181f9b8eaa426cb4c8  {"questionChoiceList":[{"questionNo":1,"choice...
16  bd5e577fd48840d6bd34  {"questionChoiceList":[{"questionNo":1,"choice...
17  d163f8c83ef64c50aa87  {"questionChoiceList":[{"questionNo":1,"choice...
18  dc9998566c234f0599c3  {"questionChoiceList":[{"questionNo":1,"choice...
19  e0cebb8191764f41a106  {"questionChoiceList":[{"questionNo":1,"choice...

               REG_DATE
0   2025-11-13 11:17:36
1   2025-11-13 11:31:45
2   2025-11-13 12:40:22
3   2025-11-13 11:24:31
4   2025-11-13 11:46:34
5   2025-11-13 12:11:09
6   2025-11-13 12:03:14
7   2025-11-13 10:27:12
8   2025-11-13 10:54:38
9   2025-11-13 10:41:26
10  2025-11-13 10:34:01
11  2025-11-13 12:18:15
12  2025-11-13 12:54:45
13  2025-11-13 12:47:15
14  2025-11-13 11:39:22
15  2025-11-13 12:25:40
16  2025-11-13 11:01:39
17  2025-11-13 12:32:58
18  2025-11-13 13:17:53
19  2025-11-13 11:09:46

In [ ]:
import json
self_report_df = pd.DataFrame()
for idx, row in testing_paper_df_filtered.iterrows():
    user_testing_no = row['USER_TESTING_NO']
    json_data = json.loads(row['PAPER_JSON'])
    question_choices_df = pd.DataFrame(json_data['questionChoiceList'])
    question_choices_df = question_choices_df['choiceScore']
    temp_df = pd.DataFrame(question_choices_df).transpose()
    temp_df['USER_TESTING_NO'] = user_testing_no
    self_report_df = pd.concat([self_report_df, temp_df], ignore_index=True)
print(self_report_df)
# 컬럼명 변경
self_report_df.columns = [f'q{col+1}' if isinstance(col, int) else col for col in self_report_df.columns]
# 컬럼명 순서 변경
self_report_df = self_report_df[['USER_TESTING_NO'] + [col for col in self_report_df.columns if col != 'USER_TESTING_NO']]
print(self_report_df)

    0  1  2  3  4  5  6  7  8  9  ... 108 109 110 111 112 113 114 115 116  \
0   1  4  3  3  3  3  3  3  1  1  ...   5   4   4   4   3   1   4   3   3
1   4  2  3  3  1  3  3  5  4  3  ...   5   4   3   4   3   5   5   4   5
2   3  3  3  3  1  3  3  3  2  4  ...   3   1   5   5   4   4   3   5   5
3   4  5  5  2  1  1  1  3  4  3  ...   5   5   2   2   1   1   2   3   1
4   4  5  3  4  3  3  1  2  1  1  ...   1   5   1   3   2   1   1   2   1
5   4  5  5  5  2  5  2  4  5  3  ...   1   1   3   1   3   1   2   2   1
6   3  4  4  2  3  3  4  4  5  5  ...   3   5   5   5   3   2   5   3   4
7   5  5  2  5  3  4  4  4  4  3  ...   2   4   1   3   3   3   3   2   1
8   1  5  5  4  4  2  2  1  3  3  ...   3   5   5   5   5   2   5   3   4
9   2  1  1  2  1  1  2  3  3  2  ...   2   1   1   3   5   1   1   2   3
10  3  3  5  5  5  3  4  3  1  5  ...   5   2   5   2   1   5   1   3   1
11  3  3  3  1  2  3  2  2  1  4  ...   4   5   4   3   3   2   3   5   4
12  5  3  3  4  4  5  5  4  3  4  ...   3   2   3   3   5   3   3   3   4
13  3  1  1  1  1  2  1  3  2  4  ...   2   1   2   2   3   4   2   3   1
14  1  1  1  1  1  1  4  3  4  1  ...   2   1   2   3   1   1   1   3   1
15  3  4  5  5  4  3  5  4  5  5  ...   3   3   2   2   1   3   3   3   3
16  1  3  2  2  1  1  1  3  1  2  ...   2   1   2   3   1   2   3   3   3
17  3  1  4  3  4  3  2  3  2  2  ...   3   5   4   4   4   4   4   3   5
18  3  5  5  3  5  2  3  3  2  3  ...   4   4   5   5   4   5   5   4   2
19  2  4  2  1  1  1  5  5  5  4  ...   3   5   4   4   2   3   1   2   2

         USER_TESTING_NO
0   083269d802e940ce95be
1   14c8df44e4004885a5e0
2   157327d769394633811f
3   1d49e9937ff141f98e40
4   1eb4ec746358472a9a97
5   30aa23408f104d1293a4
6   4f3f46fc2d2244758a78
7   5021a196f7c74c81a151
8   521595a387b449f8b55d
9   59237a4bfe5b46189c25
10  62dfbfb230e1497c963a
11  72559204bbdf448b912f
12  8916207158814a67abc2
13  a28c9553672c4f54ad7d
14  a511507acce04b908351
15  ac181f9b8eaa426cb4c8
16  bd5e577fd48840d6bd34
17  d163f8c83ef64c50aa87
18  dc9998566c234f0599c3
19  e0cebb8191764f41a106

[20 rows x 118 columns]
         USER_TESTING_NO q1 q2 q3 q4 q5 q6 q7 q8 q9  ... q108 q109 q110 q111  \
0   083269d802e940ce95be  1  4  3  3  3  3  3  3  1  ...    5    5    4    4
1   14c8df44e4004885a5e0  4  2  3  3  1  3  3  5  4  ...    5    5    4    3
2   157327d769394633811f  3  3  3  3  1  3  3  3  2  ...    3    3    1    5
3   1d49e9937ff141f98e40  4  5  5  2  1  1  1  3  4  ...    3    5    5    2
4   1eb4ec746358472a9a97  4  5  3  4  3  3  1  2  1  ...    1    1    5    1
5   30aa23408f104d1293a4  4  5  5  5  2  5  2  4  5  ...    1    1    1    3
6   4f3f46fc2d2244758a78  3  4  4  2  3  3  4  4  5  ...    4    3    5    5
7   5021a196f7c74c81a151  5  5  2  5  3  4  4  4  4  ...    5    2    4    1
8   521595a387b449f8b55d  1  5  5  4  4  2  2  1  3  ...    3    3    5    5
9   59237a4bfe5b46189c25  2  1  1  2  1  1  2  3  3  ...    1    2    1    1
10  62dfbfb230e1497c963a  3  3  5  5  5  3  4  3  1  ...    1    5    2    5
11  72559204bbdf448b912f  3  3  3  1  2  3  2  2  1  ...    4    4    5    4
12  8916207158814a67abc2  5  3  3  4  4  5  5  4  3  ...    2    3    2    3
13  a28c9553672c4f54ad7d  3  1  1  1  1  2  1  3  2  ...    3    2    1    2
14  a511507acce04b908351  1  1  1  1  1  1  4  3  4  ...    3    2    1    2
15  ac181f9b8eaa426cb4c8  3  4  5  5  4  3  5  4  5  ...    5    3    3    2
16  bd5e577fd48840d6bd34  1  3  2  2  1  1  1  3  1  ...    3    2    1    2
17  d163f8c83ef64c50aa87  3  1  4  3  4  3  2  3  2  ...    5    3    5    4
18  dc9998566c234f0599c3  3  5  5  3  5  2  3  3  2  ...    4    4    4    5
19  e0cebb8191764f41a106  2  4  2  1  1  1  5  5  5  ...    1    3    5    4

   q112 q113 q114 q115 q116 q117
0     4    3    1    4    3    3
1     4    3    5    5    4    5
2     5    4    4    3    5    5
3     2    1    1    2    3    1
4     3    2    1    1    2    1
5     1    3    1    2    2    1
6     5    3    2    5    3    4
7     3    3    3    3    2    1
8     5    5    2    5    3    4
9     3    5    1    1    2    3
10    2    1    5    1    3    1
11    3    3    2    3    5    4
12    3    5    3    3    3    4
13    2    3    4    2    3    1
14    3    1    1    1    3    1
15    2    1    3    3    3    3
16    3    1    2    3    3    3
17    4    4    4    4    3    5
18    5    4    5    5    4    2
19    4    2    3    1    2    2

[20 rows x 118 columns]

In [ ]:
result_self_scale_df = df.loc[:, ['target_code', 'user_testing_no']].copy().drop_duplicates(subset=['target_code', 'user_testing_no'])
for scale, items in self_scale_dict.items() :
    self_report_df[items] = self_report_df[items].apply(pd.to_numeric, errors='coerce')
    self_report_df[f'{scale}_평균점수'] = self_report_df[items].mean(axis=1).round(2)
    temp_df = self_report_df[['USER_TESTING_NO', f'{scale}_평균점수']].copy()
    result_self_scale_df = pd.merge(result_self_scale_df, temp_df, left_on='user_testing_no', right_on='USER_TESTING_NO', how='left')
    result_self_scale_df.drop(columns=['USER_TESTING_NO'], inplace=True)
result_self_scale_df

             target_code       user_testing_no  행동적 수업 참여_평균점수  경쟁적 태도_평균점수
0   AD00012025115D1E4020  8916207158814a67abc2             2.4         4.12
1   AD00012025115D1E4019  a28c9553672c4f54ad7d             2.8         4.38
2   AD00012025115D1E4018  157327d769394633811f             2.0         2.75
3   AD00012025115D1E4017  d163f8c83ef64c50aa87             1.6         1.25
4   AD00012025115D1E4016  ac181f9b8eaa426cb4c8             4.0         3.88
5   AD00012025115D1E4015  72559204bbdf448b912f             3.0         1.50
6   AD00012025115D1E4014  30aa23408f104d1293a4             4.6         4.50
7   AD00012025115D1E4013  4f3f46fc2d2244758a78             2.0         3.88
8   AD00012025115D1E4012  dc9998566c234f0599c3             2.8         3.00
9   AD00012025115D1E4011  1eb4ec746358472a9a97             3.8         2.00
10  AD00012025115D1E4010  a511507acce04b908351             2.6         3.62
11  AD00012025115D1E4009  14c8df44e4004885a5e0             2.8         4.00
12  AD00012025115D1E4008  1d49e9937ff141f98e40             1.8         3.75
13  AD00012025115D1E4007  083269d802e940ce95be             3.8         1.75
14  AD00012025115D1E4006  e0cebb8191764f41a106             2.0         4.50
15  AD00012025115D1E4005  bd5e577fd48840d6bd34             2.4         1.50
16  AD00012025115D1E4004  521595a387b449f8b55d             4.6         1.75
17  AD00012025115D1E4003  59237a4bfe5b46189c25             2.2         3.62
18  AD00012025115D1E4002  62dfbfb230e1497c963a             4.0         4.12
19  AD00012025115D1E4001  5021a196f7c74c81a151             4.2         4.50

In [65]:
# 교사 학생 평가 문항
tr_df = query_df.loc[query_df['QUESTION_NO'] == 10, :]
tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
def normalize(z):
    if z >= 0.84:
        return 5
    elif z >= 0.25:
        return 4
    elif z >= -0.25:
        return 3
    elif z >= -0.84:
        return 2
    else:
        return 1
tr_df['정규화'] = tr_df['z점수'].apply(normalize)
tr_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3723684949.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['z점수'] = (tr_df['SELECT_DATA'] - tr_df['SELECT_DATA'].mean()) / tr_df['SELECT_DATA'].std(ddof=0)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_44432\3723684949.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tr_df['정규화'] = tr_df['z점수'].apply(normalize)

,USER_TESTING_NO,QUESTION_NO,STUDENT_CODE,SELECT_DATA,REG_DATE,z점수,정규화
180,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4001,1,2025-11-13 13:24:57,-2.064742,1
181,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4002,3,2025-11-13 13:24:57,-0.229416,3
182,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4003,4,2025-11-13 13:24:57,0.688247,4
183,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4004,4,2025-11-13 13:24:57,0.688247,4
184,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4005,3,2025-11-13 13:24:57,-0.229416,3
185,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4006,2,2025-11-13 13:24:57,-1.147079,1
186,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4007,2,2025-11-13 13:24:57,-1.147079,1
187,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4008,2,2025-11-13 13:24:57,-1.147079,1
188,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4009,2,2025-11-13 13:24:57,-1.147079,1
189,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4010,3,2025-11-13 13:24:57,-0.229416,3
190,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4011,4,2025-11-13 13:24:57,0.688247,4
191,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4012,3,2025-11-13 13:24:57,-0.229416,3
192,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4013,3,2025-11-13 13:24:57,-0.229416,3
193,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4014,3,2025-11-13 13:24:57,-0.229416,3
194,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4015,3,2025-11-13 13:24:57,-0.229416,3
195,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4016,4,2025-11-13 13:24:57,0.688247,4
196,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4017,4,2025-11-13 13:24:57,0.688247,4
197,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4018,5,2025-11-13 13:24:57,1.605910,5
198,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4019,5,2025-11-13 13:24:57,1.605910,5
199,e91d62e3680c4cf9bd7a,10,AD00012025115D1E4020,5,2025-11-13 13:24:57,1.605910,5

In [ ]:
student_list = df['target_code'].to_list()

student_evaluation_df = pd.read_excel('5학년_1반_전수(AC000120255019FA1)/AC000120255019FA1_교사_학생평가_응답.xlsx')

# 지명수 구하는 함수
def count_point(df, student_list, item_no) :
    temp_df = df[df['문항번호'].isin(item_no)]
    count_list = []
    for student in student_list :
        if len(temp_df[temp_df['지명받은 학생']==student]) >= 1 :
            freq = len(temp_df[temp_df['지명받은 학생']==student])
        elif len(temp_df[temp_df['지명받은 학생']==student]) == 0 :
            freq = 0
        count_list.append(freq)
    count_point_df = pd.DataFrame({'학생명': student_list, '지명수': count_list})
    return count_point_df

In [5]:
# 학생 명단과 또래지명을 통해서 척도별 점수 산출 함수
def calculate_scale_scores_by_peer_nomination(student_list, point_df):
    """
    학생 명단과 또래지명 데이터, 문항 번호 리스트를 받아
    학생별로 척도별 점수를 반환하는 함수
    """
    # 정규화
    def normalize(z):
        if z >= 0.84:
            return 5
        elif z >= 0.25:
            return 4
        elif z >= -0.25:
            return 3
        elif z >= -0.84:
            return 2
        else:
            return 1
    
    # 인기
    popularity_item_no = [1]
    popularity_count_df = count_point(point_df, student_list, popularity_item_no)
    popularity_count_mean = popularity_count_df['지명수'].mean()

    popularity_count_df['인기Z점수'] = (popularity_count_df['지명수'] - popularity_count_mean) / popularity_count_df['지명수'].std(ddof=0) # 인기 지명수 Z점수
    popularity_count_df['인기_정규화'] = popularity_count_df['인기Z점수'].apply(normalize)
    # 사회적 선호
    social_preference_item_no = [2]
    social_preference_count_df = count_point(point_df, student_list, social_preference_item_no) # 사회적 선호 지명수
    social_preference_count_mean = social_preference_count_df['지명수'].mean() # 사회적 선호 지명수 학급평균
    social_preference_count_df['사회적선호Z점수'] = (social_preference_count_df['지명수'] - social_preference_count_mean) / social_preference_count_df['지명수'].std(ddof=0) # 사회적 선호 지명수 Z점수
    social_preference_count_df['사회적선호_정규화'] = social_preference_count_df['사회적선호Z점수'].apply(normalize)
    # 외현적 공격성
    overt_aggression_item_no = [4,5]
    overt_aggression_count_df = count_point(point_df, student_list, overt_aggression_item_no) # 외현적 공격성 지명수
    overt_aggression_count_mean = overt_aggression_count_df['지명수'].mean() # 외현적 공격성 지명수 학급평균
    overt_aggression_count_df['외현적공격성Z점수'] = (overt_aggression_count_df['지명수'] - overt_aggression_count_mean) / overt_aggression_count_df['지명수'].std(ddof=0) # 외현적 공격성 지명수 Z점수
    overt_aggression_count_df['외현적공격성_정규화'] = overt_aggression_count_df['외현적공격성Z점수'].apply(normalize)
    # 관계적 공격성
    relational_aggression_item_no = [6,7]
    relational_aggression_count_df = count_point(point_df, student_list, relational_aggression_item_no) # 관계적 공격성 지명수
    relational_aggression_count_mean = relational_aggression_count_df['지명수'].mean() # 관계적 공격성 지명수 학급평균
    relational_aggression_count_df['관계적공격성Z점수'] = (relational_aggression_count_df['지명수'] - relational_aggression_count_mean) / relational_aggression_count_df['지명수'].std(ddof=0) # 관계적 공격성 지명수 Z점수
    relational_aggression_count_df['관계적공격성_정규화'] = relational_aggression_count_df['관계적공격성Z점수'].apply(normalize)
    # 친사회성
    prosocial_item_no = [8,9]
    prosocial_count_df = count_point(point_df, student_list, prosocial_item_no) # 친사회성 지명수
    prosocial_count_mean = prosocial_count_df['지명수'].mean() # 친사회성 지명수 학급평균
    prosocial_count_df['친사회성Z점수'] = (prosocial_count_df['지명수'] - prosocial_count_mean) / prosocial_count_df['지명수'].std(ddof=0) # 친사회성 지명수 Z점수
    prosocial_count_df['친사회성_정규화'] = prosocial_count_df['친사회성Z점수'].apply(normalize)
    # 가해
    perpetrator_item_no = [10, 11]
    perpetrator_count_df = count_point(point_df, student_list, perpetrator_item_no)  # 가해 지명수
    perpetrator_count_mean = perpetrator_count_df['지명수'].mean()  # 가해 지명수 학급평균
    perpetrator_count_df['가해Z점수'] = (perpetrator_count_df['지명수'] - perpetrator_count_mean) / perpetrator_count_df['지명수'].std(ddof=0)  # 가해 지명수 Z점수
    perpetrator_count_df['가해_정규화'] = perpetrator_count_df['가해Z점수'].apply(normalize)
    # 피해
    victim_item_no = [12, 13]
    victim_count_df = count_point(point_df, student_list, victim_item_no)  # 피해 지명수
    victim_count_mean = victim_count_df['지명수'].mean()  # 피해 지명수 학급평균
    victim_count_df['피해Z점수'] = (victim_count_df['지명수'] - victim_count_mean) / victim_count_df['지명수'].std(ddof=0)  # 피해 지명수 Z점수
    victim_count_df['피해_정규화'] = victim_count_df['피해Z점수'].apply(normalize)
    # 교사 선호
    teacher_preference_item_no = [18]
    teacher_preference_count_df = count_point(point_df, student_list, teacher_preference_item_no)
    teacher_preference_count_mean = teacher_preference_count_df['지명수'].mean()
    teacher_preference_count_df['교사선호Z점수'] = (teacher_preference_count_df['지명수'] - teacher_preference_count_mean) / teacher_preference_count_df['지명수'].std(ddof=0)  # 교사 선호 지명수 Z점수
    teacher_preference_count_df['교사선호_정규화'] = teacher_preference_count_df['교사선호Z점수'].apply(normalize)
    # 교사 비선호
    teacher_non_preference_item_no = [19]
    teacher_non_preference_count_df = count_point(point_df, student_list, teacher_non_preference_item_no)
    teacher_non_preference_count_mean = teacher_non_preference_count_df['지명수'].mean()
    teacher_non_preference_count_df['교사비선호Z점수'] = (teacher_non_preference_count_df['지명수'] - teacher_non_preference_count_mean) / teacher_non_preference_count_df['지명수'].std(ddof=0)  # 교사 비선호 지명수 Z점수
    teacher_non_preference_count_df['교사비선호_정규화'] = teacher_non_preference_count_df['교사비선호Z점수'].apply(normalize)

    return pd.DataFrame({
        '학생명': student_list,
        '인기_정규화': popularity_count_df['인기_정규화'],
        '사회적선호_정규화': social_preference_count_df['사회적선호_정규화'],
        '외현적공격성_정규화': overt_aggression_count_df['외현적공격성_정규화'],
        '관계적공격성_정규화': relational_aggression_count_df['관계적공격성_정규화'],
        '친사회성_정규화': prosocial_count_df['친사회성_정규화'],
        '가해_정규화': perpetrator_count_df['가해_정규화'],
        '피해_정규화': victim_count_df['피해_정규화'],
        '교사선호_정규화': teacher_preference_count_df['교사선호_정규화'],
        '교사비선호_정규화': teacher_non_preference_count_df['교사비선호_정규화']
    })

In [6]:
calculate_scale_scores_by_peer_nomination_df= calculate_scale_scores_by_peer_nomination(student_list, point_df)
print(calculate_scale_scores_by_peer_nomination_df)

    학생명  인기_정규화  사회적선호_정규화  외현적공격성_정규화  관계적공격성_정규화  친사회성_정규화  가해_정규화  피해_정규화  \
0   김하윤       4          1           4           5         2       1       2
1   이준서       2          3           1           3         3       1       1
2   박서연       3          3           5           2         5       1       1
3   최민준       4          1           1           1         3       4       2
4   정예은       5          3           5           2         2       3       2
5   강도윤       1          5           4           5         2       1       1
6   오서준       1          5           5           1         3       3       4
7   윤지우       3          3           2           4         3       1       5
8   한예진       2          1           4           1         3       2       5
9   장하람       3          1           1           4         1       4       2
10  조하린       1          1           2           4         2       4       4
11  배수아       2          4           3           5         1       2       2
12  남윤후       1          5           1           3         2       4       4
13  서채은       2          1           3           4         1       4       1
14  이아린       2          5           3           4         2       1       4
15  문지아       5          4           2           1         2       5       2
16  류하진       3          3           5           4         5       2       1
17  신도현       1          1           5           2         4       4       4
18  홍지우       2          1           5           4         5       1       5
19  유하늘       1          4           1           4         3       5       5
20  노지아       3          4           5           2         1       4       4
21  권민서       5          4           2           2         3       5       5

    교사선호_정규화  교사비선호_정규화
0          1          2
1          1          4
2          5          2
3          2          2
4          5          5
5          2          2
6          2          4
7          3          4
8          3          5
9          2          5
10         3          3
11         3          3
12         2          2
13         2          3
14         1          2
15         3          2
16         5          2
17         2          2
18         3          5
19         5          5
20         5          3
21         5          2

In [7]:
'''
다 맞음
'''

'\n다 맞음\n'

### 학생평가에 의한 척도별 점수 산출

In [8]:
student_evaluation_df

    학생 이름  문항번호  응답값
0     김하윤     1    5
1     김하윤     2    4
2     김하윤     3    3
3     김하윤     4    2
4     김하윤     5    3
..    ...   ...  ...
259   권민서     8    2
260   권민서     9    4
261   권민서    10    3
262   권민서    11    3
263   권민서    12    3

[264 rows x 3 columns]

In [9]:
# 학생 명단과 학생평가를 통해서 척도별 점수 산출 함수
def calculate_scale_scores_by_student_evaluation(student_list, student_evaluation_df):
    """
    학생 명단과 학생평가 데이터프레임을 받아 학생별로 척도별 점수를 반환하는 함수
    """
    # 정규화
    def normalize(z):
        if z >= 0.84:
            return 5
        elif z >= 0.25:
            return 4
        elif z >= -0.25:
            return 3
        elif z >= -0.84:
            return 2
        else:
            return 1

    # 인기
    popularity_item_no = [2]
    popularity_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(popularity_item_no)].reset_index(drop=True)
    popularity_evaluation_df['응답값'] = popularity_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    popularity_evaluation_mean = popularity_evaluation_df['응답값'].mean()
    print(popularity_evaluation_mean, popularity_evaluation_df['응답값'].std(ddof=0))
    popularity_evaluation_df['인기Z점수'] = (popularity_evaluation_df['응답값'] - popularity_evaluation_mean) / popularity_evaluation_df['응답값'].std(ddof=0)  # 인기 Z점수
    popularity_evaluation_df['인기_정규화'] = popularity_evaluation_df['인기Z점수'].apply(normalize)
    print(popularity_evaluation_df)
    # 선호
    social_preference_item_no = [3]
    social_preference_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(social_preference_item_no)].reset_index(drop=True)
    social_preference_evaluation_df['응답값'] = social_preference_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    social_preference_evaluation_mean = social_preference_evaluation_df['응답값'].mean()
    social_preference_evaluation_df['사회적선호Z점수'] = (social_preference_evaluation_df['응답값'] - social_preference_evaluation_mean) / social_preference_evaluation_df['응답값'].std(ddof=0)  # 사회적 선호 Z점수
    social_preference_evaluation_df['사회적선호_정규화'] = social_preference_evaluation_df['사회적선호Z점수'].apply(normalize)
    # 외현적 공격성
    overt_aggression_item_no = [4]
    overt_aggression_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(overt_aggression_item_no)].reset_index(drop=True)
    overt_aggression_evaluation_df['응답값'] = overt_aggression_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    overt_aggression_evaluation_mean = overt_aggression_evaluation_df['응답값'].mean()
    overt_aggression_evaluation_df['외현적공격성Z점수'] = (overt_aggression_evaluation_df['응답값'] - overt_aggression_evaluation_mean) / overt_aggression_evaluation_df['응답값'].std(ddof=0)  # 외현적 공격성 Z점수
    overt_aggression_evaluation_df['외현적공격성_정규화'] = overt_aggression_evaluation_df['외현적공격성Z점수'].apply(normalize)
    # 관계적 공격성
    relational_aggression_item_no = [5]
    relational_aggression_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(relational_aggression_item_no)].reset_index(drop=True)
    relational_aggression_evaluation_df['응답값'] = relational_aggression_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    relational_aggression_evaluation_mean = relational_aggression_evaluation_df['응답값'].mean()
    relational_aggression_evaluation_df['관계적공격성Z점수'] = (relational_aggression_evaluation_df['응답값'] - relational_aggression_evaluation_mean) / relational_aggression_evaluation_df['응답값'].std(ddof=0)  # 관계적 공격성 Z점수
    relational_aggression_evaluation_df['관계적공격성_정규화'] = relational_aggression_evaluation_df['관계적공격성Z점수'].apply(normalize)
    # 친사회성
    prosocial_item_no = [8]
    prosocial_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(prosocial_item_no)].reset_index(drop=True)
    prosocial_evaluation_df['응답값'] = prosocial_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    prosocial_evaluation_mean = prosocial_evaluation_df['응답값'].mean()
    prosocial_evaluation_df['친사회성Z점수'] = (prosocial_evaluation_df['응답값'] - prosocial_evaluation_mean) / prosocial_evaluation_df['응답값'].std(ddof=0)  # 친사회성 Z점수
    prosocial_evaluation_df['친사회성_정규화'] = prosocial_evaluation_df['친사회성Z점수'].apply(normalize)
    # 가해
    perpetrator_item_no = [6]
    perpetrator_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(perpetrator_item_no)].reset_index(drop=True)
    perpetrator_evaluation_df['응답값'] = perpetrator_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    perpetrator_evaluation_mean = perpetrator_evaluation_df['응답값'].mean()
    perpetrator_evaluation_df['가해Z점수'] = (perpetrator_evaluation_df['응답값'] - perpetrator_evaluation_mean) / perpetrator_evaluation_df['응답값'].std(ddof=0)  # 가해 Z점수
    perpetrator_evaluation_df['가해_정규화'] = perpetrator_evaluation_df['가해Z점수'].apply(normalize)
    # 피해
    victim_item_no = [7]
    victim_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(victim_item_no)].reset_index(drop=True)
    victim_evaluation_df['응답값'] = victim_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    victim_evaluation_mean = victim_evaluation_df['응답값'].mean()
    victim_evaluation_df['피해Z점수'] = (victim_evaluation_df['응답값'] - victim_evaluation_mean) / victim_evaluation_df['응답값'].std(ddof=0)  # 피해 Z점수
    victim_evaluation_df['피해_정규화'] = victim_evaluation_df['피해Z점수'].apply(normalize)
    # 교사 선호
    teacher_preference_item_no = [11]
    teacher_preference_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(teacher_preference_item_no)].reset_index(drop=True)
    teacher_preference_evaluation_df['응답값'] = teacher_preference_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    teacher_preference_evaluation_mean = teacher_preference_evaluation_df['응답값'].mean()
    teacher_preference_evaluation_df['교사선호Z점수'] = (teacher_preference_evaluation_df['응답값'] - teacher_preference_evaluation_mean) / teacher_preference_evaluation_df['응답값'].std(ddof=0)  # 교사 선호 Z점수
    teacher_preference_evaluation_df['교사선호_정규화'] = teacher_preference_evaluation_df['교사선호Z점수'].apply(normalize)
    # 교사 비선호
    teacher_non_preference_item_no = [12]
    teacher_non_preference_evaluation_df = student_evaluation_df[student_evaluation_df['문항번호'].isin(teacher_non_preference_item_no)].reset_index(drop=True)
    teacher_non_preference_evaluation_df['응답값'] = teacher_non_preference_evaluation_df['응답값'].apply(pd.to_numeric, errors='coerce')
    teacher_non_preference_evaluation_mean = teacher_non_preference_evaluation_df['응답값'].mean()
    teacher_non_preference_evaluation_df['교사비선호Z점수'] = (teacher_non_preference_evaluation_df['응답값'] - teacher_non_preference_evaluation_mean) / teacher_non_preference_evaluation_df['응답값'].std(ddof=0)  # 교사 비선호 Z점수
    teacher_non_preference_evaluation_df['교사비선호_정규화'] = teacher_non_preference_evaluation_df['교사비선호Z점수'].apply(normalize)
    
    return pd.DataFrame({
        '학생명': student_list,
        '인기_정규화': popularity_evaluation_df['인기_정규화'],
        '사회적선호_정규화': social_preference_evaluation_df['사회적선호_정규화'],
        '외현적공격성_정규화': overt_aggression_evaluation_df['외현적공격성_정규화'],
        '관계적공격성_정규화': relational_aggression_evaluation_df['관계적공격성_정규화'],
        '친사회성_정규화': prosocial_evaluation_df['친사회성_정규화'],
        '가해_정규화': perpetrator_evaluation_df['가해_정규화'],
        '피해_정규화': victim_evaluation_df['피해_정규화'],
        '교사선호_정규화': teacher_preference_evaluation_df['교사선호_정규화'],
        '교사비선호_정규화': teacher_non_preference_evaluation_df['교사비선호_정규화']
    })

In [10]:
calculate_scale_scores_by_student_evaluation_df = calculate_scale_scores_by_student_evaluation(student_list, student_evaluation_df)
print(calculate_scale_scores_by_student_evaluation_df)

2.909090909090909 1.443137078762504
   학생 이름  문항번호  응답값     인기Z점수  인기_정규화
0    김하윤     2    4  0.755929       4
1    이준서     2    1 -1.322876       1
2    박서연     2    5  1.448864       5
3    최민준     2    1 -1.322876       1
4    정예은     2    4  0.755929       4
5    강도윤     2    4  0.755929       4
6    오서준     2    1 -1.322876       1
7    윤지우     2    5  1.448864       5
8    한예진     2    3  0.062994       3
9    장하람     2    4  0.755929       4
10   조하린     2    3  0.062994       3
11   배수아     2    2 -0.629941       2
12   남윤후     2    1 -1.322876       1
13   서채은     2    3  0.062994       3
14   이아린     2    1 -1.322876       1
15   문지아     2    1 -1.322876       1
16   류하진     2    3  0.062994       3
17   신도현     2    3  0.062994       3
18   홍지우     2    5  1.448864       5
19   유하늘     2    2 -0.629941       2
20   노지아     2    3  0.062994       3
21   권민서     2    5  1.448864       5
    학생명  인기_정규화  사회적선호_정규화  외현적공격성_정규화  관계적공격성_정규화  친사회성_정규화  가해_정규화  피해_정규화  \
0   김하윤       4          3           3           4         5       1       3
1   이준서       1          3           2           1         3       1       5
2   박서연       5          3           2           2         1       2       2
3   최민준       1          1           2           1         3       1       2
4   정예은       4          5           2           1         5       2       3
5   강도윤       4          3           3           4         5       1       3
6   오서준       1          2           5           2         3       4       5
7   윤지우       5          5           2           5         5       5       2
8   한예진       3          3           5           4         3       5       3
9   장하람       4          5           2           1         5       2       3
10  조하린       3          1           5           5         1       5       2
11  배수아       2          2           2           2         1       1       2
12  남윤후       1          1           2           1         3       1       2
13  서채은       3          3           5           4         3       5       3
14  이아린       1          1           2           1         3       1       2
15  문지아       1          2           5           2         3       4       5
16  류하진       3          1           5           5         1       5       2
17  신도현       3          3           4           4         4       4       4
18  홍지우       5          5           2           5         5       5       2
19  유하늘       2          2           2           2         1       1       2
20  노지아       3          3           4           4         4       4       4
21  권민서       5          3           2           2         1       2       2

    교사선호_정규화  교사비선호_정규화
0          5          1
1          2          5
2          2          3
3          2          5
4          4          1
5          5          1
6          2          4
7          5          3
8          2          4
9          4          1
10         2          4
11         1          1
12         2          5
13         2          4
14         2          5
15         2          4
16         2          4
17         5          1
18         5          3
19         1          1
20         5          1
21         2          3

In [11]:
calculate_scale_scores_by_student_evaluation_df

,학생명,인기_정규화,사회적선호_정규화,외현적공격성_정규화,관계적공격성_정규화,친사회성_정규화,가해_정규화,피해_정규화,교사선호_정규화,교사비선호_정규화
0,김하윤,4,3,3,4,5,1,3,5,1
1,이준서,1,3,2,1,3,1,5,2,5
2,박서연,5,3,2,2,1,2,2,2,3
3,최민준,1,1,2,1,3,1,2,2,5
4,정예은,4,5,2,1,5,2,3,4,1
5,강도윤,4,3,3,4,5,1,3,5,1
6,오서준,1,2,5,2,3,4,5,2,4
7,윤지우,5,5,2,5,5,5,2,5,3
8,한예진,3,3,5,4,3,5,3,2,4
9,장하람,4,5,2,1,5,2,3,4,1
10,조하린,3,1,5,5,1,5,2,2,4
11,배수아,2,2,2,2,1,1,2,1,1
12,남윤후,1,1,2,1,3,1,2,2,5
13,서채은,3,3,5,4,3,5,3,2,4
14,이아린,1,1,2,1,3,1,2,2,5
15,문지아,1,2,5,2,3,4,5,2,4
16,류하진,3,1,5,5,1,5,2,2,4
17,신도현,3,3,4,4,4,4,4,5,1
18,홍지우,5,5,2,5,5,5,2,5,3
19,유하늘,2,2,2,2,1,1,2,1,1
20,노지아,3,3,4,4,4,4,4,5,1
21,권민서,5,3,2,2,1,2,2,2,3

In [12]:
'''
인기 : 조서윤, 정채원 안맞음
'''

'\n인기 : 조서윤, 정채원 안맞음\n'

### 또래지명과 학생평가 일치율 산출 함수

In [13]:
def calculate_euclidean_distance_between_peer_nomination_and_student_evaluation(calculate_scale_scores_by_peer_nomination_df, calculate_scale_scores_by_student_evaluation_df) :
    """
    또래지명 척도별 점수와 학생평가 척도별 점수 간의 유클리드 거리를 계산하는 함수
    """
    euclidean_list = []
    for idx in range(1,len(calculate_scale_scores_by_peer_nomination_df.columns)):
        a_list = calculate_scale_scores_by_peer_nomination_df.iloc[:, idx]
        b_list = calculate_scale_scores_by_student_evaluation_df.iloc[:, idx]
        diff_list = []
        for a, b in zip(a_list, b_list) :
            diff = a - b
            diff_list.append(diff)
        squ_list = [i**2 for i in diff_list]
        sum_value = sum(squ_list)
        root_value = sum_value**0.5
        max_value = (len(calculate_scale_scores_by_peer_nomination_df)*16)**0.5
        euclidean_value = (1-(root_value/max_value))*100
        euclidean_value = max(0, euclidean_value)
        euclidean_list.append(euclidean_value)
    return pd.DataFrame({
        '척도' : list(calculate_scale_scores_by_peer_nomination_df.columns[1:]),
        '일치율' : euclidean_list
    })

In [14]:
euclidean_df = calculate_euclidean_distance_between_peer_nomination_and_student_evaluation(calculate_scale_scores_by_peer_nomination_df, calculate_scale_scores_by_student_evaluation_df)
print(euclidean_df)

           척도        일치율
0      인기_정규화  56.698730
1   사회적선호_정규화  41.856369
2  외현적공격성_정규화  58.371229
3  관계적공격성_정규화  57.028022
4    친사회성_정규화  45.644269
5      가해_정규화  45.644269
6      피해_정규화  49.154870
7    교사선호_정규화  46.966991
8   교사비선호_정규화  45.383569

In [ ]:
'''
인기가 안맞음
'''

'\n인기가 안맞음\n'

## 교사역량 평가

In [15]:
teacher_competency_df = pd.read_excel('5학년_1반_전수(AC000120255019FA1)/AC000120255019FA1_교사_학급평가_응답.xlsx')
print(teacher_competency_df)

                                                 응답값
0  {"questionChoiceList":[{"questionNo":1,"choice...

In [16]:
import json

response_arr = None
for i in range(len(teacher_competency_df['응답값'])):
    json_data = teacher_competency_df['응답값'][i]
    json_data = json.loads(json_data)
    response_json_data = json_data['questionChoiceList']
    response_data = []

    for item in response_json_data:
        print(item)
        response_data.append(item['choiceScore'])
    if response_arr is None:
        response_arr = np.array(response_data)
        print(response_arr)
    else:
        response_arr = np.vstack([response_arr, response_data])

{'questionNo': 1, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 2, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 3, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 4, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 5, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 6, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 7, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 8, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 9, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 10, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 11, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 12, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 13, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 14, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 15, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 16, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 17, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 18, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 19, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 20, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 21, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 22, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 23, 'choiceNo': '3', 'choiceScore': '3'}
['3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3'
 '3' '3' '3' '3' '3']

In [17]:
def calculate_teacher_competency_scores(teacher_competency_df):
    """
    교사 평가 json으로 교사별 역량 점수를 계산하는 함수
    """
    response_arr = None
    for i in range(len(teacher_competency_df['응답값'])):
        json_data = teacher_competency_df['응답값'][i]
        json_data = json.loads(json_data)
        response_json_data = json_data['questionChoiceList']
        response_data = []

        for item in response_json_data:
            print(item)
            response_data.append(item['choiceScore'])
        if response_arr is None:
            response_arr = np.array(response_data)
            print(response_arr)
        else:
            response_arr = np.vstack([response_arr, response_data])
    teacher_competency_df = pd.DataFrame([response_arr])
    teacher_competency_df.columns = [i for i in range(1, 24)]
    teacher_competency_df[[i for i in range(1,24)]] = teacher_competency_df[[i for i in range(1,24)]].apply(pd.to_numeric, errors='coerce')

    # 평등한 지위관리
    equalstatus_management_item_no = [1,2,3,4,5,6]
    equalstatus_management_df = teacher_competency_df[equalstatus_management_item_no]
    equalstatus_management_value = equalstatus_management_df.mean(axis=1).iloc[0]
    # 소외 학생 관리
    marginalized_student_management_item_no = [7,8,9,10]
    marginalized_student_management_df = teacher_competency_df[marginalized_student_management_item_no]
    marginalized_student_management_value = marginalized_student_management_df.mean(axis=1).iloc[0]
    # 문제행동 관리
    problem_behavior_management_item_no = [11,12,13]
    problem_behavior_management_df = teacher_competency_df[problem_behavior_management_item_no]
    problem_behavior_management_value = problem_behavior_management_df.mean(axis=1).iloc[0]
    # 공격성 관리
    aggression_management_item_no = [14,15,16,17,18]
    aggression_management_df = teacher_competency_df[aggression_management_item_no]
    aggression_management_value = aggression_management_df.mean(axis=1).iloc[0]
    # 긍정적 분위기 조성
    positive_atmosphere_item_no = [19, 20, 21, 22, 23]
    positive_atmosphere_df = teacher_competency_df[positive_atmosphere_item_no]
    positive_atmosphere_value = positive_atmosphere_df.mean(axis=1).iloc[0]

    return pd.DataFrame([{
        '평등한지위관리': equalstatus_management_value,
        '소외학생관리': marginalized_student_management_value,
        '문제행동관리': problem_behavior_management_value,
        '공격성관리': aggression_management_value,
        '긍정적분위기조성': positive_atmosphere_value
    }])

In [18]:
df = calculate_teacher_competency_scores(teacher_competency_df)

{'questionNo': 1, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 2, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 3, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 4, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 5, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 6, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 7, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 8, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 9, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 10, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 11, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 12, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 13, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 14, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 15, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 16, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 17, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 18, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 19, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 20, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 21, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 22, 'choiceNo': '3', 'choiceScore': '3'}
{'questionNo': 23, 'choiceNo': '3', 'choiceScore': '3'}
['3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3'
 '3' '3' '3' '3' '3']

In [19]:
df

   평등한지위관리  소외학생관리  문제행동관리  공격성관리  긍정적분위기조성
0      3.0     3.0     3.0    3.0       3.0

In [ ]:
'''
이건 왜 첫째자리 반올림이지?
'''

'\n이건 왜 첫째자리 반올림이지?\n'